# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Bilibili-App-API resource.

OpenAPI tag: ``Bilibili-App-API``
SDK attribute: ``client.bilibili_app`` / ``async_client.bilibili_app``

Endpoints: 11
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncBilibiliApp", "BilibiliApp"]


class BilibiliApp(SyncResource):
    """Sync ``Bilibili-App-API`` resource (11 endpoints)."""

    def fetch_one_video(
        self,
        *,
        av_id: str | None = None,
        bv_id: str | None = None,
    ) -> Any:
        """获取单个视频详情信息/Get single video data

        ``GET /api/v1/bilibili/app/fetch_one_video``
        """
        params = _drop_none({
            "av_id": av_id,
            "bv_id": bv_id,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_one_video", params=params)

    def fetch_video_comments(
        self,
        *,
        av_id: str | None = None,
        bv_id: str | None = None,
        mode: int | None = None,
        next_offset: int | None = None,
    ) -> Any:
        """获取视频评论列表/Get video comments

        ``GET /api/v1/bilibili/app/fetch_video_comments``
        """
        params = _drop_none({
            "av_id": av_id,
            "bv_id": bv_id,
            "mode": mode,
            "next_offset": next_offset,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_video_comments", params=params)

    def fetch_reply_detail(
        self,
        *,
        root: str,
        av_id: str | None = None,
        bv_id: str | None = None,
        next_offset: int | None = None,
        ps: int | None = None,
    ) -> Any:
        """获取二级评论回复/Get reply detail

        ``GET /api/v1/bilibili/app/fetch_reply_detail``
        """
        params = _drop_none({
            "root": root,
            "av_id": av_id,
            "bv_id": bv_id,
            "next_offset": next_offset,
            "ps": ps,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_reply_detail", params=params)

    def fetch_user_videos(
        self,
        *,
        user_id: str,
        post_filter: str | None = None,
        page: int | None = None,
        ps: int | None = None,
    ) -> Any:
        """获取用户投稿视频/Get user videos

        ``GET /api/v1/bilibili/app/fetch_user_videos``
        """
        params = _drop_none({
            "user_id": user_id,
            "post_filter": post_filter,
            "page": page,
            "ps": ps,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_user_videos", params=params)

    def fetch_user_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户信息/Get user info

        ``GET /api/v1/bilibili/app/fetch_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_user_info", params=params)

    def fetch_home_feed(
        self,
        *,
        idx: int | None = None,
        flush: int | None = None,
        pull: bool | None = None,
    ) -> Any:
        """获取主页推荐视频流/Get home feed

        ``GET /api/v1/bilibili/app/fetch_home_feed``
        """
        params = _drop_none({
            "idx": idx,
            "flush": flush,
            "pull": pull,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_home_feed", params=params)

    def fetch_popular_feed(
        self,
        *,
        idx: int | None = None,
        last_param: str | None = None,
    ) -> Any:
        """获取热门推荐/Get popular feed

        ``GET /api/v1/bilibili/app/fetch_popular_feed``
        """
        params = _drop_none({
            "idx": idx,
            "last_param": last_param,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_popular_feed", params=params)

    def fetch_search_all(
        self,
        *,
        keyword: str,
        page: int | None = None,
        page_size: int | None = None,
        order: int | None = None,
    ) -> Any:
        """综合搜索/search all

        ``GET /api/v1/bilibili/app/fetch_search_all``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "page_size": page_size,
            "order": order,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_search_all", params=params)

    def fetch_search_by_type(
        self,
        *,
        keyword: str,
        search_type: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        order: int | None = None,
    ) -> Any:
        """分类搜索/ search by type

        ``GET /api/v1/bilibili/app/fetch_search_by_type``
        """
        params = _drop_none({
            "keyword": keyword,
            "search_type": search_type,
            "page": page,
            "page_size": page_size,
            "order": order,
        })
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_search_by_type", params=params)

    def fetch_cinema_tab(
        self,
    ) -> Any:
        """获取影视推荐/Get cinema tab

        ``GET /api/v1/bilibili/app/fetch_cinema_tab``
        """
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_cinema_tab")

    def fetch_bangumi_tab(
        self,
    ) -> Any:
        """获取番剧推荐/Get bangumi tab

        ``GET /api/v1/bilibili/app/fetch_bangumi_tab``
        """
        return self._client._request("GET", "/api/v1/bilibili/app/fetch_bangumi_tab")


class AsyncBilibiliApp(AsyncResource):
    """Async ``Bilibili-App-API`` resource (11 endpoints)."""

    async def fetch_one_video(
        self,
        *,
        av_id: str | None = None,
        bv_id: str | None = None,
    ) -> Any:
        """获取单个视频详情信息/Get single video data

        ``GET /api/v1/bilibili/app/fetch_one_video``
        """
        params = _drop_none({
            "av_id": av_id,
            "bv_id": bv_id,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_one_video", params=params)

    async def fetch_video_comments(
        self,
        *,
        av_id: str | None = None,
        bv_id: str | None = None,
        mode: int | None = None,
        next_offset: int | None = None,
    ) -> Any:
        """获取视频评论列表/Get video comments

        ``GET /api/v1/bilibili/app/fetch_video_comments``
        """
        params = _drop_none({
            "av_id": av_id,
            "bv_id": bv_id,
            "mode": mode,
            "next_offset": next_offset,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_video_comments", params=params)

    async def fetch_reply_detail(
        self,
        *,
        root: str,
        av_id: str | None = None,
        bv_id: str | None = None,
        next_offset: int | None = None,
        ps: int | None = None,
    ) -> Any:
        """获取二级评论回复/Get reply detail

        ``GET /api/v1/bilibili/app/fetch_reply_detail``
        """
        params = _drop_none({
            "root": root,
            "av_id": av_id,
            "bv_id": bv_id,
            "next_offset": next_offset,
            "ps": ps,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_reply_detail", params=params)

    async def fetch_user_videos(
        self,
        *,
        user_id: str,
        post_filter: str | None = None,
        page: int | None = None,
        ps: int | None = None,
    ) -> Any:
        """获取用户投稿视频/Get user videos

        ``GET /api/v1/bilibili/app/fetch_user_videos``
        """
        params = _drop_none({
            "user_id": user_id,
            "post_filter": post_filter,
            "page": page,
            "ps": ps,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_user_videos", params=params)

    async def fetch_user_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户信息/Get user info

        ``GET /api/v1/bilibili/app/fetch_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_user_info", params=params)

    async def fetch_home_feed(
        self,
        *,
        idx: int | None = None,
        flush: int | None = None,
        pull: bool | None = None,
    ) -> Any:
        """获取主页推荐视频流/Get home feed

        ``GET /api/v1/bilibili/app/fetch_home_feed``
        """
        params = _drop_none({
            "idx": idx,
            "flush": flush,
            "pull": pull,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_home_feed", params=params)

    async def fetch_popular_feed(
        self,
        *,
        idx: int | None = None,
        last_param: str | None = None,
    ) -> Any:
        """获取热门推荐/Get popular feed

        ``GET /api/v1/bilibili/app/fetch_popular_feed``
        """
        params = _drop_none({
            "idx": idx,
            "last_param": last_param,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_popular_feed", params=params)

    async def fetch_search_all(
        self,
        *,
        keyword: str,
        page: int | None = None,
        page_size: int | None = None,
        order: int | None = None,
    ) -> Any:
        """综合搜索/search all

        ``GET /api/v1/bilibili/app/fetch_search_all``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "page_size": page_size,
            "order": order,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_search_all", params=params)

    async def fetch_search_by_type(
        self,
        *,
        keyword: str,
        search_type: str | None = None,
        page: int | None = None,
        page_size: int | None = None,
        order: int | None = None,
    ) -> Any:
        """分类搜索/ search by type

        ``GET /api/v1/bilibili/app/fetch_search_by_type``
        """
        params = _drop_none({
            "keyword": keyword,
            "search_type": search_type,
            "page": page,
            "page_size": page_size,
            "order": order,
        })
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_search_by_type", params=params)

    async def fetch_cinema_tab(
        self,
    ) -> Any:
        """获取影视推荐/Get cinema tab

        ``GET /api/v1/bilibili/app/fetch_cinema_tab``
        """
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_cinema_tab")

    async def fetch_bangumi_tab(
        self,
    ) -> Any:
        """获取番剧推荐/Get bangumi tab

        ``GET /api/v1/bilibili/app/fetch_bangumi_tab``
        """
        return await self._client._request("GET", "/api/v1/bilibili/app/fetch_bangumi_tab")
