# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Demo-API resource.

OpenAPI tag: ``Demo-API``
SDK attribute: ``client.demo`` / ``async_client.demo``

Endpoints: 9
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDemo", "Demo"]


class Demo(SyncResource):
    """Sync ``Demo-API`` resource (9 endpoints)."""

    def cache_status(
        self,
    ) -> Any:
        """查看Demo缓存状态/View Demo Cache Status

        ``GET /api/v1/demo/demo/cache_status``
        """
        return self._client._request("GET", "/api/v1/demo/demo/cache_status")

    def douyin_web_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】抖音Web获取固定作品数据（1小时缓存）/[Demo] Fetch Douyin Web Fixed Video Data with Cache

        ``GET /api/v1/demo/douyin/web/fetch_one_video``
        """
        return self._client._request("GET", "/api/v1/demo/douyin/web/fetch_one_video")

    def douyin_app_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】抖音APP获取固定作品数据（1小时缓存）/[Demo] Fetch Douyin APP Fixed Video Data with Cache

        ``GET /api/v1/demo/douyin/app/fetch_one_video``
        """
        return self._client._request("GET", "/api/v1/demo/douyin/app/fetch_one_video")

    def general_search(
        self,
    ) -> Any:
        """【Demo】抖音搜索综合搜索（1小时缓存）/[Demo] Douyin General Search with Cache

        ``GET /api/v1/demo/douyin_search/app/general_search``
        """
        return self._client._request("GET", "/api/v1/demo/douyin_search/app/general_search")

    def kuaishou_web_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】快手获取固定视频信息（1小时缓存）/[Demo] Kuaishou Fixed Video with Cache

        ``GET /api/v1/demo/kuaishou/web/fetch_one_video``
        """
        return self._client._request("GET", "/api/v1/demo/kuaishou/web/fetch_one_video")

    def fetch_user_profile(
        self,
    ) -> Any:
        """【Demo】TikTok固定用户信息（1小时缓存）/[Demo] TikTok Fixed User Profile with Cache

        ``GET /api/v1/demo/tiktok/web/fetch_user_profile``
        """
        return self._client._request("GET", "/api/v1/demo/tiktok/web/fetch_user_profile")

    def tiktok_app_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】TikTok APP获取固定视频详情（1小时缓存）/[Demo] TikTok APP Fixed Video Detail with Cache

        ``GET /api/v1/demo/tiktok/app/fetch_one_video``
        """
        return self._client._request("GET", "/api/v1/demo/tiktok/app/fetch_one_video")

    def fetch_user_info(
        self,
    ) -> Any:
        """【Demo】Instagram获取固定用户信息（1小时缓存）/[Demo] Instagram Fixed User Profile with Cache

        ``GET /api/v1/demo/instagram/web/fetch_user_info``
        """
        return self._client._request("GET", "/api/v1/demo/instagram/web/fetch_user_info")

    def article_extract(
        self,
    ) -> Any:
        """【Demo】微信公众号文章提取（1小时缓存）/[Demo] WeChat Article Extract with Cache

        ``GET /api/v1/demo/wechat/article_extract``
        """
        return self._client._request("GET", "/api/v1/demo/wechat/article_extract")


class AsyncDemo(AsyncResource):
    """Async ``Demo-API`` resource (9 endpoints)."""

    async def cache_status(
        self,
    ) -> Any:
        """查看Demo缓存状态/View Demo Cache Status

        ``GET /api/v1/demo/demo/cache_status``
        """
        return await self._client._request("GET", "/api/v1/demo/demo/cache_status")

    async def douyin_web_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】抖音Web获取固定作品数据（1小时缓存）/[Demo] Fetch Douyin Web Fixed Video Data with Cache

        ``GET /api/v1/demo/douyin/web/fetch_one_video``
        """
        return await self._client._request("GET", "/api/v1/demo/douyin/web/fetch_one_video")

    async def douyin_app_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】抖音APP获取固定作品数据（1小时缓存）/[Demo] Fetch Douyin APP Fixed Video Data with Cache

        ``GET /api/v1/demo/douyin/app/fetch_one_video``
        """
        return await self._client._request("GET", "/api/v1/demo/douyin/app/fetch_one_video")

    async def general_search(
        self,
    ) -> Any:
        """【Demo】抖音搜索综合搜索（1小时缓存）/[Demo] Douyin General Search with Cache

        ``GET /api/v1/demo/douyin_search/app/general_search``
        """
        return await self._client._request("GET", "/api/v1/demo/douyin_search/app/general_search")

    async def kuaishou_web_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】快手获取固定视频信息（1小时缓存）/[Demo] Kuaishou Fixed Video with Cache

        ``GET /api/v1/demo/kuaishou/web/fetch_one_video``
        """
        return await self._client._request("GET", "/api/v1/demo/kuaishou/web/fetch_one_video")

    async def fetch_user_profile(
        self,
    ) -> Any:
        """【Demo】TikTok固定用户信息（1小时缓存）/[Demo] TikTok Fixed User Profile with Cache

        ``GET /api/v1/demo/tiktok/web/fetch_user_profile``
        """
        return await self._client._request("GET", "/api/v1/demo/tiktok/web/fetch_user_profile")

    async def tiktok_app_fetch_one_video(
        self,
    ) -> Any:
        """【Demo】TikTok APP获取固定视频详情（1小时缓存）/[Demo] TikTok APP Fixed Video Detail with Cache

        ``GET /api/v1/demo/tiktok/app/fetch_one_video``
        """
        return await self._client._request("GET", "/api/v1/demo/tiktok/app/fetch_one_video")

    async def fetch_user_info(
        self,
    ) -> Any:
        """【Demo】Instagram获取固定用户信息（1小时缓存）/[Demo] Instagram Fixed User Profile with Cache

        ``GET /api/v1/demo/instagram/web/fetch_user_info``
        """
        return await self._client._request("GET", "/api/v1/demo/instagram/web/fetch_user_info")

    async def article_extract(
        self,
    ) -> Any:
        """【Demo】微信公众号文章提取（1小时缓存）/[Demo] WeChat Article Extract with Cache

        ``GET /api/v1/demo/wechat/article_extract``
        """
        return await self._client._request("GET", "/api/v1/demo/wechat/article_extract")
