# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Search-API resource.

OpenAPI tag: ``Douyin-Search-API``
SDK attribute: ``client.douyin_search`` / ``async_client.douyin_search``

Endpoints: 19
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinSearch", "DouyinSearch"]


class DouyinSearch(SyncResource):
    """Sync ``Douyin-Search-API`` resource (19 endpoints)."""

    def fetch_general_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取综合搜索 V1/Fetch general search V1

        ``POST /api/v1/douyin/search/fetch_general_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_general_search_v1", json=json_body)

    def fetch_general_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取综合搜索 V2/Fetch general search V2

        ``POST /api/v1/douyin/search/fetch_general_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_general_search_v2", json=json_body)

    def fetch_search_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取搜索关键词推荐/Fetch search keyword suggestions

        ``POST /api/v1/douyin/search/fetch_search_suggest``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_search_suggest", json=json_body)

    def fetch_video_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取视频搜索 V1/Fetch video search V1

        ``POST /api/v1/douyin/search/fetch_video_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_video_search_v1", json=json_body)

    def fetch_video_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取视频搜索 V2/Fetch video search V2

        ``POST /api/v1/douyin/search/fetch_video_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_video_search_v2", json=json_body)

    def fetch_multi_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取多重搜索/Fetch multi-type search

        ``POST /api/v1/douyin/search/fetch_multi_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_multi_search", json=json_body)

    def fetch_user_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        douyin_user_fans: str | None = None,
        douyin_user_type: str | None = None,
        search_id: str | None = None,
    ) -> Any:
        """获取用户搜索/Fetch user search

        ``POST /api/v1/douyin/search/fetch_user_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "douyin_user_fans": douyin_user_fans,
            "douyin_user_type": douyin_user_type,
            "search_id": search_id,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_user_search", json=json_body)

    def fetch_user_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
    ) -> Any:
        """获取用户搜索 V2/Fetch user search V2

        ``POST /api/v1/douyin/search/fetch_user_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_user_search_v2", json=json_body)

    def fetch_image_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取图片搜索/Fetch image search

        ``POST /api/v1/douyin/search/fetch_image_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_image_search", json=json_body)

    def fetch_image_search_v3(
        self,
        *,
        keyword: str,
        cursor: int | None = None,
        search_id: str | None = None,
    ) -> Any:
        """获取图文搜索 V3/Fetch image-text search V3

        ``POST /api/v1/douyin/search/fetch_image_search_v3``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "search_id": search_id,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_image_search_v3", json=json_body)

    def fetch_live_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取直播搜索 V1/Fetch live search V1

        ``POST /api/v1/douyin/search/fetch_live_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_live_search_v1", json=json_body)

    def fetch_challenge_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取话题搜索 V1/Fetch hashtag search V1

        ``POST /api/v1/douyin/search/fetch_challenge_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_search_v1", json=json_body)

    def fetch_challenge_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取话题搜索 V2/Fetch hashtag search V2

        ``POST /api/v1/douyin/search/fetch_challenge_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_search_v2", json=json_body)

    def fetch_challenge_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取话题推荐搜索/Fetch hashtag suggestions

        ``POST /api/v1/douyin/search/fetch_challenge_suggest``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_suggest", json=json_body)

    def fetch_experience_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取经验搜索/Fetch experience search

        ``POST /api/v1/douyin/search/fetch_experience_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_experience_search", json=json_body)

    def fetch_music_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取音乐搜索/Fetch music search

        ``POST /api/v1/douyin/search/fetch_music_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_music_search", json=json_body)

    def fetch_discuss_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取讨论搜索/Fetch discussion search

        ``POST /api/v1/douyin/search/fetch_discuss_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_discuss_search", json=json_body)

    def fetch_school_search(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取学校搜索/Fetch school search

        ``POST /api/v1/douyin/search/fetch_school_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_school_search", json=json_body)

    def fetch_vision_search(
        self,
        *,
        image_uri: str,
        cursor: int | None = None,
        search_id: str | None = None,
        search_source: str | None = None,
        detection: str | None = None,
        detection_index: int | None = None,
        user_query: str | None = None,
        aweme_id: str | None = None,
    ) -> Any:
        """获取图像识别搜索/Fetch vision search (image-based search)

        ``POST /api/v1/douyin/search/fetch_vision_search``
        """
        json_body = _drop_none({
            "image_uri": image_uri,
            "cursor": cursor,
            "search_id": search_id,
            "search_source": search_source,
            "detection": detection,
            "detection_index": detection_index,
            "user_query": user_query,
            "aweme_id": aweme_id,
        })
        return self._client._request("POST", "/api/v1/douyin/search/fetch_vision_search", json=json_body)


class AsyncDouyinSearch(AsyncResource):
    """Async ``Douyin-Search-API`` resource (19 endpoints)."""

    async def fetch_general_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取综合搜索 V1/Fetch general search V1

        ``POST /api/v1/douyin/search/fetch_general_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_general_search_v1", json=json_body)

    async def fetch_general_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取综合搜索 V2/Fetch general search V2

        ``POST /api/v1/douyin/search/fetch_general_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_general_search_v2", json=json_body)

    async def fetch_search_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取搜索关键词推荐/Fetch search keyword suggestions

        ``POST /api/v1/douyin/search/fetch_search_suggest``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_search_suggest", json=json_body)

    async def fetch_video_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取视频搜索 V1/Fetch video search V1

        ``POST /api/v1/douyin/search/fetch_video_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_video_search_v1", json=json_body)

    async def fetch_video_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取视频搜索 V2/Fetch video search V2

        ``POST /api/v1/douyin/search/fetch_video_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_video_search_v2", json=json_body)

    async def fetch_multi_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取多重搜索/Fetch multi-type search

        ``POST /api/v1/douyin/search/fetch_multi_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_multi_search", json=json_body)

    async def fetch_user_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        douyin_user_fans: str | None = None,
        douyin_user_type: str | None = None,
        search_id: str | None = None,
    ) -> Any:
        """获取用户搜索/Fetch user search

        ``POST /api/v1/douyin/search/fetch_user_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "douyin_user_fans": douyin_user_fans,
            "douyin_user_type": douyin_user_type,
            "search_id": search_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_user_search", json=json_body)

    async def fetch_user_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
    ) -> Any:
        """获取用户搜索 V2/Fetch user search V2

        ``POST /api/v1/douyin/search/fetch_user_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_user_search_v2", json=json_body)

    async def fetch_image_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取图片搜索/Fetch image search

        ``POST /api/v1/douyin/search/fetch_image_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_image_search", json=json_body)

    async def fetch_image_search_v3(
        self,
        *,
        keyword: str,
        cursor: int | None = None,
        search_id: str | None = None,
    ) -> Any:
        """获取图文搜索 V3/Fetch image-text search V3

        ``POST /api/v1/douyin/search/fetch_image_search_v3``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "search_id": search_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_image_search_v3", json=json_body)

    async def fetch_live_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取直播搜索 V1/Fetch live search V1

        ``POST /api/v1/douyin/search/fetch_live_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_live_search_v1", json=json_body)

    async def fetch_challenge_search_v1(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取话题搜索 V1/Fetch hashtag search V1

        ``POST /api/v1/douyin/search/fetch_challenge_search_v1``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_search_v1", json=json_body)

    async def fetch_challenge_search_v2(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取话题搜索 V2/Fetch hashtag search V2

        ``POST /api/v1/douyin/search/fetch_challenge_search_v2``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_search_v2", json=json_body)

    async def fetch_challenge_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取话题推荐搜索/Fetch hashtag suggestions

        ``POST /api/v1/douyin/search/fetch_challenge_suggest``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_challenge_suggest", json=json_body)

    async def fetch_experience_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取经验搜索/Fetch experience search

        ``POST /api/v1/douyin/search/fetch_experience_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_experience_search", json=json_body)

    async def fetch_music_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取音乐搜索/Fetch music search

        ``POST /api/v1/douyin/search/fetch_music_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_music_search", json=json_body)

    async def fetch_discuss_search(
        self,
        *,
        keyword: str | None = None,
        cursor: int | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        filter_duration: str | None = None,
        content_type: str | None = None,
        search_id: str | None = None,
        backtrace: str | None = None,
    ) -> Any:
        """获取讨论搜索/Fetch discussion search

        ``POST /api/v1/douyin/search/fetch_discuss_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "filter_duration": filter_duration,
            "content_type": content_type,
            "search_id": search_id,
            "backtrace": backtrace,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_discuss_search", json=json_body)

    async def fetch_school_search(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取学校搜索/Fetch school search

        ``POST /api/v1/douyin/search/fetch_school_search``
        """
        json_body = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_school_search", json=json_body)

    async def fetch_vision_search(
        self,
        *,
        image_uri: str,
        cursor: int | None = None,
        search_id: str | None = None,
        search_source: str | None = None,
        detection: str | None = None,
        detection_index: int | None = None,
        user_query: str | None = None,
        aweme_id: str | None = None,
    ) -> Any:
        """获取图像识别搜索/Fetch vision search (image-based search)

        ``POST /api/v1/douyin/search/fetch_vision_search``
        """
        json_body = _drop_none({
            "image_uri": image_uri,
            "cursor": cursor,
            "search_id": search_id,
            "search_source": search_source,
            "detection": detection,
            "detection_index": detection_index,
            "user_query": user_query,
            "aweme_id": aweme_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/search/fetch_vision_search", json=json_body)
