# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Creator-V2-API resource.

OpenAPI tag: ``Douyin-Creator-V2-API``
SDK attribute: ``client.douyin_creator_v2`` / ``async_client.douyin_creator_v2``

Endpoints: 14
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinCreatorV2", "DouyinCreatorV2"]


class DouyinCreatorV2(SyncResource):
    """Sync ``Douyin-Creator-V2-API`` resource (14 endpoints)."""

    def fetch_item_overview_data(
        self,
        *,
        cookie: str,
        ids: str,
        fields: Any | None = None,
    ) -> Any:
        """获取作品总览数据/Fetch item overview data

        ``POST /api/v1/douyin/creator_v2/fetch_item_overview_data``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "ids": ids,
            "fields": fields,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_overview_data", json=json_body)

    def fetch_item_play_source(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品流量来源统计/Fetch item play source statistics

        ``POST /api/v1/douyin/creator_v2/fetch_item_play_source``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_play_source", json=json_body)

    def fetch_item_search_keyword(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品搜索关键词统计/Fetch item search keywords statistics

        ``POST /api/v1/douyin/creator_v2/fetch_item_search_keyword``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_search_keyword", json=json_body)

    def fetch_item_watch_trend(
        self,
        *,
        cookie: str,
        item_id: str,
        analysis_type: int | None = None,
    ) -> Any:
        """获取作品观看趋势分析/Fetch item watch trend analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_watch_trend``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
            "analysis_type": analysis_type,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_watch_trend", json=json_body)

    def fetch_item_danmaku_analysis(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品弹幕分析/Fetch item bullet analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_danmaku_analysis``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_danmaku_analysis", json=json_body)

    def fetch_item_audience_portrait(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品观众数据分析/Fetch item audience portrait

        ``POST /api/v1/douyin/creator_v2/fetch_item_audience_portrait``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_audience_portrait", json=json_body)

    def fetch_item_audience_others(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品观众其他数据分析/Fetch item audience others analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_audience_others``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_audience_others", json=json_body)

    def fetch_item_analysis_involved_vertical(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """获取作品垂类标签/Fetch item analysis involved vertical

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_involved_vertical``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_involved_vertical", json=json_body)

    def fetch_item_analysis_overview(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        primary_verticals: list[Any],
        genres: list[Any] | None = None,
    ) -> Any:
        """获取投稿分析概览/Fetch item analysis overview

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_overview``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "genres": genres,
            "primary_verticals": primary_verticals,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_overview", json=json_body)

    def fetch_item_analysis_item_performance(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        primary_verticals: list[Any],
        genres: list[Any] | None = None,
        metric_type: int | None = None,
    ) -> Any:
        """获取投稿表现数据/Fetch item analysis item performance

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_item_performance``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "genres": genres,
            "primary_verticals": primary_verticals,
            "metric_type": metric_type,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_item_performance", json=json_body)

    def fetch_item_list(
        self,
        *,
        cookie: str,
        start_time: int,
        end_time: int,
        count: int | None = None,
        order_by: int | None = None,
        fields: str | None = None,
        need_cooperation: bool | None = None,
        need_long_article: bool | None = None,
        cursor: Any | None = None,
    ) -> Any:
        """获取投稿作品列表/Fetch item list

        ``POST /api/v1/douyin/creator_v2/fetch_item_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "count": count,
            "order_by": order_by,
            "fields": fields,
            "need_cooperation": need_cooperation,
            "start_time": start_time,
            "end_time": end_time,
            "need_long_article": need_long_article,
            "cursor": cursor,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_list", json=json_body)

    def fetch_item_list_download(
        self,
        *,
        cookie: str,
        min_cursor: int,
        max_cursor: int,
        type_filters: list[Any] | None = None,
        need_long_article: bool | None = None,
    ) -> Any:
        """导出投稿作品列表/Download item list

        ``POST /api/v1/douyin/creator_v2/fetch_item_list_download``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "min_cursor": min_cursor,
            "max_cursor": max_cursor,
            "type_filters": type_filters,
            "need_long_article": need_long_article,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_list_download", json=json_body)

    def fetch_live_room_history_list(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        limit: int | None = None,
        need_living: int | None = None,
        download: int | None = None,
    ) -> Any:
        """获取直播场次历史记录/Fetch live room history list

        ``POST /api/v1/douyin/creator_v2/fetch_live_room_history_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "limit": limit,
            "need_living": need_living,
            "download": download,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_live_room_history_list", json=json_body)

    def fetch_author_diagnosis(
        self,
        *,
        cookie: str,
    ) -> Any:
        """获取创作者账号诊断/Fetch author diagnosis

        ``POST /api/v1/douyin/creator_v2/fetch_author_diagnosis``
        """
        json_body = _drop_none({
            "cookie": cookie,
        })
        return self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_author_diagnosis", json=json_body)


class AsyncDouyinCreatorV2(AsyncResource):
    """Async ``Douyin-Creator-V2-API`` resource (14 endpoints)."""

    async def fetch_item_overview_data(
        self,
        *,
        cookie: str,
        ids: str,
        fields: Any | None = None,
    ) -> Any:
        """获取作品总览数据/Fetch item overview data

        ``POST /api/v1/douyin/creator_v2/fetch_item_overview_data``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "ids": ids,
            "fields": fields,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_overview_data", json=json_body)

    async def fetch_item_play_source(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品流量来源统计/Fetch item play source statistics

        ``POST /api/v1/douyin/creator_v2/fetch_item_play_source``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_play_source", json=json_body)

    async def fetch_item_search_keyword(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品搜索关键词统计/Fetch item search keywords statistics

        ``POST /api/v1/douyin/creator_v2/fetch_item_search_keyword``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_search_keyword", json=json_body)

    async def fetch_item_watch_trend(
        self,
        *,
        cookie: str,
        item_id: str,
        analysis_type: int | None = None,
    ) -> Any:
        """获取作品观看趋势分析/Fetch item watch trend analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_watch_trend``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
            "analysis_type": analysis_type,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_watch_trend", json=json_body)

    async def fetch_item_danmaku_analysis(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品弹幕分析/Fetch item bullet analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_danmaku_analysis``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_danmaku_analysis", json=json_body)

    async def fetch_item_audience_portrait(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品观众数据分析/Fetch item audience portrait

        ``POST /api/v1/douyin/creator_v2/fetch_item_audience_portrait``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_audience_portrait", json=json_body)

    async def fetch_item_audience_others(
        self,
        *,
        cookie: str,
        item_id: str,
    ) -> Any:
        """获取作品观众其他数据分析/Fetch item audience others analysis

        ``POST /api/v1/douyin/creator_v2/fetch_item_audience_others``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_audience_others", json=json_body)

    async def fetch_item_analysis_involved_vertical(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
    ) -> Any:
        """获取作品垂类标签/Fetch item analysis involved vertical

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_involved_vertical``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_involved_vertical", json=json_body)

    async def fetch_item_analysis_overview(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        primary_verticals: list[Any],
        genres: list[Any] | None = None,
    ) -> Any:
        """获取投稿分析概览/Fetch item analysis overview

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_overview``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "genres": genres,
            "primary_verticals": primary_verticals,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_overview", json=json_body)

    async def fetch_item_analysis_item_performance(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        primary_verticals: list[Any],
        genres: list[Any] | None = None,
        metric_type: int | None = None,
    ) -> Any:
        """获取投稿表现数据/Fetch item analysis item performance

        ``POST /api/v1/douyin/creator_v2/fetch_item_analysis_item_performance``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "genres": genres,
            "primary_verticals": primary_verticals,
            "metric_type": metric_type,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_analysis_item_performance", json=json_body)

    async def fetch_item_list(
        self,
        *,
        cookie: str,
        start_time: int,
        end_time: int,
        count: int | None = None,
        order_by: int | None = None,
        fields: str | None = None,
        need_cooperation: bool | None = None,
        need_long_article: bool | None = None,
        cursor: Any | None = None,
    ) -> Any:
        """获取投稿作品列表/Fetch item list

        ``POST /api/v1/douyin/creator_v2/fetch_item_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "count": count,
            "order_by": order_by,
            "fields": fields,
            "need_cooperation": need_cooperation,
            "start_time": start_time,
            "end_time": end_time,
            "need_long_article": need_long_article,
            "cursor": cursor,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_list", json=json_body)

    async def fetch_item_list_download(
        self,
        *,
        cookie: str,
        min_cursor: int,
        max_cursor: int,
        type_filters: list[Any] | None = None,
        need_long_article: bool | None = None,
    ) -> Any:
        """导出投稿作品列表/Download item list

        ``POST /api/v1/douyin/creator_v2/fetch_item_list_download``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "min_cursor": min_cursor,
            "max_cursor": max_cursor,
            "type_filters": type_filters,
            "need_long_article": need_long_article,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_item_list_download", json=json_body)

    async def fetch_live_room_history_list(
        self,
        *,
        cookie: str,
        start_date: str,
        end_date: str,
        limit: int | None = None,
        need_living: int | None = None,
        download: int | None = None,
    ) -> Any:
        """获取直播场次历史记录/Fetch live room history list

        ``POST /api/v1/douyin/creator_v2/fetch_live_room_history_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "start_date": start_date,
            "end_date": end_date,
            "limit": limit,
            "need_living": need_living,
            "download": download,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_live_room_history_list", json=json_body)

    async def fetch_author_diagnosis(
        self,
        *,
        cookie: str,
    ) -> Any:
        """获取创作者账号诊断/Fetch author diagnosis

        ``POST /api/v1/douyin/creator_v2/fetch_author_diagnosis``
        """
        json_body = _drop_none({
            "cookie": cookie,
        })
        return await self._client._request("POST", "/api/v1/douyin/creator_v2/fetch_author_diagnosis", json=json_body)
