# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Douyin-Xingtu-API resource.

OpenAPI tag: ``Douyin-Xingtu-API``
SDK attribute: ``client.douyin_xingtu`` / ``async_client.douyin_xingtu``

Endpoints: 22
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncDouyinXingtu", "DouyinXingtu"]


class DouyinXingtu(SyncResource):
    """Sync ``Douyin-Xingtu-API`` resource (22 endpoints)."""

    def get_sign_image(
        self,
        *,
        uri: str,
        durationTS: int | None = None,
        format: str | None = None,
    ) -> Any:
        """获取加密图片解析/Get Sign Image

        ``GET /api/v1/douyin/xingtu/get_sign_image``
        """
        params = _drop_none({
            "uri": uri,
            "durationTS": durationTS,
            "format": format,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/get_sign_image", params=params)

    def get_xingtu_kolid_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid", params=params)

    def get_xingtu_kolid_by_sec_user_id(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id", params=params)

    def get_xingtu_kolid_by_unique_id(
        self,
        *,
        unique_id: str,
    ) -> Any:
        """根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id``
        """
        params = _drop_none({
            "unique_id": unique_id,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id", params=params)

    def kol_base_info_v1(
        self,
        *,
        kolId: str,
        platformChannel: str,
    ) -> Any:
        """获取kol基本信息V1/Get kol Base Info V1

        ``GET /api/v1/douyin/xingtu/kol_base_info_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "platformChannel": platformChannel,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_base_info_v1", params=params)

    def kol_audience_portrait_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol观众画像V1/Get kol Audience Portrait V1

        ``GET /api/v1/douyin/xingtu/kol_audience_portrait_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_audience_portrait_v1", params=params)

    def kol_fans_portrait_v1(
        self,
        *,
        kolId: str,
        fansType: str | None = None,
    ) -> Any:
        """获取kol粉丝画像V1/Get kol Fans Portrait V1

        ``GET /api/v1/douyin/xingtu/kol_fans_portrait_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "fansType": fansType,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_fans_portrait_v1", params=params)

    def kol_service_price_v1(
        self,
        *,
        kolId: str,
        platformChannel: str,
    ) -> Any:
        """获取kol服务报价V1/Get kol Service Price V1

        ``GET /api/v1/douyin/xingtu/kol_service_price_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "platformChannel": platformChannel,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_service_price_v1", params=params)

    def kol_data_overview_v1(
        self,
        *,
        kolId: str,
        _type: str,
        _range: str,
        flowType: int,
        onlyAssign: bool | None = None,
    ) -> Any:
        """获取kol数据概览V1/Get kol Data Overview V1

        ``GET /api/v1/douyin/xingtu/kol_data_overview_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "_type": _type,
            "_range": _range,
            "flowType": flowType,
            "onlyAssign": onlyAssign,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_data_overview_v1", params=params)

    def search_kol_v1(
        self,
        *,
        keyword: str,
        platformSource: str,
        page: int,
    ) -> Any:
        """关键词搜索kol V1/Search Kol V1

        ``GET /api/v1/douyin/xingtu/search_kol_v1``
        """
        params = _drop_none({
            "keyword": keyword,
            "platformSource": platformSource,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/search_kol_v1", params=params)

    def search_kol_v2(
        self,
        *,
        keyword: str,
        followerRange: str | None = None,
        contentTag: str | None = None,
    ) -> Any:
        """高级搜索kol V2/Search Kol Advanced V2

        ``GET /api/v1/douyin/xingtu/search_kol_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "followerRange": followerRange,
            "contentTag": contentTag,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/search_kol_v2", params=params)

    def kol_conversion_ability_analysis_v1(
        self,
        *,
        kolId: str,
        _range: str,
    ) -> Any:
        """获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1

        ``GET /api/v1/douyin/xingtu/kol_conversion_ability_analysis_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "_range": _range,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_conversion_ability_analysis_v1", params=params)

    def kol_video_performance_v1(
        self,
        *,
        kolId: str,
        onlyAssign: bool,
    ) -> Any:
        """获取kol视频表现V1/Get kol Video Performance V1

        ``GET /api/v1/douyin/xingtu/kol_video_performance_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "onlyAssign": onlyAssign,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_video_performance_v1", params=params)

    def kol_xingtu_index_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol星图指数V1/Get kol Xingtu Index V1

        ``GET /api/v1/douyin/xingtu/kol_xingtu_index_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_xingtu_index_v1", params=params)

    def kol_convert_video_display_v1(
        self,
        *,
        kolId: str,
        detailType: str,
        page: int,
    ) -> Any:
        """获取kol转化视频展示V1/Get kol Convert Video Display V1

        ``GET /api/v1/douyin/xingtu/kol_convert_video_display_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "detailType": detailType,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_convert_video_display_v1", params=params)

    def kol_link_struct_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol连接用户V1/Get kol Link Struct V1

        ``GET /api/v1/douyin/xingtu/kol_link_struct_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_link_struct_v1", params=params)

    def kol_touch_distribution_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol连接用户来源V1/Get kol Touch Distribution V1

        ``GET /api/v1/douyin/xingtu/kol_touch_distribution_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_touch_distribution_v1", params=params)

    def kol_cp_info_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol性价比能力分析V1/Get kol Cp Info V1

        ``GET /api/v1/douyin/xingtu/kol_cp_info_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_cp_info_v1", params=params)

    def kol_rec_videos_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol内容表现V1/Get kol Rec Videos V1

        ``GET /api/v1/douyin/xingtu/kol_rec_videos_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_rec_videos_v1", params=params)

    def kol_daily_fans_v1(
        self,
        *,
        kolId: str,
        startDate: str,
        endDate: str,
    ) -> Any:
        """获取kol粉丝趋势V1/Get kol Daily Fans V1

        ``GET /api/v1/douyin/xingtu/kol_daily_fans_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "startDate": startDate,
            "endDate": endDate,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/kol_daily_fans_v1", params=params)

    def author_hot_comment_tokens_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol热词分析评论V1/Get Author Hot Comment Tokens V1

        ``GET /api/v1/douyin/xingtu/author_hot_comment_tokens_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/author_hot_comment_tokens_v1", params=params)

    def author_content_hot_comment_keywords_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1

        ``GET /api/v1/douyin/xingtu/author_content_hot_comment_keywords_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return self._client._request("GET", "/api/v1/douyin/xingtu/author_content_hot_comment_keywords_v1", params=params)


class AsyncDouyinXingtu(AsyncResource):
    """Async ``Douyin-Xingtu-API`` resource (22 endpoints)."""

    async def get_sign_image(
        self,
        *,
        uri: str,
        durationTS: int | None = None,
        format: str | None = None,
    ) -> Any:
        """获取加密图片解析/Get Sign Image

        ``GET /api/v1/douyin/xingtu/get_sign_image``
        """
        params = _drop_none({
            "uri": uri,
            "durationTS": durationTS,
            "format": format,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/get_sign_image", params=params)

    async def get_xingtu_kolid_by_uid(
        self,
        *,
        uid: str,
    ) -> Any:
        """根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_uid``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_uid", params=params)

    async def get_xingtu_kolid_by_sec_user_id(
        self,
        *,
        sec_user_id: str,
    ) -> Any:
        """根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id", params=params)

    async def get_xingtu_kolid_by_unique_id(
        self,
        *,
        unique_id: str,
    ) -> Any:
        """根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id

        ``GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id``
        """
        params = _drop_none({
            "unique_id": unique_id,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id", params=params)

    async def kol_base_info_v1(
        self,
        *,
        kolId: str,
        platformChannel: str,
    ) -> Any:
        """获取kol基本信息V1/Get kol Base Info V1

        ``GET /api/v1/douyin/xingtu/kol_base_info_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "platformChannel": platformChannel,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_base_info_v1", params=params)

    async def kol_audience_portrait_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol观众画像V1/Get kol Audience Portrait V1

        ``GET /api/v1/douyin/xingtu/kol_audience_portrait_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_audience_portrait_v1", params=params)

    async def kol_fans_portrait_v1(
        self,
        *,
        kolId: str,
        fansType: str | None = None,
    ) -> Any:
        """获取kol粉丝画像V1/Get kol Fans Portrait V1

        ``GET /api/v1/douyin/xingtu/kol_fans_portrait_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "fansType": fansType,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_fans_portrait_v1", params=params)

    async def kol_service_price_v1(
        self,
        *,
        kolId: str,
        platformChannel: str,
    ) -> Any:
        """获取kol服务报价V1/Get kol Service Price V1

        ``GET /api/v1/douyin/xingtu/kol_service_price_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "platformChannel": platformChannel,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_service_price_v1", params=params)

    async def kol_data_overview_v1(
        self,
        *,
        kolId: str,
        _type: str,
        _range: str,
        flowType: int,
        onlyAssign: bool | None = None,
    ) -> Any:
        """获取kol数据概览V1/Get kol Data Overview V1

        ``GET /api/v1/douyin/xingtu/kol_data_overview_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "_type": _type,
            "_range": _range,
            "flowType": flowType,
            "onlyAssign": onlyAssign,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_data_overview_v1", params=params)

    async def search_kol_v1(
        self,
        *,
        keyword: str,
        platformSource: str,
        page: int,
    ) -> Any:
        """关键词搜索kol V1/Search Kol V1

        ``GET /api/v1/douyin/xingtu/search_kol_v1``
        """
        params = _drop_none({
            "keyword": keyword,
            "platformSource": platformSource,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/search_kol_v1", params=params)

    async def search_kol_v2(
        self,
        *,
        keyword: str,
        followerRange: str | None = None,
        contentTag: str | None = None,
    ) -> Any:
        """高级搜索kol V2/Search Kol Advanced V2

        ``GET /api/v1/douyin/xingtu/search_kol_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "followerRange": followerRange,
            "contentTag": contentTag,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/search_kol_v2", params=params)

    async def kol_conversion_ability_analysis_v1(
        self,
        *,
        kolId: str,
        _range: str,
    ) -> Any:
        """获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1

        ``GET /api/v1/douyin/xingtu/kol_conversion_ability_analysis_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "_range": _range,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_conversion_ability_analysis_v1", params=params)

    async def kol_video_performance_v1(
        self,
        *,
        kolId: str,
        onlyAssign: bool,
    ) -> Any:
        """获取kol视频表现V1/Get kol Video Performance V1

        ``GET /api/v1/douyin/xingtu/kol_video_performance_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "onlyAssign": onlyAssign,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_video_performance_v1", params=params)

    async def kol_xingtu_index_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol星图指数V1/Get kol Xingtu Index V1

        ``GET /api/v1/douyin/xingtu/kol_xingtu_index_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_xingtu_index_v1", params=params)

    async def kol_convert_video_display_v1(
        self,
        *,
        kolId: str,
        detailType: str,
        page: int,
    ) -> Any:
        """获取kol转化视频展示V1/Get kol Convert Video Display V1

        ``GET /api/v1/douyin/xingtu/kol_convert_video_display_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "detailType": detailType,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_convert_video_display_v1", params=params)

    async def kol_link_struct_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol连接用户V1/Get kol Link Struct V1

        ``GET /api/v1/douyin/xingtu/kol_link_struct_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_link_struct_v1", params=params)

    async def kol_touch_distribution_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol连接用户来源V1/Get kol Touch Distribution V1

        ``GET /api/v1/douyin/xingtu/kol_touch_distribution_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_touch_distribution_v1", params=params)

    async def kol_cp_info_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol性价比能力分析V1/Get kol Cp Info V1

        ``GET /api/v1/douyin/xingtu/kol_cp_info_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_cp_info_v1", params=params)

    async def kol_rec_videos_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol内容表现V1/Get kol Rec Videos V1

        ``GET /api/v1/douyin/xingtu/kol_rec_videos_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_rec_videos_v1", params=params)

    async def kol_daily_fans_v1(
        self,
        *,
        kolId: str,
        startDate: str,
        endDate: str,
    ) -> Any:
        """获取kol粉丝趋势V1/Get kol Daily Fans V1

        ``GET /api/v1/douyin/xingtu/kol_daily_fans_v1``
        """
        params = _drop_none({
            "kolId": kolId,
            "startDate": startDate,
            "endDate": endDate,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/kol_daily_fans_v1", params=params)

    async def author_hot_comment_tokens_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol热词分析评论V1/Get Author Hot Comment Tokens V1

        ``GET /api/v1/douyin/xingtu/author_hot_comment_tokens_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/author_hot_comment_tokens_v1", params=params)

    async def author_content_hot_comment_keywords_v1(
        self,
        *,
        kolId: str,
    ) -> Any:
        """获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1

        ``GET /api/v1/douyin/xingtu/author_content_hot_comment_keywords_v1``
        """
        params = _drop_none({
            "kolId": kolId,
        })
        return await self._client._request("GET", "/api/v1/douyin/xingtu/author_content_hot_comment_keywords_v1", params=params)
