# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Health-Check resource.

OpenAPI tag: ``Health-Check``
SDK attribute: ``client.health_check`` / ``async_client.health_check``

Endpoints: 2
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncHealthCheck", "HealthCheck"]


class HealthCheck(SyncResource):
    """Sync ``Health-Check`` resource (2 endpoints)."""

    def check(
        self,
    ) -> Any:
        """检查服务器是否正确响应请求 / Check if the server responds to requests correctly

        ``GET /api/v1/health/check``
        """
        return self._client._request("GET", "/api/v1/health/check")

    def deep(
        self,
    ) -> Any:
        """深度健康检查（实测依赖与资源）/ Deep health check (probes dependencies and resources)

        ``GET /api/v1/health/deep``
        """
        return self._client._request("GET", "/api/v1/health/deep")


class AsyncHealthCheck(AsyncResource):
    """Async ``Health-Check`` resource (2 endpoints)."""

    async def check(
        self,
    ) -> Any:
        """检查服务器是否正确响应请求 / Check if the server responds to requests correctly

        ``GET /api/v1/health/check``
        """
        return await self._client._request("GET", "/api/v1/health/check")

    async def deep(
        self,
    ) -> Any:
        """深度健康检查（实测依赖与资源）/ Deep health check (probes dependencies and resources)

        ``GET /api/v1/health/deep``
        """
        return await self._client._request("GET", "/api/v1/health/deep")
