# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""iOS-Shortcut resource.

OpenAPI tag: ``iOS-Shortcut``
SDK attribute: ``client.ios_shortcut`` / ``async_client.ios_shortcut``

Endpoints: 1
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncIosShortcut", "IosShortcut"]


class IosShortcut(SyncResource):
    """Sync ``iOS-Shortcut`` resource (1 endpoints)."""

    def shortcut(
        self,
    ) -> Any:
        """用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts

        ``GET /api/v1/ios_shortcut/shortcut``
        """
        return self._client._request("GET", "/api/v1/ios_shortcut/shortcut")


class AsyncIosShortcut(AsyncResource):
    """Async ``iOS-Shortcut`` resource (1 endpoints)."""

    async def shortcut(
        self,
    ) -> Any:
        """用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts

        ``GET /api/v1/ios_shortcut/shortcut``
        """
        return await self._client._request("GET", "/api/v1/ios_shortcut/shortcut")
