# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Kuaishou-App-API resource.

OpenAPI tag: ``Kuaishou-App-API``
SDK attribute: ``client.kuaishou_app`` / ``async_client.kuaishou_app``

Endpoints: 20
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncKuaishouApp", "KuaishouApp"]


class KuaishouApp(SyncResource):
    """Sync ``Kuaishou-App-API`` resource (20 endpoints)."""

    def fetch_one_video(
        self,
        *,
        photo_id: str,
    ) -> Any:
        """视频详情V1/Video detailsV1

        ``GET /api/v1/kuaishou/app/fetch_one_video``
        """
        params = _drop_none({
            "photo_id": photo_id,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video", params=params)

    def fetch_videos_batch(
        self,
        *,
        photo_ids: str,
    ) -> Any:
        """快手批量视频查询接口/Kuaishou batch video query API

        ``GET /api/v1/kuaishou/app/fetch_videos_batch``
        """
        params = _drop_none({
            "photo_ids": photo_ids,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_videos_batch", params=params)

    def fetch_one_video_by_url(
        self,
        *,
        share_text: str,
    ) -> Any:
        """根据链接获取单个作品数据/Fetch single video by URL

        ``GET /api/v1/kuaishou/app/fetch_one_video_by_url``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video_by_url", params=params)

    def fetch_one_video_comment(
        self,
        *,
        photo_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """获取单个作品评论数据/Get single video comment data

        ``GET /api/v1/kuaishou/app/fetch_one_video_comment``
        """
        params = _drop_none({
            "photo_id": photo_id,
            "pcursor": pcursor,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video_comment", params=params)

    def fetch_one_user_v2(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取单个用户数据V2/Get single user data V2

        ``GET /api/v1/kuaishou/app/fetch_one_user_v2``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_user_v2", params=params)

    def fetch_user_live_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户直播信息/Get user live info

        ``GET /api/v1/kuaishou/app/fetch_user_live_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_live_info", params=params)

    def fetch_user_hot_post(
        self,
        *,
        user_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """获取用户热门作品数据/Get user hot post data

        ``GET /api/v1/kuaishou/app/fetch_user_hot_post``
        """
        params = _drop_none({
            "user_id": user_id,
            "pcursor": pcursor,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_hot_post", params=params)

    def fetch_user_post_v2(
        self,
        *,
        user_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """用户视频列表V2/User video list V2

        ``GET /api/v1/kuaishou/app/fetch_user_post_v2``
        """
        params = _drop_none({
            "user_id": user_id,
            "pcursor": pcursor,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_post_v2", params=params)

    def search_comprehensive(
        self,
        *,
        keyword: str,
        pcursor: str | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        duration: str | None = None,
        search_scope: str | None = None,
    ) -> Any:
        """综合搜索/Comprehensive search

        ``GET /api/v1/kuaishou/app/search_comprehensive``
        """
        params = _drop_none({
            "keyword": keyword,
            "pcursor": pcursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "duration": duration,
            "search_scope": search_scope,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/search_comprehensive", params=params)

    def search_video_v2(
        self,
        *,
        keyword: str,
        page: str | None = None,
    ) -> Any:
        """搜索视频V2/Search video V2

        ``GET /api/v1/kuaishou/app/search_video_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/search_video_v2", params=params)

    def search_user_v2(
        self,
        *,
        keyword: str,
        page: str | None = None,
    ) -> Any:
        """搜索用户V2/Search user V2

        ``GET /api/v1/kuaishou/app/search_user_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/search_user_v2", params=params)

    def fetch_hot_board_categories(
        self,
    ) -> Any:
        """快手热榜分类/Kuaishou hot categories

        ``GET /api/v1/kuaishou/app/fetch_hot_board_categories``
        """
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_board_categories")

    def fetch_hot_board_detail(
        self,
        *,
        boardType: int | None = None,
        boardId: int | None = None,
    ) -> Any:
        """快手热榜详情/Kuaishou hot board detail

        ``GET /api/v1/kuaishou/app/fetch_hot_board_detail``
        """
        params = _drop_none({
            "boardType": boardType,
            "boardId": boardId,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_board_detail", params=params)

    def fetch_hot_search_person(
        self,
    ) -> Any:
        """快手热搜人物榜单/Kuaishou hot search person board

        ``GET /api/v1/kuaishou/app/fetch_hot_search_person``
        """
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_search_person")

    def fetch_live_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手直播榜单/Kuaishou live top list

        ``GET /api/v1/kuaishou/app/fetch_live_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_live_top_list", params=params)

    def fetch_shopping_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手购物榜单/Kuaishou shopping top list

        ``GET /api/v1/kuaishou/app/fetch_shopping_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_shopping_top_list", params=params)

    def fetch_brand_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手品牌榜单/Kuaishou brand top list

        ``GET /api/v1/kuaishou/app/fetch_brand_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_brand_top_list", params=params)

    def generate_kuaishou_share_link(
        self,
        *,
        shareObjectId: str,
    ) -> Any:
        """生成快手分享链接/Generate Kuaishou share link

        ``GET /api/v1/kuaishou/app/generate_kuaishou_share_link``
        """
        params = _drop_none({
            "shareObjectId": shareObjectId,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/generate_kuaishou_share_link", params=params)

    def fetch_magic_face_usage(
        self,
        *,
        magic_face_id: str,
    ) -> Any:
        """获取魔法表情使用人数/Fetch magic face usage count

        ``GET /api/v1/kuaishou/app/fetch_magic_face_usage``
        """
        params = _drop_none({
            "magic_face_id": magic_face_id,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_magic_face_usage", params=params)

    def fetch_magic_face_hot(
        self,
        *,
        magic_face_id: str,
        pcursor: str | None = None,
        count: int | None = None,
    ) -> Any:
        """获取魔法表情热门视频/Fetch magic face hot videos

        ``GET /api/v1/kuaishou/app/fetch_magic_face_hot``
        """
        params = _drop_none({
            "magic_face_id": magic_face_id,
            "pcursor": pcursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/kuaishou/app/fetch_magic_face_hot", params=params)


class AsyncKuaishouApp(AsyncResource):
    """Async ``Kuaishou-App-API`` resource (20 endpoints)."""

    async def fetch_one_video(
        self,
        *,
        photo_id: str,
    ) -> Any:
        """视频详情V1/Video detailsV1

        ``GET /api/v1/kuaishou/app/fetch_one_video``
        """
        params = _drop_none({
            "photo_id": photo_id,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video", params=params)

    async def fetch_videos_batch(
        self,
        *,
        photo_ids: str,
    ) -> Any:
        """快手批量视频查询接口/Kuaishou batch video query API

        ``GET /api/v1/kuaishou/app/fetch_videos_batch``
        """
        params = _drop_none({
            "photo_ids": photo_ids,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_videos_batch", params=params)

    async def fetch_one_video_by_url(
        self,
        *,
        share_text: str,
    ) -> Any:
        """根据链接获取单个作品数据/Fetch single video by URL

        ``GET /api/v1/kuaishou/app/fetch_one_video_by_url``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video_by_url", params=params)

    async def fetch_one_video_comment(
        self,
        *,
        photo_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """获取单个作品评论数据/Get single video comment data

        ``GET /api/v1/kuaishou/app/fetch_one_video_comment``
        """
        params = _drop_none({
            "photo_id": photo_id,
            "pcursor": pcursor,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_video_comment", params=params)

    async def fetch_one_user_v2(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取单个用户数据V2/Get single user data V2

        ``GET /api/v1/kuaishou/app/fetch_one_user_v2``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_one_user_v2", params=params)

    async def fetch_user_live_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户直播信息/Get user live info

        ``GET /api/v1/kuaishou/app/fetch_user_live_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_live_info", params=params)

    async def fetch_user_hot_post(
        self,
        *,
        user_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """获取用户热门作品数据/Get user hot post data

        ``GET /api/v1/kuaishou/app/fetch_user_hot_post``
        """
        params = _drop_none({
            "user_id": user_id,
            "pcursor": pcursor,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_hot_post", params=params)

    async def fetch_user_post_v2(
        self,
        *,
        user_id: str,
        pcursor: str | None = None,
    ) -> Any:
        """用户视频列表V2/User video list V2

        ``GET /api/v1/kuaishou/app/fetch_user_post_v2``
        """
        params = _drop_none({
            "user_id": user_id,
            "pcursor": pcursor,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_user_post_v2", params=params)

    async def search_comprehensive(
        self,
        *,
        keyword: str,
        pcursor: str | None = None,
        sort_type: str | None = None,
        publish_time: str | None = None,
        duration: str | None = None,
        search_scope: str | None = None,
    ) -> Any:
        """综合搜索/Comprehensive search

        ``GET /api/v1/kuaishou/app/search_comprehensive``
        """
        params = _drop_none({
            "keyword": keyword,
            "pcursor": pcursor,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "duration": duration,
            "search_scope": search_scope,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/search_comprehensive", params=params)

    async def search_video_v2(
        self,
        *,
        keyword: str,
        page: str | None = None,
    ) -> Any:
        """搜索视频V2/Search video V2

        ``GET /api/v1/kuaishou/app/search_video_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/search_video_v2", params=params)

    async def search_user_v2(
        self,
        *,
        keyword: str,
        page: str | None = None,
    ) -> Any:
        """搜索用户V2/Search user V2

        ``GET /api/v1/kuaishou/app/search_user_v2``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/search_user_v2", params=params)

    async def fetch_hot_board_categories(
        self,
    ) -> Any:
        """快手热榜分类/Kuaishou hot categories

        ``GET /api/v1/kuaishou/app/fetch_hot_board_categories``
        """
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_board_categories")

    async def fetch_hot_board_detail(
        self,
        *,
        boardType: int | None = None,
        boardId: int | None = None,
    ) -> Any:
        """快手热榜详情/Kuaishou hot board detail

        ``GET /api/v1/kuaishou/app/fetch_hot_board_detail``
        """
        params = _drop_none({
            "boardType": boardType,
            "boardId": boardId,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_board_detail", params=params)

    async def fetch_hot_search_person(
        self,
    ) -> Any:
        """快手热搜人物榜单/Kuaishou hot search person board

        ``GET /api/v1/kuaishou/app/fetch_hot_search_person``
        """
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_hot_search_person")

    async def fetch_live_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手直播榜单/Kuaishou live top list

        ``GET /api/v1/kuaishou/app/fetch_live_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_live_top_list", params=params)

    async def fetch_shopping_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手购物榜单/Kuaishou shopping top list

        ``GET /api/v1/kuaishou/app/fetch_shopping_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_shopping_top_list", params=params)

    async def fetch_brand_top_list(
        self,
        *,
        subTabId: int | None = None,
        subTabName: str | None = None,
    ) -> Any:
        """快手品牌榜单/Kuaishou brand top list

        ``GET /api/v1/kuaishou/app/fetch_brand_top_list``
        """
        params = _drop_none({
            "subTabId": subTabId,
            "subTabName": subTabName,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_brand_top_list", params=params)

    async def generate_kuaishou_share_link(
        self,
        *,
        shareObjectId: str,
    ) -> Any:
        """生成快手分享链接/Generate Kuaishou share link

        ``GET /api/v1/kuaishou/app/generate_kuaishou_share_link``
        """
        params = _drop_none({
            "shareObjectId": shareObjectId,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/generate_kuaishou_share_link", params=params)

    async def fetch_magic_face_usage(
        self,
        *,
        magic_face_id: str,
    ) -> Any:
        """获取魔法表情使用人数/Fetch magic face usage count

        ``GET /api/v1/kuaishou/app/fetch_magic_face_usage``
        """
        params = _drop_none({
            "magic_face_id": magic_face_id,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_magic_face_usage", params=params)

    async def fetch_magic_face_hot(
        self,
        *,
        magic_face_id: str,
        pcursor: str | None = None,
        count: int | None = None,
    ) -> Any:
        """获取魔法表情热门视频/Fetch magic face hot videos

        ``GET /api/v1/kuaishou/app/fetch_magic_face_hot``
        """
        params = _drop_none({
            "magic_face_id": magic_face_id,
            "pcursor": pcursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/kuaishou/app/fetch_magic_face_hot", params=params)
