# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Lemon8-App-API resource.

OpenAPI tag: ``Lemon8-App-API``
SDK attribute: ``client.lemon8_app`` / ``async_client.lemon8_app``

Endpoints: 16
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncLemon8App", "Lemon8App"]


class Lemon8App(SyncResource):
    """Sync ``Lemon8-App-API`` resource (16 endpoints)."""

    def fetch_user_profile(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取指定用户的信息/Get information of specified user

        ``GET /api/v1/lemon8/app/fetch_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_user_profile", params=params)

    def fetch_post_detail(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取指定作品的信息/Get information of specified post

        ``GET /api/v1/lemon8/app/fetch_post_detail``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_post_detail", params=params)

    def fetch_user_follower_list(
        self,
        *,
        user_id: str,
        cursor: str | None = None,
    ) -> Any:
        """获取指定用户的粉丝列表/Get fans list of specified user

        ``GET /api/v1/lemon8/app/fetch_user_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "cursor": cursor,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_user_follower_list", params=params)

    def fetch_user_following_list(
        self,
        *,
        user_id: str,
        cursor: str | None = None,
    ) -> Any:
        """获取指定用户的关注列表/Get following list of specified user

        ``GET /api/v1/lemon8/app/fetch_user_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "cursor": cursor,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_user_following_list", params=params)

    def fetch_post_comment_list(
        self,
        *,
        group_id: str,
        item_id: str,
        media_id: str,
        offset: str | None = None,
    ) -> Any:
        """获取指定作品的评论列表/Get comments list of specified post

        ``GET /api/v1/lemon8/app/fetch_post_comment_list``
        """
        params = _drop_none({
            "group_id": group_id,
            "item_id": item_id,
            "media_id": media_id,
            "offset": offset,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_post_comment_list", params=params)

    def fetch_discover_banners(
        self,
    ) -> Any:
        """获取发现页Banner/Get banners of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_banners``
        """
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_banners")

    def fetch_discover_tab(
        self,
    ) -> Any:
        """获取发现页主体内容/Get main content of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_tab``
        """
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_tab")

    def fetch_discover_tab_information_tabs(
        self,
    ) -> Any:
        """获取发现页的 Editor's Picks/Get Editor's Picks of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_tab_information_tabs``
        """
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_tab_information_tabs")

    def fetch_hot_search_keywords(
        self,
    ) -> Any:
        """获取热搜关键词/Get hot search keywords

        ``GET /api/v1/lemon8/app/fetch_hot_search_keywords``
        """
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_hot_search_keywords")

    def fetch_topic_info(
        self,
        *,
        forum_id: str,
    ) -> Any:
        """获取话题信息/Get topic information

        ``GET /api/v1/lemon8/app/fetch_topic_info``
        """
        params = _drop_none({
            "forum_id": forum_id,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_topic_info", params=params)

    def fetch_topic_post_list(
        self,
        *,
        category: str,
        category_parameter: str,
        hashtag_name: str,
        max_behot_time: str | None = None,
        sort_type: str | None = None,
    ) -> Any:
        """获取话题作品列表/Get topic post list

        ``GET /api/v1/lemon8/app/fetch_topic_post_list``
        """
        params = _drop_none({
            "category": category,
            "max_behot_time": max_behot_time,
            "category_parameter": category_parameter,
            "hashtag_name": hashtag_name,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_topic_post_list", params=params)

    def fetch_search(
        self,
        *,
        query: str,
        max_cursor: str | None = None,
        filter_type: str | None = None,
        order_by: str | None = None,
        search_tab: str | None = None,
    ) -> Any:
        """搜索接口/Search API

        ``GET /api/v1/lemon8/app/fetch_search``
        """
        params = _drop_none({
            "query": query,
            "max_cursor": max_cursor,
            "filter_type": filter_type,
            "order_by": order_by,
            "search_tab": search_tab,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/fetch_search", params=params)

    def get_item_id(
        self,
        *,
        share_text: str,
    ) -> Any:
        """通过分享链接获取作品ID/Get post ID through sharing link

        ``GET /api/v1/lemon8/app/get_item_id``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/get_item_id", params=params)

    def get_user_id(
        self,
        *,
        share_text: str,
    ) -> Any:
        """通过分享链接获取用户ID/Get user ID through sharing link

        ``GET /api/v1/lemon8/app/get_user_id``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return self._client._request("GET", "/api/v1/lemon8/app/get_user_id", params=params)

    def get_item_ids(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """通过分享链接批量获取作品ID/Get post IDs in batch through sharing links

        ``POST /api/v1/lemon8/app/get_item_ids``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/lemon8/app/get_item_ids", json=json_body)

    def get_user_ids(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """通过分享链接批量获取用户ID/Get user IDs in batch through sharing links

        ``POST /api/v1/lemon8/app/get_user_ids``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/lemon8/app/get_user_ids", json=json_body)


class AsyncLemon8App(AsyncResource):
    """Async ``Lemon8-App-API`` resource (16 endpoints)."""

    async def fetch_user_profile(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取指定用户的信息/Get information of specified user

        ``GET /api/v1/lemon8/app/fetch_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_user_profile", params=params)

    async def fetch_post_detail(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取指定作品的信息/Get information of specified post

        ``GET /api/v1/lemon8/app/fetch_post_detail``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_post_detail", params=params)

    async def fetch_user_follower_list(
        self,
        *,
        user_id: str,
        cursor: str | None = None,
    ) -> Any:
        """获取指定用户的粉丝列表/Get fans list of specified user

        ``GET /api/v1/lemon8/app/fetch_user_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "cursor": cursor,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_user_follower_list", params=params)

    async def fetch_user_following_list(
        self,
        *,
        user_id: str,
        cursor: str | None = None,
    ) -> Any:
        """获取指定用户的关注列表/Get following list of specified user

        ``GET /api/v1/lemon8/app/fetch_user_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "cursor": cursor,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_user_following_list", params=params)

    async def fetch_post_comment_list(
        self,
        *,
        group_id: str,
        item_id: str,
        media_id: str,
        offset: str | None = None,
    ) -> Any:
        """获取指定作品的评论列表/Get comments list of specified post

        ``GET /api/v1/lemon8/app/fetch_post_comment_list``
        """
        params = _drop_none({
            "group_id": group_id,
            "item_id": item_id,
            "media_id": media_id,
            "offset": offset,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_post_comment_list", params=params)

    async def fetch_discover_banners(
        self,
    ) -> Any:
        """获取发现页Banner/Get banners of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_banners``
        """
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_banners")

    async def fetch_discover_tab(
        self,
    ) -> Any:
        """获取发现页主体内容/Get main content of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_tab``
        """
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_tab")

    async def fetch_discover_tab_information_tabs(
        self,
    ) -> Any:
        """获取发现页的 Editor's Picks/Get Editor's Picks of discover page

        ``GET /api/v1/lemon8/app/fetch_discover_tab_information_tabs``
        """
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_discover_tab_information_tabs")

    async def fetch_hot_search_keywords(
        self,
    ) -> Any:
        """获取热搜关键词/Get hot search keywords

        ``GET /api/v1/lemon8/app/fetch_hot_search_keywords``
        """
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_hot_search_keywords")

    async def fetch_topic_info(
        self,
        *,
        forum_id: str,
    ) -> Any:
        """获取话题信息/Get topic information

        ``GET /api/v1/lemon8/app/fetch_topic_info``
        """
        params = _drop_none({
            "forum_id": forum_id,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_topic_info", params=params)

    async def fetch_topic_post_list(
        self,
        *,
        category: str,
        category_parameter: str,
        hashtag_name: str,
        max_behot_time: str | None = None,
        sort_type: str | None = None,
    ) -> Any:
        """获取话题作品列表/Get topic post list

        ``GET /api/v1/lemon8/app/fetch_topic_post_list``
        """
        params = _drop_none({
            "category": category,
            "max_behot_time": max_behot_time,
            "category_parameter": category_parameter,
            "hashtag_name": hashtag_name,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_topic_post_list", params=params)

    async def fetch_search(
        self,
        *,
        query: str,
        max_cursor: str | None = None,
        filter_type: str | None = None,
        order_by: str | None = None,
        search_tab: str | None = None,
    ) -> Any:
        """搜索接口/Search API

        ``GET /api/v1/lemon8/app/fetch_search``
        """
        params = _drop_none({
            "query": query,
            "max_cursor": max_cursor,
            "filter_type": filter_type,
            "order_by": order_by,
            "search_tab": search_tab,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/fetch_search", params=params)

    async def get_item_id(
        self,
        *,
        share_text: str,
    ) -> Any:
        """通过分享链接获取作品ID/Get post ID through sharing link

        ``GET /api/v1/lemon8/app/get_item_id``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/get_item_id", params=params)

    async def get_user_id(
        self,
        *,
        share_text: str,
    ) -> Any:
        """通过分享链接获取用户ID/Get user ID through sharing link

        ``GET /api/v1/lemon8/app/get_user_id``
        """
        params = _drop_none({
            "share_text": share_text,
        })
        return await self._client._request("GET", "/api/v1/lemon8/app/get_user_id", params=params)

    async def get_item_ids(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """通过分享链接批量获取作品ID/Get post IDs in batch through sharing links

        ``POST /api/v1/lemon8/app/get_item_ids``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/lemon8/app/get_item_ids", json=json_body)

    async def get_user_ids(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """通过分享链接批量获取用户ID/Get user IDs in batch through sharing links

        ``POST /api/v1/lemon8/app/get_user_ids``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/lemon8/app/get_user_ids", json=json_body)
