# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""LinkedIn-Web-API resource.

OpenAPI tag: ``LinkedIn-Web-API``
SDK attribute: ``client.linkedin_web`` / ``async_client.linkedin_web``

Endpoints: 25
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncLinkedinWeb", "LinkedinWeb"]


class LinkedinWeb(SyncResource):
    """Sync ``LinkedIn-Web-API`` resource (25 endpoints)."""

    def get_user_profile(
        self,
        *,
        username: str,
        include_follower_and_connection: Any | None = None,
        include_experiences: Any | None = None,
        include_skills: Any | None = None,
        include_certifications: Any | None = None,
        include_publications: Any | None = None,
        include_educations: Any | None = None,
        include_volunteers: Any | None = None,
        include_honors: Any | None = None,
        include_interests: Any | None = None,
        include_bio: Any | None = None,
    ) -> Any:
        """获取用户资料/Get user profile

        ``GET /api/v1/linkedin/web/get_user_profile``
        """
        params = _drop_none({
            "username": username,
            "include_follower_and_connection": include_follower_and_connection,
            "include_experiences": include_experiences,
            "include_skills": include_skills,
            "include_certifications": include_certifications,
            "include_publications": include_publications,
            "include_educations": include_educations,
            "include_volunteers": include_volunteers,
            "include_honors": include_honors,
            "include_interests": include_interests,
            "include_bio": include_bio,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_profile", params=params)

    def get_user_posts(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户帖子/Get user posts

        ``GET /api/v1/linkedin/web/get_user_posts``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_posts", params=params)

    def get_user_comments(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户评论/Get user comments

        ``GET /api/v1/linkedin/web/get_user_comments``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_comments", params=params)

    def get_user_contact(
        self,
        *,
        username: str,
    ) -> Any:
        """获取用户联系信息/Get user contact information

        ``GET /api/v1/linkedin/web/get_user_contact``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_contact", params=params)

    def get_user_recommendations(
        self,
        *,
        urn: str,
        page: Any | None = None,
        type: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户推荐信/Get user recommendations

        ``GET /api/v1/linkedin/web/get_user_recommendations``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "type": type,
            "pagination_token": pagination_token,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_recommendations", params=params)

    def get_user_videos(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户视频/Get user videos

        ``GET /api/v1/linkedin/web/get_user_videos``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_videos", params=params)

    def get_user_images(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户图片/Get user images

        ``GET /api/v1/linkedin/web/get_user_images``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_images", params=params)

    def get_company_profile(
        self,
        *,
        company: Any | None = None,
        company_id: Any | None = None,
    ) -> Any:
        """获取公司资料/Get company profile

        ``GET /api/v1/linkedin/web/get_company_profile``
        """
        params = _drop_none({
            "company": company,
            "company_id": company_id,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_company_profile", params=params)

    def get_company_people(
        self,
        *,
        company_id: str,
        page: Any | None = None,
    ) -> Any:
        """获取公司员工/Get company people

        ``GET /api/v1/linkedin/web/get_company_people``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_company_people", params=params)

    def get_company_posts(
        self,
        *,
        company_id: str,
        page: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """获取公司帖子/Get company posts

        ``GET /api/v1/linkedin/web/get_company_posts``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
            "sort_by": sort_by,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_company_posts", params=params)

    def get_company_jobs(
        self,
        *,
        company_id: str,
        page: Any | None = None,
        sort_by: Any | None = None,
        date_posted: Any | None = None,
        experience_level: Any | None = None,
        remote: Any | None = None,
        job_type: Any | None = None,
        easy_apply: Any | None = None,
        under_10_applicants: Any | None = None,
        fair_chance_employer: Any | None = None,
    ) -> Any:
        """获取公司职位/Get company jobs

        ``GET /api/v1/linkedin/web/get_company_jobs``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
            "sort_by": sort_by,
            "date_posted": date_posted,
            "experience_level": experience_level,
            "remote": remote,
            "job_type": job_type,
            "easy_apply": easy_apply,
            "under_10_applicants": under_10_applicants,
            "fair_chance_employer": fair_chance_employer,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_company_jobs", params=params)

    def get_company_job_count(
        self,
        *,
        company_id: str,
    ) -> Any:
        """获取公司职位数量/Get company job count

        ``GET /api/v1/linkedin/web/get_company_job_count``
        """
        params = _drop_none({
            "company_id": company_id,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_company_job_count", params=params)

    def get_user_about(
        self,
        *,
        urn: str,
    ) -> Any:
        """获取用户简介/Get user about

        ``GET /api/v1/linkedin/web/get_user_about``
        """
        params = _drop_none({
            "urn": urn,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_about", params=params)

    def get_user_follower_and_connection(
        self,
        *,
        username: str,
    ) -> Any:
        """获取用户粉丝和连接数/Get user follower and connection

        ``GET /api/v1/linkedin/web/get_user_follower_and_connection``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_follower_and_connection", params=params)

    def get_user_experience(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户工作经历/Get user experience

        ``GET /api/v1/linkedin/web/get_user_experience``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_experience", params=params)

    def get_user_skills(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户技能/Get user skills

        ``GET /api/v1/linkedin/web/get_user_skills``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_skills", params=params)

    def get_user_educations(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户教育背景/Get user educations

        ``GET /api/v1/linkedin/web/get_user_educations``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_educations", params=params)

    def get_user_publications(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户出版物/Get user publications

        ``GET /api/v1/linkedin/web/get_user_publications``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_publications", params=params)

    def get_user_certifications(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户认证/Get user certifications

        ``GET /api/v1/linkedin/web/get_user_certifications``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_certifications", params=params)

    def get_user_honors(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户荣誉奖项/Get user honors

        ``GET /api/v1/linkedin/web/get_user_honors``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_honors", params=params)

    def get_user_interests_groups(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户感兴趣的群组/Get user interests groups

        ``GET /api/v1/linkedin/web/get_user_interests_groups``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_interests_groups", params=params)

    def get_user_interests_companies(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户感兴趣的公司/Get user interests companies

        ``GET /api/v1/linkedin/web/get_user_interests_companies``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_user_interests_companies", params=params)

    def get_job_detail(
        self,
        *,
        job_id: str,
        include_skills: Any | None = None,
    ) -> Any:
        """获取职位详情/Get job detail

        ``GET /api/v1/linkedin/web/get_job_detail``
        """
        params = _drop_none({
            "job_id": job_id,
            "include_skills": include_skills,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/get_job_detail", params=params)

    def search_jobs(
        self,
        *,
        keyword: str,
        page: Any | None = None,
        sort_by: Any | None = None,
        date_posted: Any | None = None,
        geocode: Any | None = None,
        company: Any | None = None,
        experience_level: Any | None = None,
        remote: Any | None = None,
        job_type: Any | None = None,
        easy_apply: Any | None = None,
        has_verifications: Any | None = None,
        under_10_applicants: Any | None = None,
        fair_chance_employer: Any | None = None,
    ) -> Any:
        """搜索职位/Search jobs

        ``GET /api/v1/linkedin/web/search_jobs``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "sort_by": sort_by,
            "date_posted": date_posted,
            "geocode": geocode,
            "company": company,
            "experience_level": experience_level,
            "remote": remote,
            "job_type": job_type,
            "easy_apply": easy_apply,
            "has_verifications": has_verifications,
            "under_10_applicants": under_10_applicants,
            "fair_chance_employer": fair_chance_employer,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/search_jobs", params=params)

    def search_people(
        self,
        *,
        name: Any | None = None,
        first_name: Any | None = None,
        last_name: Any | None = None,
        title: Any | None = None,
        company: Any | None = None,
        school: Any | None = None,
        page: Any | None = None,
        geocode_location: Any | None = None,
        current_company: Any | None = None,
        profile_language: Any | None = None,
        industry: Any | None = None,
        service_category: Any | None = None,
    ) -> Any:
        """搜索用户/Search people

        ``GET /api/v1/linkedin/web/search_people``
        """
        params = _drop_none({
            "name": name,
            "first_name": first_name,
            "last_name": last_name,
            "title": title,
            "company": company,
            "school": school,
            "page": page,
            "geocode_location": geocode_location,
            "current_company": current_company,
            "profile_language": profile_language,
            "industry": industry,
            "service_category": service_category,
        })
        return self._client._request("GET", "/api/v1/linkedin/web/search_people", params=params)


class AsyncLinkedinWeb(AsyncResource):
    """Async ``LinkedIn-Web-API`` resource (25 endpoints)."""

    async def get_user_profile(
        self,
        *,
        username: str,
        include_follower_and_connection: Any | None = None,
        include_experiences: Any | None = None,
        include_skills: Any | None = None,
        include_certifications: Any | None = None,
        include_publications: Any | None = None,
        include_educations: Any | None = None,
        include_volunteers: Any | None = None,
        include_honors: Any | None = None,
        include_interests: Any | None = None,
        include_bio: Any | None = None,
    ) -> Any:
        """获取用户资料/Get user profile

        ``GET /api/v1/linkedin/web/get_user_profile``
        """
        params = _drop_none({
            "username": username,
            "include_follower_and_connection": include_follower_and_connection,
            "include_experiences": include_experiences,
            "include_skills": include_skills,
            "include_certifications": include_certifications,
            "include_publications": include_publications,
            "include_educations": include_educations,
            "include_volunteers": include_volunteers,
            "include_honors": include_honors,
            "include_interests": include_interests,
            "include_bio": include_bio,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_profile", params=params)

    async def get_user_posts(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户帖子/Get user posts

        ``GET /api/v1/linkedin/web/get_user_posts``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_posts", params=params)

    async def get_user_comments(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户评论/Get user comments

        ``GET /api/v1/linkedin/web/get_user_comments``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_comments", params=params)

    async def get_user_contact(
        self,
        *,
        username: str,
    ) -> Any:
        """获取用户联系信息/Get user contact information

        ``GET /api/v1/linkedin/web/get_user_contact``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_contact", params=params)

    async def get_user_recommendations(
        self,
        *,
        urn: str,
        page: Any | None = None,
        type: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户推荐信/Get user recommendations

        ``GET /api/v1/linkedin/web/get_user_recommendations``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "type": type,
            "pagination_token": pagination_token,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_recommendations", params=params)

    async def get_user_videos(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户视频/Get user videos

        ``GET /api/v1/linkedin/web/get_user_videos``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_videos", params=params)

    async def get_user_images(
        self,
        *,
        urn: str,
        page: Any | None = None,
        pagination_token: Any | None = None,
    ) -> Any:
        """获取用户图片/Get user images

        ``GET /api/v1/linkedin/web/get_user_images``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
            "pagination_token": pagination_token,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_images", params=params)

    async def get_company_profile(
        self,
        *,
        company: Any | None = None,
        company_id: Any | None = None,
    ) -> Any:
        """获取公司资料/Get company profile

        ``GET /api/v1/linkedin/web/get_company_profile``
        """
        params = _drop_none({
            "company": company,
            "company_id": company_id,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_company_profile", params=params)

    async def get_company_people(
        self,
        *,
        company_id: str,
        page: Any | None = None,
    ) -> Any:
        """获取公司员工/Get company people

        ``GET /api/v1/linkedin/web/get_company_people``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_company_people", params=params)

    async def get_company_posts(
        self,
        *,
        company_id: str,
        page: Any | None = None,
        sort_by: Any | None = None,
    ) -> Any:
        """获取公司帖子/Get company posts

        ``GET /api/v1/linkedin/web/get_company_posts``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
            "sort_by": sort_by,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_company_posts", params=params)

    async def get_company_jobs(
        self,
        *,
        company_id: str,
        page: Any | None = None,
        sort_by: Any | None = None,
        date_posted: Any | None = None,
        experience_level: Any | None = None,
        remote: Any | None = None,
        job_type: Any | None = None,
        easy_apply: Any | None = None,
        under_10_applicants: Any | None = None,
        fair_chance_employer: Any | None = None,
    ) -> Any:
        """获取公司职位/Get company jobs

        ``GET /api/v1/linkedin/web/get_company_jobs``
        """
        params = _drop_none({
            "company_id": company_id,
            "page": page,
            "sort_by": sort_by,
            "date_posted": date_posted,
            "experience_level": experience_level,
            "remote": remote,
            "job_type": job_type,
            "easy_apply": easy_apply,
            "under_10_applicants": under_10_applicants,
            "fair_chance_employer": fair_chance_employer,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_company_jobs", params=params)

    async def get_company_job_count(
        self,
        *,
        company_id: str,
    ) -> Any:
        """获取公司职位数量/Get company job count

        ``GET /api/v1/linkedin/web/get_company_job_count``
        """
        params = _drop_none({
            "company_id": company_id,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_company_job_count", params=params)

    async def get_user_about(
        self,
        *,
        urn: str,
    ) -> Any:
        """获取用户简介/Get user about

        ``GET /api/v1/linkedin/web/get_user_about``
        """
        params = _drop_none({
            "urn": urn,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_about", params=params)

    async def get_user_follower_and_connection(
        self,
        *,
        username: str,
    ) -> Any:
        """获取用户粉丝和连接数/Get user follower and connection

        ``GET /api/v1/linkedin/web/get_user_follower_and_connection``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_follower_and_connection", params=params)

    async def get_user_experience(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户工作经历/Get user experience

        ``GET /api/v1/linkedin/web/get_user_experience``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_experience", params=params)

    async def get_user_skills(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户技能/Get user skills

        ``GET /api/v1/linkedin/web/get_user_skills``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_skills", params=params)

    async def get_user_educations(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户教育背景/Get user educations

        ``GET /api/v1/linkedin/web/get_user_educations``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_educations", params=params)

    async def get_user_publications(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户出版物/Get user publications

        ``GET /api/v1/linkedin/web/get_user_publications``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_publications", params=params)

    async def get_user_certifications(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户认证/Get user certifications

        ``GET /api/v1/linkedin/web/get_user_certifications``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_certifications", params=params)

    async def get_user_honors(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户荣誉奖项/Get user honors

        ``GET /api/v1/linkedin/web/get_user_honors``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_honors", params=params)

    async def get_user_interests_groups(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户感兴趣的群组/Get user interests groups

        ``GET /api/v1/linkedin/web/get_user_interests_groups``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_interests_groups", params=params)

    async def get_user_interests_companies(
        self,
        *,
        urn: str,
        page: Any | None = None,
    ) -> Any:
        """获取用户感兴趣的公司/Get user interests companies

        ``GET /api/v1/linkedin/web/get_user_interests_companies``
        """
        params = _drop_none({
            "urn": urn,
            "page": page,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_user_interests_companies", params=params)

    async def get_job_detail(
        self,
        *,
        job_id: str,
        include_skills: Any | None = None,
    ) -> Any:
        """获取职位详情/Get job detail

        ``GET /api/v1/linkedin/web/get_job_detail``
        """
        params = _drop_none({
            "job_id": job_id,
            "include_skills": include_skills,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/get_job_detail", params=params)

    async def search_jobs(
        self,
        *,
        keyword: str,
        page: Any | None = None,
        sort_by: Any | None = None,
        date_posted: Any | None = None,
        geocode: Any | None = None,
        company: Any | None = None,
        experience_level: Any | None = None,
        remote: Any | None = None,
        job_type: Any | None = None,
        easy_apply: Any | None = None,
        has_verifications: Any | None = None,
        under_10_applicants: Any | None = None,
        fair_chance_employer: Any | None = None,
    ) -> Any:
        """搜索职位/Search jobs

        ``GET /api/v1/linkedin/web/search_jobs``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "sort_by": sort_by,
            "date_posted": date_posted,
            "geocode": geocode,
            "company": company,
            "experience_level": experience_level,
            "remote": remote,
            "job_type": job_type,
            "easy_apply": easy_apply,
            "has_verifications": has_verifications,
            "under_10_applicants": under_10_applicants,
            "fair_chance_employer": fair_chance_employer,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/search_jobs", params=params)

    async def search_people(
        self,
        *,
        name: Any | None = None,
        first_name: Any | None = None,
        last_name: Any | None = None,
        title: Any | None = None,
        company: Any | None = None,
        school: Any | None = None,
        page: Any | None = None,
        geocode_location: Any | None = None,
        current_company: Any | None = None,
        profile_language: Any | None = None,
        industry: Any | None = None,
        service_category: Any | None = None,
    ) -> Any:
        """搜索用户/Search people

        ``GET /api/v1/linkedin/web/search_people``
        """
        params = _drop_none({
            "name": name,
            "first_name": first_name,
            "last_name": last_name,
            "title": title,
            "company": company,
            "school": school,
            "page": page,
            "geocode_location": geocode_location,
            "current_company": current_company,
            "profile_language": profile_language,
            "industry": industry,
            "service_category": service_category,
        })
        return await self._client._request("GET", "/api/v1/linkedin/web/search_people", params=params)
