# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Temp-Mail-API resource.

OpenAPI tag: ``Temp-Mail-API``
SDK attribute: ``client.temp_mail`` / ``async_client.temp_mail``

Endpoints: 3
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTempMail", "TempMail"]


class TempMail(SyncResource):
    """Sync ``Temp-Mail-API`` resource (3 endpoints)."""

    def get_temp_email_address(
        self,
    ) -> Any:
        """Get Temp Email

        ``GET /api/v1/temp_mail/v1/get_temp_email_address``
        """
        return self._client._request("GET", "/api/v1/temp_mail/v1/get_temp_email_address")

    def get_emails_inbox(
        self,
        *,
        token: str,
    ) -> Any:
        """Get Emails

        ``GET /api/v1/temp_mail/v1/get_emails_inbox``
        """
        params = _drop_none({
            "token": token,
        })
        return self._client._request("GET", "/api/v1/temp_mail/v1/get_emails_inbox", params=params)

    def get_email_by_id(
        self,
        *,
        token: str,
        message_id: str,
    ) -> Any:
        """Get Email By Id

        ``GET /api/v1/temp_mail/v1/get_email_by_id``
        """
        params = _drop_none({
            "token": token,
            "message_id": message_id,
        })
        return self._client._request("GET", "/api/v1/temp_mail/v1/get_email_by_id", params=params)


class AsyncTempMail(AsyncResource):
    """Async ``Temp-Mail-API`` resource (3 endpoints)."""

    async def get_temp_email_address(
        self,
    ) -> Any:
        """Get Temp Email

        ``GET /api/v1/temp_mail/v1/get_temp_email_address``
        """
        return await self._client._request("GET", "/api/v1/temp_mail/v1/get_temp_email_address")

    async def get_emails_inbox(
        self,
        *,
        token: str,
    ) -> Any:
        """Get Emails

        ``GET /api/v1/temp_mail/v1/get_emails_inbox``
        """
        params = _drop_none({
            "token": token,
        })
        return await self._client._request("GET", "/api/v1/temp_mail/v1/get_emails_inbox", params=params)

    async def get_email_by_id(
        self,
        *,
        token: str,
        message_id: str,
    ) -> Any:
        """Get Email By Id

        ``GET /api/v1/temp_mail/v1/get_email_by_id``
        """
        params = _drop_none({
            "token": token,
            "message_id": message_id,
        })
        return await self._client._request("GET", "/api/v1/temp_mail/v1/get_email_by_id", params=params)
