# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikHub-Downloader-API resource.

OpenAPI tag: ``TikHub-Downloader-API``
SDK attribute: ``client.tikhub_downloader`` / ``async_client.tikhub_downloader``

Endpoints: 2
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTikhubDownloader", "TikhubDownloader"]


class TikhubDownloader(SyncResource):
    """Sync ``TikHub-Downloader-API`` resource (2 endpoints)."""

    def version(
        self,
    ) -> Any:
        """检查TikHub下载器的版本更新 / Check for TikHub Downloader version updates

        ``GET /api/v1/tikhub/downloader/version``
        """
        return self._client._request("GET", "/api/v1/tikhub/downloader/version")

    def redirect_download(
        self,
    ) -> Any:
        """重定向到最新版本的下载链接 / Redirect to the latest version download link

        ``GET /api/v1/tikhub/downloader/redirect_download``
        """
        return self._client._request("GET", "/api/v1/tikhub/downloader/redirect_download")


class AsyncTikhubDownloader(AsyncResource):
    """Async ``TikHub-Downloader-API`` resource (2 endpoints)."""

    async def version(
        self,
    ) -> Any:
        """检查TikHub下载器的版本更新 / Check for TikHub Downloader version updates

        ``GET /api/v1/tikhub/downloader/version``
        """
        return await self._client._request("GET", "/api/v1/tikhub/downloader/version")

    async def redirect_download(
        self,
    ) -> Any:
        """重定向到最新版本的下载链接 / Redirect to the latest version download link

        ``GET /api/v1/tikhub/downloader/redirect_download``
        """
        return await self._client._request("GET", "/api/v1/tikhub/downloader/redirect_download")
