# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikTok-Creator-API resource.

OpenAPI tag: ``TikTok-Creator-API``
SDK attribute: ``client.tiktok_creator`` / ``async_client.tiktok_creator``

Endpoints: 14
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTiktokCreator", "TiktokCreator"]


class TiktokCreator(SyncResource):
    """Sync ``TikTok-Creator-API`` resource (14 endpoints)."""

    def get_account_health_status(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者账号健康状态/Get Creator Account Health Status

        ``POST /api/v1/tiktok/creator/get_account_health_status``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_account_health_status", json=json_body)

    def get_account_violation_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        page: int | None = None,
    ) -> Any:
        """获取创作者账号违规记录列表/Get Creator Account Violation Record List

        ``POST /api/v1/tiktok/creator/get_account_violation_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "page": page,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_account_violation_list", json=json_body)

    def get_account_insights_overview(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取创作者账号概览/Get Creator Account Overview

        ``POST /api/v1/tiktok/creator/get_account_insights_overview``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_account_insights_overview", json=json_body)

    def get_live_analytics_summary(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取创作者直播概览/Get Creator Live Overview

        ``POST /api/v1/tiktok/creator/get_live_analytics_summary``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_live_analytics_summary", json=json_body)

    def get_video_analytics_summary(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者视频概览/Get Creator Video Overview

        ``POST /api/v1/tiktok/creator/get_video_analytics_summary``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_analytics_summary", json=json_body)

    def get_video_list_analytics(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
        page: int | None = None,
        rules: str | None = None,
    ) -> Any:
        """获取创作者视频列表分析/Get Creator Video List Analytics

        ``POST /api/v1/tiktok/creator/get_video_list_analytics``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "page": page,
            "rules": rules,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_list_analytics", json=json_body)

    def get_product_analytics_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        page: int | None = None,
    ) -> Any:
        """获取创作者商品列表分析/Get Creator Product List Analytics

        ``POST /api/v1/tiktok/creator/get_product_analytics_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "end_date": end_date,
            "page": page,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_product_analytics_list", json=json_body)

    def get_creator_account_info(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者账号信息/Get Creator Account Info

        ``POST /api/v1/tiktok/creator/get_creator_account_info``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_creator_account_info", json=json_body)

    def get_showcase_product_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        count: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取橱窗商品列表/Get Showcase Product List

        ``POST /api/v1/tiktok/creator/get_showcase_product_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "count": count,
            "offset": offset,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_showcase_product_list", json=json_body)

    def get_video_associated_product_list(
        self,
        *,
        item_ids: list[Any],
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频关联商品列表/Get Video Associated Product List

        ``POST /api/v1/tiktok/creator/get_video_associated_product_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_ids": item_ids,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_associated_product_list", json=json_body)

    def get_video_detailed_stats(
        self,
        *,
        item_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频详细分段统计数据/Get Video Detailed Statistics

        ``POST /api/v1/tiktok/creator/get_video_detailed_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_detailed_stats", json=json_body)

    def get_video_to_product_stats(
        self,
        *,
        item_id: str,
        product_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频与商品关联统计数据/Get Video-Product Association Statistics

        ``POST /api/v1/tiktok/creator/get_video_to_product_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
            "product_id": product_id,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_to_product_stats", json=json_body)

    def get_product_related_videos(
        self,
        *,
        item_id: str,
        product_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取同款商品关联视频/Get Product Related Videos

        ``POST /api/v1/tiktok/creator/get_product_related_videos``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
            "product_id": product_id,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_product_related_videos", json=json_body)

    def get_video_audience_stats(
        self,
        *,
        item_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频受众分析数据/Get Video Audience Analysis Data

        ``POST /api/v1/tiktok/creator/get_video_audience_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
        })
        return self._client._request("POST", "/api/v1/tiktok/creator/get_video_audience_stats", json=json_body)


class AsyncTiktokCreator(AsyncResource):
    """Async ``TikTok-Creator-API`` resource (14 endpoints)."""

    async def get_account_health_status(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者账号健康状态/Get Creator Account Health Status

        ``POST /api/v1/tiktok/creator/get_account_health_status``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_account_health_status", json=json_body)

    async def get_account_violation_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        page: int | None = None,
    ) -> Any:
        """获取创作者账号违规记录列表/Get Creator Account Violation Record List

        ``POST /api/v1/tiktok/creator/get_account_violation_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "page": page,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_account_violation_list", json=json_body)

    async def get_account_insights_overview(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取创作者账号概览/Get Creator Account Overview

        ``POST /api/v1/tiktok/creator/get_account_insights_overview``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_account_insights_overview", json=json_body)

    async def get_live_analytics_summary(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取创作者直播概览/Get Creator Live Overview

        ``POST /api/v1/tiktok/creator/get_live_analytics_summary``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_live_analytics_summary", json=json_body)

    async def get_video_analytics_summary(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者视频概览/Get Creator Video Overview

        ``POST /api/v1/tiktok/creator/get_video_analytics_summary``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_analytics_summary", json=json_body)

    async def get_video_list_analytics(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
        page: int | None = None,
        rules: str | None = None,
    ) -> Any:
        """获取创作者视频列表分析/Get Creator Video List Analytics

        ``POST /api/v1/tiktok/creator/get_video_list_analytics``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "page": page,
            "rules": rules,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_list_analytics", json=json_body)

    async def get_product_analytics_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
        end_date: str | None = None,
        page: int | None = None,
    ) -> Any:
        """获取创作者商品列表分析/Get Creator Product List Analytics

        ``POST /api/v1/tiktok/creator/get_product_analytics_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "end_date": end_date,
            "page": page,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_product_analytics_list", json=json_body)

    async def get_creator_account_info(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
    ) -> Any:
        """获取创作者账号信息/Get Creator Account Info

        ``POST /api/v1/tiktok/creator/get_creator_account_info``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_creator_account_info", json=json_body)

    async def get_showcase_product_list(
        self,
        *,
        cookie: str | None = None,
        proxy: Any | None = None,
        count: int | None = None,
        offset: int | None = None,
    ) -> Any:
        """获取橱窗商品列表/Get Showcase Product List

        ``POST /api/v1/tiktok/creator/get_showcase_product_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "count": count,
            "offset": offset,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_showcase_product_list", json=json_body)

    async def get_video_associated_product_list(
        self,
        *,
        item_ids: list[Any],
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频关联商品列表/Get Video Associated Product List

        ``POST /api/v1/tiktok/creator/get_video_associated_product_list``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_ids": item_ids,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_associated_product_list", json=json_body)

    async def get_video_detailed_stats(
        self,
        *,
        item_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频详细分段统计数据/Get Video Detailed Statistics

        ``POST /api/v1/tiktok/creator/get_video_detailed_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_detailed_stats", json=json_body)

    async def get_video_to_product_stats(
        self,
        *,
        item_id: str,
        product_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频与商品关联统计数据/Get Video-Product Association Statistics

        ``POST /api/v1/tiktok/creator/get_video_to_product_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
            "product_id": product_id,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_to_product_stats", json=json_body)

    async def get_product_related_videos(
        self,
        *,
        item_id: str,
        product_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取同款商品关联视频/Get Product Related Videos

        ``POST /api/v1/tiktok/creator/get_product_related_videos``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
            "product_id": product_id,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_product_related_videos", json=json_body)

    async def get_video_audience_stats(
        self,
        *,
        item_id: str,
        cookie: str | None = None,
        proxy: Any | None = None,
        start_date: str | None = None,
    ) -> Any:
        """获取视频受众分析数据/Get Video Audience Analysis Data

        ``POST /api/v1/tiktok/creator/get_video_audience_stats``
        """
        json_body = _drop_none({
            "cookie": cookie,
            "proxy": proxy,
            "start_date": start_date,
            "item_id": item_id,
        })
        return await self._client._request("POST", "/api/v1/tiktok/creator/get_video_audience_stats", json=json_body)
