# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikTok-App-V3-API resource.

OpenAPI tag: ``TikTok-App-V3-API``
SDK attribute: ``client.tiktok_app_v3`` / ``async_client.tiktok_app_v3``

Endpoints: 75
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTiktokAppV3", "TiktokAppV3"]


class TiktokAppV3(SyncResource):
    """Sync ``TikTok-App-V3-API`` resource (75 endpoints)."""

    def fetch_one_video(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据/Get single video data

        ``GET /api/v1/tiktok/app/v3/fetch_one_video``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video", params=params)

    def fetch_one_video_v2(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据 V2/Get single video data V2

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_v2``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_v2", params=params)

    def fetch_one_video_v3(
        self,
        *,
        aweme_id: str,
        region: str | None = None,
    ) -> Any:
        """获取单个作品数据 V3(支持国家参数)/Get single video data V3 (support country parameter)

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_v3``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_v3", params=params)

    def fetch_multi_video(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息/Batch Get Video Information

        ``POST /api/v1/tiktok/app/v3/fetch_multi_video``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_multi_video", json=json_body)

    def fetch_multi_video_v2(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息 V2/Batch Get Video Information V2

        ``POST /api/v1/tiktok/app/v3/fetch_multi_video_v2``
        """
        json_body = body
        return self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_multi_video_v2", json=json_body)

    def fetch_one_video_by_share_url_v2(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_by_share_url_v2``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_by_share_url_v2", params=params)

    def fetch_one_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_by_share_url", params=params)

    def get_user_id_and_sec_user_id_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """使用用户名获取用户 user_id 和 sec_user_id/Get user_id and sec_user_id by Username

        ``GET /api/v1/tiktok/app/v3/get_user_id_and_sec_user_id_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/get_user_id_and_sec_user_id_by_username", params=params)

    def handler_user_profile(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
    ) -> Any:
        """获取指定用户的信息/Get information of specified user

        ``GET /api/v1/tiktok/app/v3/handler_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/handler_user_profile", params=params)

    def fetch_webcast_user_info(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
    ) -> Any:
        """获取指定 Webcast 用户的信息/Get information of specified Webcast user

        ``GET /api/v1/tiktok/app/v3/fetch_webcast_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_webcast_user_info", params=params)

    def fetch_user_country_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """通过用户名获取用户账号国家地区/Get user account country by username

        ``GET /api/v1/tiktok/app/v3/fetch_user_country_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_country_by_username", params=params)

    def fetch_similar_user_recommendations(
        self,
        *,
        sec_uid: str,
        page_token: str | None = None,
    ) -> Any:
        """获取类似用户推荐/Similar User Recommendations

        ``GET /api/v1/tiktok/app/v3/fetch_similar_user_recommendations``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
            "page_token": page_token,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_similar_user_recommendations", params=params)

    def fetch_user_repost_videos(
        self,
        *,
        user_id: int,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户转发的作品数据/Get user repost video data

        ``GET /api/v1/tiktok/app/v3/fetch_user_repost_videos``
        """
        params = _drop_none({
            "user_id": user_id,
            "offset": offset,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_repost_videos", params=params)

    def fetch_user_post_videos(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V1/Get user homepage video data V1

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos", params=params)

    def fetch_user_post_videos_v2(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V2/Get user homepage video data V2

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos_v2``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos_v2", params=params)

    def fetch_user_post_videos_v3(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V3（精简数据-更快速）/Get user homepage video data V3 (simplified data - faster)

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos_v3``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos_v3", params=params)

    def fetch_user_like_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户喜欢作品数据/Get user like video data

        ``GET /api/v1/tiktok/app/v3/fetch_user_like_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_like_videos", params=params)

    def fetch_video_comments(
        self,
        *,
        aweme_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取单个视频评论数据/Get single video comments data

        ``GET /api/v1/tiktok/app/v3/fetch_video_comments``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_comments", params=params)

    def fetch_video_comment_replies(
        self,
        *,
        item_id: str,
        comment_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定视频的评论回复数据/Get comment replies data of specified video

        ``GET /api/v1/tiktok/app/v3/fetch_video_comment_replies``
        """
        params = _drop_none({
            "item_id": item_id,
            "comment_id": comment_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_comment_replies", params=params)

    def fetch_general_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        publish_time: int | None = None,
    ) -> Any:
        """获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_general_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "sort_type": sort_type,
            "publish_time": publish_time,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_general_search_result", params=params)

    def fetch_video_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        publish_time: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的视频搜索结果/Get video search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_video_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_search_result", params=params)

    def fetch_user_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        user_search_follower_count: str | None = None,
        user_search_profile_type: str | None = None,
        user_search_other_pref: str | None = None,
    ) -> Any:
        """获取指定关键词的用户搜索结果/Get user search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_user_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "user_search_follower_count": user_search_follower_count,
            "user_search_profile_type": user_search_profile_type,
            "user_search_other_pref": user_search_other_pref,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_search_result", params=params)

    def fetch_music_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        filter_by: int | None = None,
        sort_type: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的音乐搜索结果/Get music search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_music_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "filter_by": filter_by,
            "sort_type": sort_type,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_search_result", params=params)

    def fetch_hashtag_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_search_result", params=params)

    def fetch_live_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的直播搜索结果/Get live search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_live_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_search_result", params=params)

    def fetch_location_search(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取地点搜索结果/Get location search results

        ``GET /api/v1/tiktok/app/v3/fetch_location_search``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_location_search", params=params)

    def fetch_music_detail(
        self,
        *,
        music_id: str,
    ) -> Any:
        """获取指定音乐的详情数据/Get details of specified music

        ``GET /api/v1/tiktok/app/v3/fetch_music_detail``
        """
        params = _drop_none({
            "music_id": music_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_detail", params=params)

    def fetch_music_video_list(
        self,
        *,
        music_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定音乐的视频列表数据/Get video list of specified music

        ``GET /api/v1/tiktok/app/v3/fetch_music_video_list``
        """
        params = _drop_none({
            "music_id": music_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_video_list", params=params)

    def fetch_hashtag_detail(
        self,
        *,
        ch_id: str,
    ) -> Any:
        """获取指定话题的详情数据/Get details of specified hashtag

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_detail``
        """
        params = _drop_none({
            "ch_id": ch_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_detail", params=params)

    def fetch_hashtag_video_list(
        self,
        *,
        ch_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定话题的作品数据/Get video list of specified hashtag

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_video_list``
        """
        params = _drop_none({
            "ch_id": ch_id,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_video_list", params=params)

    def fetch_user_follower_list(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        count: int | None = None,
        min_time: int | None = None,
        page_token: str | None = None,
    ) -> Any:
        """获取指定用户的粉丝列表数据/Get follower list of specified user

        ``GET /api/v1/tiktok/app/v3/fetch_user_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "count": count,
            "min_time": min_time,
            "page_token": page_token,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_follower_list", params=params)

    def fetch_user_following_list(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        count: int | None = None,
        min_time: int | None = None,
        page_token: str | None = None,
    ) -> Any:
        """获取指定用户的关注列表数据/Get following list of specified user

        ``GET /api/v1/tiktok/app/v3/fetch_user_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "count": count,
            "min_time": min_time,
            "page_token": page_token,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_following_list", params=params)

    def fetch_creator_search_insights(
        self,
        *,
        offset: int | None = None,
        limit: int | None = None,
        tab: str | None = None,
        language_filters: str | None = None,
        category_filters: str | None = None,
        creator_source: str | None = None,
        force_refresh: bool | None = None,
    ) -> Any:
        """创作者搜索洞察/Creator Search Insights

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights``
        """
        params = _drop_none({
            "offset": offset,
            "limit": limit,
            "tab": tab,
            "language_filters": language_filters,
            "category_filters": category_filters,
            "creator_source": creator_source,
            "force_refresh": force_refresh,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights", params=params)

    def fetch_creator_search_insights_detail(
        self,
        *,
        query_id_str: str,
        time_range: str | None = None,
        start_date: int | None = None,
        end_date: int | None = None,
        dimension_list: str | None = None,
    ) -> Any:
        """创作者搜索洞察详情/Creator Search Insights Detail

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_detail``
        """
        params = _drop_none({
            "query_id_str": query_id_str,
            "time_range": time_range,
            "start_date": start_date,
            "end_date": end_date,
            "dimension_list": dimension_list,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_detail", params=params)

    def fetch_creator_search_insights_trend(
        self,
        *,
        query_id_str: str,
        from_tab_path: str | None = None,
        query_analysis_required: bool | None = None,
    ) -> Any:
        """创作者搜索洞察趋势/Creator Search Insights Trend

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_trend``
        """
        params = _drop_none({
            "query_id_str": query_id_str,
            "from_tab_path": from_tab_path,
            "query_analysis_required": query_analysis_required,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_trend", params=params)

    def fetch_creator_search_insights_videos(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """创作者搜索洞察相关视频/Creator Search Insights Videos

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_videos``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_videos", params=params)

    def fetch_music_chart_list(
        self,
        *,
        scene: int | None = None,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """音乐排行榜/Music Chart List

        ``GET /api/v1/tiktok/app/v3/fetch_music_chart_list``
        """
        params = _drop_none({
            "scene": scene,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_chart_list", params=params)

    def search_follower_list(
        self,
        *,
        user_id: str,
        keyword: str,
    ) -> Any:
        """搜索粉丝列表/Search follower list

        ``GET /api/v1/tiktok/app/v3/search_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/search_follower_list", params=params)

    def search_following_list(
        self,
        *,
        user_id: str,
        keyword: str,
    ) -> Any:
        """搜索关注列表/Search following list

        ``GET /api/v1/tiktok/app/v3/search_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/search_following_list", params=params)

    def fetch_live_room_info(
        self,
        *,
        room_id: str,
    ) -> Any:
        """获取指定直播间的数据/Get data of specified live room

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_info``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_info", params=params)

    def fetch_live_ranking_list(
        self,
        *,
        room_id: str,
        anchor_id: str,
    ) -> Any:
        """获取直播间排行榜数据/Get live room ranking list

        ``GET /api/v1/tiktok/app/v3/fetch_live_ranking_list``
        """
        params = _drop_none({
            "room_id": room_id,
            "anchor_id": anchor_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_ranking_list", params=params)

    def check_live_room_online(
        self,
        *,
        room_id: str,
    ) -> Any:
        """检测直播间是否在线/Check if live room is online

        ``GET /api/v1/tiktok/app/v3/check_live_room_online``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/check_live_room_online", params=params)

    def check_live_room_online_batch(
        self,
        *,
        room_ids: list[Any] | None = None,
    ) -> Any:
        """批量检测直播间是否在线/Batch check if live rooms are online

        ``POST /api/v1/tiktok/app/v3/check_live_room_online_batch``
        """
        json_body = _drop_none({
            "room_ids": room_ids,
        })
        return self._client._request("POST", "/api/v1/tiktok/app/v3/check_live_room_online_batch", json=json_body)

    def fetch_share_short_link(
        self,
        *,
        url: str,
    ) -> Any:
        """获取分享短链接/Get share short link

        ``GET /api/v1/tiktok/app/v3/fetch_share_short_link``
        """
        params = _drop_none({
            "url": url,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_share_short_link", params=params)

    def fetch_share_qr_code(
        self,
        *,
        object_id: str,
        schema_type: int | None = None,
    ) -> Any:
        """获取分享二维码/Get share QR code

        ``GET /api/v1/tiktok/app/v3/fetch_share_qr_code``
        """
        params = _drop_none({
            "object_id": object_id,
            "schema_type": schema_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_share_qr_code", params=params)

    def fetch_product_search(
        self,
        *,
        keyword: str,
        cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        customer_review_four_star: bool | None = None,
        have_discount: bool | None = None,
        min_price: str | None = None,
        max_price: str | None = None,
    ) -> Any:
        """获取商品搜索结果/Get product search results

        ``GET /api/v1/tiktok/app/v3/fetch_product_search``
        """
        params = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "count": count,
            "sort_type": sort_type,
            "customer_review_four_star": customer_review_four_star,
            "have_discount": have_discount,
            "min_price": min_price,
            "max_price": max_price,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_search", params=params)

    def fetch_creator_info(
        self,
        *,
        creator_uid: str,
    ) -> Any:
        """获取带货创作者信息/Get shopping creator information

        ``GET /api/v1/tiktok/app/v3/fetch_creator_info``
        """
        params = _drop_none({
            "creator_uid": creator_uid,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_info", params=params)

    def fetch_creator_showcase_product_list(
        self,
        *,
        kol_id: str,
        count: int | None = None,
        next_scroll_param: str | None = None,
    ) -> Any:
        """获取创作者橱窗商品列表/Get creator showcase product list

        ``GET /api/v1/tiktok/app/v3/fetch_creator_showcase_product_list``
        """
        params = _drop_none({
            "kol_id": kol_id,
            "count": count,
            "next_scroll_param": next_scroll_param,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_showcase_product_list", params=params)

    def fetch_shop_id_by_share_link(
        self,
        *,
        share_link: str,
    ) -> Any:
        """通过分享链接获取店铺ID/Get Shop ID by Share Link

        ``GET /api/v1/tiktok/app/v3/fetch_shop_id_by_share_link``
        """
        params = _drop_none({
            "share_link": share_link,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_id_by_share_link", params=params)

    def fetch_product_id_by_share_link(
        self,
        *,
        share_link: str,
    ) -> Any:
        """通过分享链接获取商品ID/Get Product ID by Share Link

        ``GET /api/v1/tiktok/app/v3/fetch_product_id_by_share_link``
        """
        params = _drop_none({
            "share_link": share_link,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_id_by_share_link", params=params)

    def fetch_product_detail(
        self,
        *,
        product_id: str,
    ) -> Any:
        """获取商品详情数据（即将弃用，使用 fetch_product_detail_v2 代替）/Get product detail data (will be deprecated, use fetch_product_detail_v2 instead)

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail``
        """
        params = _drop_none({
            "product_id": product_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail", params=params)

    def fetch_product_detail_v2(
        self,
        *,
        product_id: str,
    ) -> Any:
        """获取商品详情数据V2/Get product detail data V2

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v2``
        """
        params = _drop_none({
            "product_id": product_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v2", params=params)

    def fetch_product_detail_v3(
        self,
        *,
        product_id: str,
        region: str | None = None,
    ) -> Any:
        """获取商品详情数据V3 / Get product detail data V3

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v3``
        """
        params = _drop_none({
            "product_id": product_id,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v3", params=params)

    def fetch_product_detail_v4(
        self,
        *,
        product_id: str,
        region: str | None = None,
    ) -> Any:
        """获取商品详情数据V4 / Get product detail data V4

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v4``
        """
        params = _drop_none({
            "product_id": product_id,
            "region": region,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v4", params=params)

    def fetch_product_review(
        self,
        *,
        product_id: str,
        cursor: int | None = None,
        size: int | None = None,
        filter_id: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取商品评价数据/Get product review data

        ``GET /api/v1/tiktok/app/v3/fetch_product_review``
        """
        params = _drop_none({
            "product_id": product_id,
            "cursor": cursor,
            "size": size,
            "filter_id": filter_id,
            "sort_type": sort_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_review", params=params)

    def fetch_shop_home_page_list(
        self,
        *,
        seller_id: str,
    ) -> Any:
        """获取商家主页Page列表数据/Get shop home page list data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_home_page_list``
        """
        params = _drop_none({
            "seller_id": seller_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_home_page_list", params=params)

    def fetch_shop_home(
        self,
        *,
        page_id: str,
        seller_id: str,
    ) -> Any:
        """获取商家主页数据/Get shop home page data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_home``
        """
        params = _drop_none({
            "page_id": page_id,
            "seller_id": seller_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_home", params=params)

    def fetch_shop_product_recommend(
        self,
        *,
        seller_id: str,
        scroll_param: str | None = None,
        page_size: int | None = None,
    ) -> Any:
        """获取商家商品推荐数据/Get shop product recommend data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_recommend``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_param": scroll_param,
            "page_size": page_size,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_recommend", params=params)

    def fetch_shop_product_list(
        self,
        *,
        seller_id: str,
        scroll_params: str | None = None,
        page_size: int | None = None,
        sort_field: int | None = None,
        sort_order: int | None = None,
    ) -> Any:
        """获取商家商品列表数据/Get shop product list data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_list``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_params": scroll_params,
            "page_size": page_size,
            "sort_field": sort_field,
            "sort_order": sort_order,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_list", params=params)

    def fetch_shop_product_list_v2(
        self,
        *,
        seller_id: str,
        scroll_params: str | None = None,
        page_size: int | None = None,
        sort_field: int | None = None,
        sort_order: int | None = None,
    ) -> Any:
        """获取商家商品列表数据 V2/Get shop product list data V2

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_list_v2``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_params": scroll_params,
            "page_size": page_size,
            "sort_field": sort_field,
            "sort_order": sort_order,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_list_v2", params=params)

    def fetch_shop_info(
        self,
        *,
        shop_id: str,
    ) -> Any:
        """获取商家信息数据/Get shop information data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_info``
        """
        params = _drop_none({
            "shop_id": shop_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_info", params=params)

    def fetch_shop_product_category(
        self,
        *,
        seller_id: str,
    ) -> Any:
        """获取商家产品分类数据/Get shop product category data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_category``
        """
        params = _drop_none({
            "seller_id": seller_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_category", params=params)

    def fetch_live_daily_rank(
        self,
        *,
        anchor_id: str | None = None,
        room_id: str | None = None,
        rank_type: int | None = None,
        region_type: int | None = None,
        gap_interval: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播每日榜单数据/Get live daily rank data

        ``GET /api/v1/tiktok/app/v3/fetch_live_daily_rank``
        """
        params = _drop_none({
            "anchor_id": anchor_id,
            "room_id": room_id,
            "rank_type": rank_type,
            "region_type": region_type,
            "gap_interval": gap_interval,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_daily_rank", params=params)

    def fetch_user_music_list(
        self,
        *,
        sec_uid: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户音乐列表数据/Get user music list data

        ``GET /api/v1/tiktok/app/v3/fetch_user_music_list``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
            "cursor": cursor,
            "count": count,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_music_list", params=params)

    def fetch_content_translate(
        self,
        *,
        trg_lang: str | None = None,
        src_content: str | None = None,
    ) -> Any:
        """获取内容翻译数据/Get content translation data

        ``POST /api/v1/tiktok/app/v3/fetch_content_translate``
        """
        json_body = _drop_none({
            "trg_lang": trg_lang,
            "src_content": src_content,
        })
        return self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_content_translate", json=json_body)

    def fetch_home_feed(
        self,
        *,
        cookie: str | None = None,
    ) -> Any:
        """获取主页视频推荐数据/Get home feed(recommend) video data

        ``POST /api/v1/tiktok/app/v3/fetch_home_feed``
        """
        json_body = _drop_none({
            "cookie": cookie,
        })
        return self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_home_feed", json=json_body)

    def TTencrypt_algorithm(
        self,
        *,
        url: str | None = None,
        data: str | None = None,
        device_info: dict[str, Any] | None = None,
    ) -> Any:
        """TikTok APP加密算法/TikTok APP encryption algorithm

        ``POST /api/v1/tiktok/app/v3/TTencrypt_algorithm``
        """
        json_body = _drop_none({
            "url": url,
            "data": data,
            "device_info": device_info,
        })
        return self._client._request("POST", "/api/v1/tiktok/app/v3/TTencrypt_algorithm", json=json_body)

    def fetch_live_room_product_list(
        self,
        *,
        room_id: str,
        author_id: str,
        page_size: int | None = None,
        offset: int | None = None,
        region: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播间商品列表数据/Get live room product list data

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_product_list``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "page_size": page_size,
            "offset": offset,
            "region": region,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_product_list", params=params)

    def fetch_live_room_product_list_v2(
        self,
        *,
        room_id: str,
        author_id: str,
        page_size: int | None = None,
        offset: int | None = None,
        region: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播间商品列表数据 V2 /Get live room product list data V2

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_product_list_v2``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "page_size": page_size,
            "offset": offset,
            "region": region,
            "cookie": cookie,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_product_list_v2", params=params)

    def add_video_play_count(
        self,
        *,
        aweme_type: int,
        item_id: str,
    ) -> Any:
        """根据视频ID来增加作品的播放数/Increase the number of plays of the work according to the video ID

        ``GET /api/v1/tiktok/app/v3/add_video_play_count``
        """
        params = _drop_none({
            "aweme_type": aweme_type,
            "item_id": item_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/add_video_play_count", params=params)

    def encrypt_decrypt_login_request(
        self,
        *,
        username: str | None = None,
        password: str | None = None,
        mode: Any | None = None,
    ) -> Any:
        """加密或解密 TikTok APP 登录请求体/Encrypt or Decrypt TikTok APP login request body

        ``POST /api/v1/tiktok/app/v3/encrypt_decrypt_login_request``
        """
        json_body = _drop_none({
            "username": username,
            "password": password,
            "mode": mode,
        })
        return self._client._request("POST", "/api/v1/tiktok/app/v3/encrypt_decrypt_login_request", json=json_body)

    def open_tiktok_app_to_video_detail(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定作品详情页/Generate TikTok share link, call TikTok APP, and jump to the specified video details page

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_video_detail``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_video_detail", params=params)

    def open_tiktok_app_to_user_profile(
        self,
        *,
        uid: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定用户主页/Generate TikTok share link, call TikTok APP, and jump to the specified user profile

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_user_profile``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_user_profile", params=params)

    def open_tiktok_app_to_keyword_search(
        self,
        *,
        keyword: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定关键词搜索结果/Generate TikTok share link, call TikTok APP, and jump to the specified keyword search result

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_keyword_search``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_keyword_search", params=params)

    def open_tiktok_app_to_send_private_message(
        self,
        *,
        uid: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，给指定用户发送私信/Generate TikTok share link, call TikTok APP, and send private messages to specified users

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_send_private_message``
        """
        params = _drop_none({
            "uid": uid,
        })
        return self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_send_private_message", params=params)


class AsyncTiktokAppV3(AsyncResource):
    """Async ``TikTok-App-V3-API`` resource (75 endpoints)."""

    async def fetch_one_video(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据/Get single video data

        ``GET /api/v1/tiktok/app/v3/fetch_one_video``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video", params=params)

    async def fetch_one_video_v2(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """获取单个作品数据 V2/Get single video data V2

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_v2``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_v2", params=params)

    async def fetch_one_video_v3(
        self,
        *,
        aweme_id: str,
        region: str | None = None,
    ) -> Any:
        """获取单个作品数据 V3(支持国家参数)/Get single video data V3 (support country parameter)

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_v3``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_v3", params=params)

    async def fetch_multi_video(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息/Batch Get Video Information

        ``POST /api/v1/tiktok/app/v3/fetch_multi_video``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_multi_video", json=json_body)

    async def fetch_multi_video_v2(
        self,
        *,
        body: list[Any],
    ) -> Any:
        """批量获取视频信息 V2/Batch Get Video Information V2

        ``POST /api/v1/tiktok/app/v3/fetch_multi_video_v2``
        """
        json_body = body
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_multi_video_v2", json=json_body)

    async def fetch_one_video_by_share_url_v2(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_by_share_url_v2``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_by_share_url_v2", params=params)

    async def fetch_one_video_by_share_url(
        self,
        *,
        share_url: str,
    ) -> Any:
        """根据分享链接获取单个作品数据/Get single video data by sharing link

        ``GET /api/v1/tiktok/app/v3/fetch_one_video_by_share_url``
        """
        params = _drop_none({
            "share_url": share_url,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_one_video_by_share_url", params=params)

    async def get_user_id_and_sec_user_id_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """使用用户名获取用户 user_id 和 sec_user_id/Get user_id and sec_user_id by Username

        ``GET /api/v1/tiktok/app/v3/get_user_id_and_sec_user_id_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/get_user_id_and_sec_user_id_by_username", params=params)

    async def handler_user_profile(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
    ) -> Any:
        """获取指定用户的信息/Get information of specified user

        ``GET /api/v1/tiktok/app/v3/handler_user_profile``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/handler_user_profile", params=params)

    async def fetch_webcast_user_info(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
    ) -> Any:
        """获取指定 Webcast 用户的信息/Get information of specified Webcast user

        ``GET /api/v1/tiktok/app/v3/fetch_webcast_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_webcast_user_info", params=params)

    async def fetch_user_country_by_username(
        self,
        *,
        username: str,
    ) -> Any:
        """通过用户名获取用户账号国家地区/Get user account country by username

        ``GET /api/v1/tiktok/app/v3/fetch_user_country_by_username``
        """
        params = _drop_none({
            "username": username,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_country_by_username", params=params)

    async def fetch_similar_user_recommendations(
        self,
        *,
        sec_uid: str,
        page_token: str | None = None,
    ) -> Any:
        """获取类似用户推荐/Similar User Recommendations

        ``GET /api/v1/tiktok/app/v3/fetch_similar_user_recommendations``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
            "page_token": page_token,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_similar_user_recommendations", params=params)

    async def fetch_user_repost_videos(
        self,
        *,
        user_id: int,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户转发的作品数据/Get user repost video data

        ``GET /api/v1/tiktok/app/v3/fetch_user_repost_videos``
        """
        params = _drop_none({
            "user_id": user_id,
            "offset": offset,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_repost_videos", params=params)

    async def fetch_user_post_videos(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V1/Get user homepage video data V1

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos", params=params)

    async def fetch_user_post_videos_v2(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V2/Get user homepage video data V2

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos_v2``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos_v2", params=params)

    async def fetch_user_post_videos_v3(
        self,
        *,
        sec_user_id: str | None = None,
        unique_id: str | None = None,
        max_cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取用户主页作品数据 V3（精简数据-更快速）/Get user homepage video data V3 (simplified data - faster)

        ``GET /api/v1/tiktok/app/v3/fetch_user_post_videos_v3``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "unique_id": unique_id,
            "max_cursor": max_cursor,
            "count": count,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_post_videos_v3", params=params)

    async def fetch_user_like_videos(
        self,
        *,
        sec_user_id: str,
        max_cursor: int | None = None,
        counts: int | None = None,
    ) -> Any:
        """获取用户喜欢作品数据/Get user like video data

        ``GET /api/v1/tiktok/app/v3/fetch_user_like_videos``
        """
        params = _drop_none({
            "sec_user_id": sec_user_id,
            "max_cursor": max_cursor,
            "counts": counts,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_like_videos", params=params)

    async def fetch_video_comments(
        self,
        *,
        aweme_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取单个视频评论数据/Get single video comments data

        ``GET /api/v1/tiktok/app/v3/fetch_video_comments``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_comments", params=params)

    async def fetch_video_comment_replies(
        self,
        *,
        item_id: str,
        comment_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定视频的评论回复数据/Get comment replies data of specified video

        ``GET /api/v1/tiktok/app/v3/fetch_video_comment_replies``
        """
        params = _drop_none({
            "item_id": item_id,
            "comment_id": comment_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_comment_replies", params=params)

    async def fetch_general_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        publish_time: int | None = None,
    ) -> Any:
        """获取指定关键词的综合搜索结果/Get comprehensive search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_general_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "sort_type": sort_type,
            "publish_time": publish_time,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_general_search_result", params=params)

    async def fetch_video_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        publish_time: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的视频搜索结果/Get video search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_video_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "sort_type": sort_type,
            "publish_time": publish_time,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_video_search_result", params=params)

    async def fetch_user_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        user_search_follower_count: str | None = None,
        user_search_profile_type: str | None = None,
        user_search_other_pref: str | None = None,
    ) -> Any:
        """获取指定关键词的用户搜索结果/Get user search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_user_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "user_search_follower_count": user_search_follower_count,
            "user_search_profile_type": user_search_profile_type,
            "user_search_other_pref": user_search_other_pref,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_search_result", params=params)

    async def fetch_music_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        filter_by: int | None = None,
        sort_type: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的音乐搜索结果/Get music search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_music_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "filter_by": filter_by,
            "sort_type": sort_type,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_search_result", params=params)

    async def fetch_hashtag_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定关键词的话题搜索结果/Get hashtag search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_search_result", params=params)

    async def fetch_live_search_result(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
        region: str | None = None,
    ) -> Any:
        """获取指定关键词的直播搜索结果/Get live search results of specified keywords

        ``GET /api/v1/tiktok/app/v3/fetch_live_search_result``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_search_result", params=params)

    async def fetch_location_search(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取地点搜索结果/Get location search results

        ``GET /api/v1/tiktok/app/v3/fetch_location_search``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_location_search", params=params)

    async def fetch_music_detail(
        self,
        *,
        music_id: str,
    ) -> Any:
        """获取指定音乐的详情数据/Get details of specified music

        ``GET /api/v1/tiktok/app/v3/fetch_music_detail``
        """
        params = _drop_none({
            "music_id": music_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_detail", params=params)

    async def fetch_music_video_list(
        self,
        *,
        music_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定音乐的视频列表数据/Get video list of specified music

        ``GET /api/v1/tiktok/app/v3/fetch_music_video_list``
        """
        params = _drop_none({
            "music_id": music_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_video_list", params=params)

    async def fetch_hashtag_detail(
        self,
        *,
        ch_id: str,
    ) -> Any:
        """获取指定话题的详情数据/Get details of specified hashtag

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_detail``
        """
        params = _drop_none({
            "ch_id": ch_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_detail", params=params)

    async def fetch_hashtag_video_list(
        self,
        *,
        ch_id: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取指定话题的作品数据/Get video list of specified hashtag

        ``GET /api/v1/tiktok/app/v3/fetch_hashtag_video_list``
        """
        params = _drop_none({
            "ch_id": ch_id,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_hashtag_video_list", params=params)

    async def fetch_user_follower_list(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        count: int | None = None,
        min_time: int | None = None,
        page_token: str | None = None,
    ) -> Any:
        """获取指定用户的粉丝列表数据/Get follower list of specified user

        ``GET /api/v1/tiktok/app/v3/fetch_user_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "count": count,
            "min_time": min_time,
            "page_token": page_token,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_follower_list", params=params)

    async def fetch_user_following_list(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        count: int | None = None,
        min_time: int | None = None,
        page_token: str | None = None,
    ) -> Any:
        """获取指定用户的关注列表数据/Get following list of specified user

        ``GET /api/v1/tiktok/app/v3/fetch_user_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "count": count,
            "min_time": min_time,
            "page_token": page_token,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_following_list", params=params)

    async def fetch_creator_search_insights(
        self,
        *,
        offset: int | None = None,
        limit: int | None = None,
        tab: str | None = None,
        language_filters: str | None = None,
        category_filters: str | None = None,
        creator_source: str | None = None,
        force_refresh: bool | None = None,
    ) -> Any:
        """创作者搜索洞察/Creator Search Insights

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights``
        """
        params = _drop_none({
            "offset": offset,
            "limit": limit,
            "tab": tab,
            "language_filters": language_filters,
            "category_filters": category_filters,
            "creator_source": creator_source,
            "force_refresh": force_refresh,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights", params=params)

    async def fetch_creator_search_insights_detail(
        self,
        *,
        query_id_str: str,
        time_range: str | None = None,
        start_date: int | None = None,
        end_date: int | None = None,
        dimension_list: str | None = None,
    ) -> Any:
        """创作者搜索洞察详情/Creator Search Insights Detail

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_detail``
        """
        params = _drop_none({
            "query_id_str": query_id_str,
            "time_range": time_range,
            "start_date": start_date,
            "end_date": end_date,
            "dimension_list": dimension_list,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_detail", params=params)

    async def fetch_creator_search_insights_trend(
        self,
        *,
        query_id_str: str,
        from_tab_path: str | None = None,
        query_analysis_required: bool | None = None,
    ) -> Any:
        """创作者搜索洞察趋势/Creator Search Insights Trend

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_trend``
        """
        params = _drop_none({
            "query_id_str": query_id_str,
            "from_tab_path": from_tab_path,
            "query_analysis_required": query_analysis_required,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_trend", params=params)

    async def fetch_creator_search_insights_videos(
        self,
        *,
        keyword: str,
        offset: int | None = None,
        count: int | None = None,
    ) -> Any:
        """创作者搜索洞察相关视频/Creator Search Insights Videos

        ``GET /api/v1/tiktok/app/v3/fetch_creator_search_insights_videos``
        """
        params = _drop_none({
            "keyword": keyword,
            "offset": offset,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_search_insights_videos", params=params)

    async def fetch_music_chart_list(
        self,
        *,
        scene: int | None = None,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """音乐排行榜/Music Chart List

        ``GET /api/v1/tiktok/app/v3/fetch_music_chart_list``
        """
        params = _drop_none({
            "scene": scene,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_music_chart_list", params=params)

    async def search_follower_list(
        self,
        *,
        user_id: str,
        keyword: str,
    ) -> Any:
        """搜索粉丝列表/Search follower list

        ``GET /api/v1/tiktok/app/v3/search_follower_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/search_follower_list", params=params)

    async def search_following_list(
        self,
        *,
        user_id: str,
        keyword: str,
    ) -> Any:
        """搜索关注列表/Search following list

        ``GET /api/v1/tiktok/app/v3/search_following_list``
        """
        params = _drop_none({
            "user_id": user_id,
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/search_following_list", params=params)

    async def fetch_live_room_info(
        self,
        *,
        room_id: str,
    ) -> Any:
        """获取指定直播间的数据/Get data of specified live room

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_info``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_info", params=params)

    async def fetch_live_ranking_list(
        self,
        *,
        room_id: str,
        anchor_id: str,
    ) -> Any:
        """获取直播间排行榜数据/Get live room ranking list

        ``GET /api/v1/tiktok/app/v3/fetch_live_ranking_list``
        """
        params = _drop_none({
            "room_id": room_id,
            "anchor_id": anchor_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_ranking_list", params=params)

    async def check_live_room_online(
        self,
        *,
        room_id: str,
    ) -> Any:
        """检测直播间是否在线/Check if live room is online

        ``GET /api/v1/tiktok/app/v3/check_live_room_online``
        """
        params = _drop_none({
            "room_id": room_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/check_live_room_online", params=params)

    async def check_live_room_online_batch(
        self,
        *,
        room_ids: list[Any] | None = None,
    ) -> Any:
        """批量检测直播间是否在线/Batch check if live rooms are online

        ``POST /api/v1/tiktok/app/v3/check_live_room_online_batch``
        """
        json_body = _drop_none({
            "room_ids": room_ids,
        })
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/check_live_room_online_batch", json=json_body)

    async def fetch_share_short_link(
        self,
        *,
        url: str,
    ) -> Any:
        """获取分享短链接/Get share short link

        ``GET /api/v1/tiktok/app/v3/fetch_share_short_link``
        """
        params = _drop_none({
            "url": url,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_share_short_link", params=params)

    async def fetch_share_qr_code(
        self,
        *,
        object_id: str,
        schema_type: int | None = None,
    ) -> Any:
        """获取分享二维码/Get share QR code

        ``GET /api/v1/tiktok/app/v3/fetch_share_qr_code``
        """
        params = _drop_none({
            "object_id": object_id,
            "schema_type": schema_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_share_qr_code", params=params)

    async def fetch_product_search(
        self,
        *,
        keyword: str,
        cursor: int | None = None,
        count: int | None = None,
        sort_type: int | None = None,
        customer_review_four_star: bool | None = None,
        have_discount: bool | None = None,
        min_price: str | None = None,
        max_price: str | None = None,
    ) -> Any:
        """获取商品搜索结果/Get product search results

        ``GET /api/v1/tiktok/app/v3/fetch_product_search``
        """
        params = _drop_none({
            "keyword": keyword,
            "cursor": cursor,
            "count": count,
            "sort_type": sort_type,
            "customer_review_four_star": customer_review_four_star,
            "have_discount": have_discount,
            "min_price": min_price,
            "max_price": max_price,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_search", params=params)

    async def fetch_creator_info(
        self,
        *,
        creator_uid: str,
    ) -> Any:
        """获取带货创作者信息/Get shopping creator information

        ``GET /api/v1/tiktok/app/v3/fetch_creator_info``
        """
        params = _drop_none({
            "creator_uid": creator_uid,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_info", params=params)

    async def fetch_creator_showcase_product_list(
        self,
        *,
        kol_id: str,
        count: int | None = None,
        next_scroll_param: str | None = None,
    ) -> Any:
        """获取创作者橱窗商品列表/Get creator showcase product list

        ``GET /api/v1/tiktok/app/v3/fetch_creator_showcase_product_list``
        """
        params = _drop_none({
            "kol_id": kol_id,
            "count": count,
            "next_scroll_param": next_scroll_param,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_creator_showcase_product_list", params=params)

    async def fetch_shop_id_by_share_link(
        self,
        *,
        share_link: str,
    ) -> Any:
        """通过分享链接获取店铺ID/Get Shop ID by Share Link

        ``GET /api/v1/tiktok/app/v3/fetch_shop_id_by_share_link``
        """
        params = _drop_none({
            "share_link": share_link,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_id_by_share_link", params=params)

    async def fetch_product_id_by_share_link(
        self,
        *,
        share_link: str,
    ) -> Any:
        """通过分享链接获取商品ID/Get Product ID by Share Link

        ``GET /api/v1/tiktok/app/v3/fetch_product_id_by_share_link``
        """
        params = _drop_none({
            "share_link": share_link,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_id_by_share_link", params=params)

    async def fetch_product_detail(
        self,
        *,
        product_id: str,
    ) -> Any:
        """获取商品详情数据（即将弃用，使用 fetch_product_detail_v2 代替）/Get product detail data (will be deprecated, use fetch_product_detail_v2 instead)

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail``
        """
        params = _drop_none({
            "product_id": product_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail", params=params)

    async def fetch_product_detail_v2(
        self,
        *,
        product_id: str,
    ) -> Any:
        """获取商品详情数据V2/Get product detail data V2

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v2``
        """
        params = _drop_none({
            "product_id": product_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v2", params=params)

    async def fetch_product_detail_v3(
        self,
        *,
        product_id: str,
        region: str | None = None,
    ) -> Any:
        """获取商品详情数据V3 / Get product detail data V3

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v3``
        """
        params = _drop_none({
            "product_id": product_id,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v3", params=params)

    async def fetch_product_detail_v4(
        self,
        *,
        product_id: str,
        region: str | None = None,
    ) -> Any:
        """获取商品详情数据V4 / Get product detail data V4

        ``GET /api/v1/tiktok/app/v3/fetch_product_detail_v4``
        """
        params = _drop_none({
            "product_id": product_id,
            "region": region,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_detail_v4", params=params)

    async def fetch_product_review(
        self,
        *,
        product_id: str,
        cursor: int | None = None,
        size: int | None = None,
        filter_id: int | None = None,
        sort_type: int | None = None,
    ) -> Any:
        """获取商品评价数据/Get product review data

        ``GET /api/v1/tiktok/app/v3/fetch_product_review``
        """
        params = _drop_none({
            "product_id": product_id,
            "cursor": cursor,
            "size": size,
            "filter_id": filter_id,
            "sort_type": sort_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_product_review", params=params)

    async def fetch_shop_home_page_list(
        self,
        *,
        seller_id: str,
    ) -> Any:
        """获取商家主页Page列表数据/Get shop home page list data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_home_page_list``
        """
        params = _drop_none({
            "seller_id": seller_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_home_page_list", params=params)

    async def fetch_shop_home(
        self,
        *,
        page_id: str,
        seller_id: str,
    ) -> Any:
        """获取商家主页数据/Get shop home page data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_home``
        """
        params = _drop_none({
            "page_id": page_id,
            "seller_id": seller_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_home", params=params)

    async def fetch_shop_product_recommend(
        self,
        *,
        seller_id: str,
        scroll_param: str | None = None,
        page_size: int | None = None,
    ) -> Any:
        """获取商家商品推荐数据/Get shop product recommend data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_recommend``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_param": scroll_param,
            "page_size": page_size,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_recommend", params=params)

    async def fetch_shop_product_list(
        self,
        *,
        seller_id: str,
        scroll_params: str | None = None,
        page_size: int | None = None,
        sort_field: int | None = None,
        sort_order: int | None = None,
    ) -> Any:
        """获取商家商品列表数据/Get shop product list data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_list``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_params": scroll_params,
            "page_size": page_size,
            "sort_field": sort_field,
            "sort_order": sort_order,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_list", params=params)

    async def fetch_shop_product_list_v2(
        self,
        *,
        seller_id: str,
        scroll_params: str | None = None,
        page_size: int | None = None,
        sort_field: int | None = None,
        sort_order: int | None = None,
    ) -> Any:
        """获取商家商品列表数据 V2/Get shop product list data V2

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_list_v2``
        """
        params = _drop_none({
            "seller_id": seller_id,
            "scroll_params": scroll_params,
            "page_size": page_size,
            "sort_field": sort_field,
            "sort_order": sort_order,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_list_v2", params=params)

    async def fetch_shop_info(
        self,
        *,
        shop_id: str,
    ) -> Any:
        """获取商家信息数据/Get shop information data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_info``
        """
        params = _drop_none({
            "shop_id": shop_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_info", params=params)

    async def fetch_shop_product_category(
        self,
        *,
        seller_id: str,
    ) -> Any:
        """获取商家产品分类数据/Get shop product category data

        ``GET /api/v1/tiktok/app/v3/fetch_shop_product_category``
        """
        params = _drop_none({
            "seller_id": seller_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_shop_product_category", params=params)

    async def fetch_live_daily_rank(
        self,
        *,
        anchor_id: str | None = None,
        room_id: str | None = None,
        rank_type: int | None = None,
        region_type: int | None = None,
        gap_interval: int | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播每日榜单数据/Get live daily rank data

        ``GET /api/v1/tiktok/app/v3/fetch_live_daily_rank``
        """
        params = _drop_none({
            "anchor_id": anchor_id,
            "room_id": room_id,
            "rank_type": rank_type,
            "region_type": region_type,
            "gap_interval": gap_interval,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_daily_rank", params=params)

    async def fetch_user_music_list(
        self,
        *,
        sec_uid: str,
        cursor: int | None = None,
        count: int | None = None,
    ) -> Any:
        """获取用户音乐列表数据/Get user music list data

        ``GET /api/v1/tiktok/app/v3/fetch_user_music_list``
        """
        params = _drop_none({
            "sec_uid": sec_uid,
            "cursor": cursor,
            "count": count,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_user_music_list", params=params)

    async def fetch_content_translate(
        self,
        *,
        trg_lang: str | None = None,
        src_content: str | None = None,
    ) -> Any:
        """获取内容翻译数据/Get content translation data

        ``POST /api/v1/tiktok/app/v3/fetch_content_translate``
        """
        json_body = _drop_none({
            "trg_lang": trg_lang,
            "src_content": src_content,
        })
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_content_translate", json=json_body)

    async def fetch_home_feed(
        self,
        *,
        cookie: str | None = None,
    ) -> Any:
        """获取主页视频推荐数据/Get home feed(recommend) video data

        ``POST /api/v1/tiktok/app/v3/fetch_home_feed``
        """
        json_body = _drop_none({
            "cookie": cookie,
        })
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/fetch_home_feed", json=json_body)

    async def TTencrypt_algorithm(
        self,
        *,
        url: str | None = None,
        data: str | None = None,
        device_info: dict[str, Any] | None = None,
    ) -> Any:
        """TikTok APP加密算法/TikTok APP encryption algorithm

        ``POST /api/v1/tiktok/app/v3/TTencrypt_algorithm``
        """
        json_body = _drop_none({
            "url": url,
            "data": data,
            "device_info": device_info,
        })
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/TTencrypt_algorithm", json=json_body)

    async def fetch_live_room_product_list(
        self,
        *,
        room_id: str,
        author_id: str,
        page_size: int | None = None,
        offset: int | None = None,
        region: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播间商品列表数据/Get live room product list data

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_product_list``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "page_size": page_size,
            "offset": offset,
            "region": region,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_product_list", params=params)

    async def fetch_live_room_product_list_v2(
        self,
        *,
        room_id: str,
        author_id: str,
        page_size: int | None = None,
        offset: int | None = None,
        region: str | None = None,
        cookie: str | None = None,
    ) -> Any:
        """获取直播间商品列表数据 V2 /Get live room product list data V2

        ``GET /api/v1/tiktok/app/v3/fetch_live_room_product_list_v2``
        """
        params = _drop_none({
            "room_id": room_id,
            "author_id": author_id,
            "page_size": page_size,
            "offset": offset,
            "region": region,
            "cookie": cookie,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/fetch_live_room_product_list_v2", params=params)

    async def add_video_play_count(
        self,
        *,
        aweme_type: int,
        item_id: str,
    ) -> Any:
        """根据视频ID来增加作品的播放数/Increase the number of plays of the work according to the video ID

        ``GET /api/v1/tiktok/app/v3/add_video_play_count``
        """
        params = _drop_none({
            "aweme_type": aweme_type,
            "item_id": item_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/add_video_play_count", params=params)

    async def encrypt_decrypt_login_request(
        self,
        *,
        username: str | None = None,
        password: str | None = None,
        mode: Any | None = None,
    ) -> Any:
        """加密或解密 TikTok APP 登录请求体/Encrypt or Decrypt TikTok APP login request body

        ``POST /api/v1/tiktok/app/v3/encrypt_decrypt_login_request``
        """
        json_body = _drop_none({
            "username": username,
            "password": password,
            "mode": mode,
        })
        return await self._client._request("POST", "/api/v1/tiktok/app/v3/encrypt_decrypt_login_request", json=json_body)

    async def open_tiktok_app_to_video_detail(
        self,
        *,
        aweme_id: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定作品详情页/Generate TikTok share link, call TikTok APP, and jump to the specified video details page

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_video_detail``
        """
        params = _drop_none({
            "aweme_id": aweme_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_video_detail", params=params)

    async def open_tiktok_app_to_user_profile(
        self,
        *,
        uid: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定用户主页/Generate TikTok share link, call TikTok APP, and jump to the specified user profile

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_user_profile``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_user_profile", params=params)

    async def open_tiktok_app_to_keyword_search(
        self,
        *,
        keyword: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，跳转指定关键词搜索结果/Generate TikTok share link, call TikTok APP, and jump to the specified keyword search result

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_keyword_search``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_keyword_search", params=params)

    async def open_tiktok_app_to_send_private_message(
        self,
        *,
        uid: str,
    ) -> Any:
        """生成TikTok分享链接，唤起TikTok APP，给指定用户发送私信/Generate TikTok share link, call TikTok APP, and send private messages to specified users

        ``GET /api/v1/tiktok/app/v3/open_tiktok_app_to_send_private_message``
        """
        params = _drop_none({
            "uid": uid,
        })
        return await self._client._request("GET", "/api/v1/tiktok/app/v3/open_tiktok_app_to_send_private_message", params=params)
