# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikTok-Analytics-API resource.

OpenAPI tag: ``TikTok-Analytics-API``
SDK attribute: ``client.tiktok_analytics`` / ``async_client.tiktok_analytics``

Endpoints: 4
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTiktokAnalytics", "TiktokAnalytics"]


class TiktokAnalytics(SyncResource):
    """Sync ``TikTok-Analytics-API`` resource (4 endpoints)."""

    def fetch_video_metrics(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取作品的统计数据/Get video metrics

        ``GET /api/v1/tiktok/analytics/fetch_video_metrics``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/analytics/fetch_video_metrics", params=params)

    def detect_fake_views(
        self,
        *,
        item_id: str,
        content_category: str | None = None,
    ) -> Any:
        """检测视频虚假流量分析/Detect fake views in video

        ``GET /api/v1/tiktok/analytics/detect_fake_views``
        """
        params = _drop_none({
            "item_id": item_id,
            "content_category": content_category,
        })
        return self._client._request("GET", "/api/v1/tiktok/analytics/detect_fake_views", params=params)

    def fetch_comment_keywords(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取视频评论关键词分析/Get comment keywords analysis

        ``GET /api/v1/tiktok/analytics/fetch_comment_keywords``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/analytics/fetch_comment_keywords", params=params)

    def fetch_creator_info_and_milestones(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取创作者信息和里程碑数据/Get creator info and milestones

        ``GET /api/v1/tiktok/analytics/fetch_creator_info_and_milestones``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/analytics/fetch_creator_info_and_milestones", params=params)


class AsyncTiktokAnalytics(AsyncResource):
    """Async ``TikTok-Analytics-API`` resource (4 endpoints)."""

    async def fetch_video_metrics(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取作品的统计数据/Get video metrics

        ``GET /api/v1/tiktok/analytics/fetch_video_metrics``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/analytics/fetch_video_metrics", params=params)

    async def detect_fake_views(
        self,
        *,
        item_id: str,
        content_category: str | None = None,
    ) -> Any:
        """检测视频虚假流量分析/Detect fake views in video

        ``GET /api/v1/tiktok/analytics/detect_fake_views``
        """
        params = _drop_none({
            "item_id": item_id,
            "content_category": content_category,
        })
        return await self._client._request("GET", "/api/v1/tiktok/analytics/detect_fake_views", params=params)

    async def fetch_comment_keywords(
        self,
        *,
        item_id: str,
    ) -> Any:
        """获取视频评论关键词分析/Get comment keywords analysis

        ``GET /api/v1/tiktok/analytics/fetch_comment_keywords``
        """
        params = _drop_none({
            "item_id": item_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/analytics/fetch_comment_keywords", params=params)

    async def fetch_creator_info_and_milestones(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取创作者信息和里程碑数据/Get creator info and milestones

        ``GET /api/v1/tiktok/analytics/fetch_creator_info_and_milestones``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/analytics/fetch_creator_info_and_milestones", params=params)
