# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikTok-Interaction-API resource.

OpenAPI tag: ``TikTok-Interaction-API``
SDK attribute: ``client.tiktok_interaction`` / ``async_client.tiktok_interaction``

Endpoints: 7
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTiktokInteraction", "TiktokInteraction"]


class TiktokInteraction(SyncResource):
    """Sync ``TikTok-Interaction-API`` resource (7 endpoints)."""

    def apply(
        self,
        *,
        api_key: str,
        invite_code: str,
    ) -> Any:
        """申请使用TikTok交互API权限（Scope）/Apply for TikTok Interaction API permission (Scope)

        ``GET /api/v1/tiktok/interaction/apply``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "api_key": api_key,
            "invite_code": invite_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/interaction/apply", params=params)

    def post_comment(
        self,
        *,
        aweme_id: str | None = None,
        text: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """发送评论/Post comment

        ``POST /api/v1/tiktok/interaction/post_comment``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "text": text,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/post_comment", json=json_body)

    def reply_comment(
        self,
        *,
        aweme_id: str | None = None,
        reply_id: str | None = None,
        text: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """回复评论/Reply to comment

        ``POST /api/v1/tiktok/interaction/reply_comment``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "reply_id": reply_id,
            "text": text,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/reply_comment", json=json_body)

    def like(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """点赞/Like

        ``POST /api/v1/tiktok/interaction/like``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/like", json=json_body)

    def follow(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """关注/Follow

        ``POST /api/v1/tiktok/interaction/follow``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/follow", json=json_body)

    def collect(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """收藏/Collect

        ``POST /api/v1/tiktok/interaction/collect``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/collect", json=json_body)

    def forward(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """转发/Forward

        ``POST /api/v1/tiktok/interaction/forward``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return self._client._request("POST", "/api/v1/tiktok/interaction/forward", json=json_body)


class AsyncTiktokInteraction(AsyncResource):
    """Async ``TikTok-Interaction-API`` resource (7 endpoints)."""

    async def apply(
        self,
        *,
        api_key: str,
        invite_code: str,
    ) -> Any:
        """申请使用TikTok交互API权限（Scope）/Apply for TikTok Interaction API permission (Scope)

        ``GET /api/v1/tiktok/interaction/apply``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        params = _drop_none({
            "api_key": api_key,
            "invite_code": invite_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/interaction/apply", params=params)

    async def post_comment(
        self,
        *,
        aweme_id: str | None = None,
        text: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """发送评论/Post comment

        ``POST /api/v1/tiktok/interaction/post_comment``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "text": text,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/post_comment", json=json_body)

    async def reply_comment(
        self,
        *,
        aweme_id: str | None = None,
        reply_id: str | None = None,
        text: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """回复评论/Reply to comment

        ``POST /api/v1/tiktok/interaction/reply_comment``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "reply_id": reply_id,
            "text": text,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/reply_comment", json=json_body)

    async def like(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """点赞/Like

        ``POST /api/v1/tiktok/interaction/like``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/like", json=json_body)

    async def follow(
        self,
        *,
        user_id: str | None = None,
        sec_user_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """关注/Follow

        ``POST /api/v1/tiktok/interaction/follow``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "user_id": user_id,
            "sec_user_id": sec_user_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/follow", json=json_body)

    async def collect(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """收藏/Collect

        ``POST /api/v1/tiktok/interaction/collect``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/collect", json=json_body)

    async def forward(
        self,
        *,
        aweme_id: str | None = None,
        cookie: str | None = None,
        device_id: str | None = None,
        iid: str | None = None,
        proxy: str | None = None,
    ) -> Any:
        """转发/Forward

        ``POST /api/v1/tiktok/interaction/forward``

        .. deprecated:: this endpoint is marked deprecated upstream.
        """
        json_body = _drop_none({
            "aweme_id": aweme_id,
            "cookie": cookie,
            "device_id": device_id,
            "iid": iid,
            "proxy": proxy,
        })
        return await self._client._request("POST", "/api/v1/tiktok/interaction/forward", json=json_body)
