# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""TikTok-Ads-API resource.

OpenAPI tag: ``TikTok-Ads-API``
SDK attribute: ``client.tiktok_ads`` / ``async_client.tiktok_ads``

Endpoints: 31
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncTiktokAds", "TiktokAds"]


class TiktokAds(SyncResource):
    """Sync ``TikTok-Ads-API`` resource (31 endpoints)."""

    def get_ads_detail(
        self,
        *,
        ads_id: str,
    ) -> Any:
        """获取单个广告详情/Get single ad detail

        ``GET /api/v1/tiktok/ads/get_ads_detail``
        """
        params = _drop_none({
            "ads_id": ads_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_ads_detail", params=params)

    def search_ads(
        self,
        *,
        objective: int | None = None,
        like: int | None = None,
        period: int | None = None,
        industry: str | None = None,
        keyword: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
        ad_format: int | None = None,
        ad_language: str | None = None,
        search_id: str | None = None,
    ) -> Any:
        """搜索广告/Search ads

        ``GET /api/v1/tiktok/ads/search_ads``
        """
        params = _drop_none({
            "objective": objective,
            "like": like,
            "period": period,
            "industry": industry,
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "order_by": order_by,
            "country_code": country_code,
            "ad_format": ad_format,
            "ad_language": ad_language,
            "search_id": search_id,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/search_ads", params=params)

    def get_keyword_insights(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
        industry: str | None = None,
        objective: str | None = None,
        keyword_type: str | None = None,
        keyword: str | None = None,
    ) -> Any:
        """获取关键词洞察数据/Get keyword insights data

        ``GET /api/v1/tiktok/ads/get_keyword_insights``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "order_by": order_by,
            "order_type": order_type,
            "industry": industry,
            "objective": objective,
            "keyword_type": keyword_type,
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_insights", params=params)

    def get_top_products(
        self,
        *,
        last: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        country_code: str | None = None,
        first_ecom_category_id: str | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
    ) -> Any:
        """获取热门产品列表/Get top products list

        ``GET /api/v1/tiktok/ads/get_top_products``
        """
        params = _drop_none({
            "last": last,
            "page": page,
            "limit": limit,
            "country_code": country_code,
            "first_ecom_category_id": first_ecom_category_id,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "order_by": order_by,
            "order_type": order_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_top_products", params=params)

    def get_hashtag_list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        sort_by: str | None = None,
        industry_id: str | None = None,
        filter_by: str | None = None,
    ) -> Any:
        """获取热门标签列表/Get popular hashtags list

        ``GET /api/v1/tiktok/ads/get_hashtag_list``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "sort_by": sort_by,
            "industry_id": industry_id,
            "filter_by": filter_by,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_list", params=params)

    def get_sound_rank_list(
        self,
        *,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        new_on_board: bool | None = None,
        commercial_music: bool | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取热门音乐排行榜/Get popular sound rankings

        ``GET /api/v1/tiktok/ads/get_sound_rank_list``
        """
        params = _drop_none({
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "new_on_board": new_on_board,
            "commercial_music": commercial_music,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_sound_rank_list", params=params)

    def get_keyword_list(
        self,
        *,
        keyword: str | None = None,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        country_code: str | None = None,
        industry: str | None = None,
    ) -> Any:
        """获取关键词列表/Get keyword list

        ``GET /api/v1/tiktok/ads/get_keyword_list``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "country_code": country_code,
            "industry": industry,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_list", params=params)

    def get_top_ads_spotlight(
        self,
        *,
        industry: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取热门广告聚光灯/Get top ads spotlight

        ``GET /api/v1/tiktok/ads/get_top_ads_spotlight``
        """
        params = _drop_none({
            "industry": industry,
            "page": page,
            "limit": limit,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_top_ads_spotlight", params=params)

    def get_ad_keyframe_analysis(
        self,
        *,
        material_id: str,
        metric: str | None = None,
    ) -> Any:
        """获取广告关键帧分析/Get ad keyframe analysis

        ``GET /api/v1/tiktok/ads/get_ad_keyframe_analysis``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric": metric,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_ad_keyframe_analysis", params=params)

    def get_ad_percentile(
        self,
        *,
        material_id: str,
        metric: str | None = None,
        period_type: int | None = None,
    ) -> Any:
        """获取广告百分位数据/Get ad percentile data

        ``GET /api/v1/tiktok/ads/get_ad_percentile``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric": metric,
            "period_type": period_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_ad_percentile", params=params)

    def get_ad_interactive_analysis(
        self,
        *,
        material_id: str,
        metric_type: str | None = None,
        period_type: int | None = None,
    ) -> Any:
        """获取广告互动分析/Get ad interactive analysis

        ``GET /api/v1/tiktok/ads/get_ad_interactive_analysis``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric_type": metric_type,
            "period_type": period_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_ad_interactive_analysis", params=params)

    def get_recommended_ads(
        self,
        *,
        material_id: str,
        industry: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取推荐广告/Get recommended ads

        ``GET /api/v1/tiktok/ads/get_recommended_ads``
        """
        params = _drop_none({
            "material_id": material_id,
            "industry": industry,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_recommended_ads", params=params)

    def get_query_suggestions(
        self,
        *,
        count: int | None = None,
        scenario: int | None = None,
    ) -> Any:
        """获取查询建议/Get query suggestions

        ``GET /api/v1/tiktok/ads/get_query_suggestions``
        """
        params = _drop_none({
            "count": count,
            "scenario": scenario,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_query_suggestions", params=params)

    def get_keyword_filters(
        self,
    ) -> Any:
        """获取关键词筛选器/Get keyword filters

        ``GET /api/v1/tiktok/ads/get_keyword_filters``
        """
        return self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_filters")

    def get_related_keywords(
        self,
        *,
        keyword: str | None = None,
        period: int | None = None,
        country_code: str | None = None,
        rank_type: str | None = None,
        content_type: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取相关关键词/Get related keywords

        ``GET /api/v1/tiktok/ads/get_related_keywords``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "country_code": country_code,
            "rank_type": rank_type,
            "content_type": content_type,
            "page": page,
            "limit": limit,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_related_keywords", params=params)

    def get_keyword_details(
        self,
        *,
        keyword: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
        industry: str | None = None,
        objective: str | None = None,
        keyword_type: str | None = None,
    ) -> Any:
        """获取关键词详细信息/Get keyword details

        ``GET /api/v1/tiktok/ads/get_keyword_details``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "order_by": order_by,
            "order_type": order_type,
            "industry": industry,
            "objective": objective,
            "keyword_type": keyword_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_details", params=params)

    def get_creative_patterns(
        self,
        *,
        first_industry_id: str | None = None,
        period_type: str | None = None,
        order_field: str | None = None,
        order_type: str | None = None,
        week: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取创意模式排行榜/Get creative pattern rankings

        ``GET /api/v1/tiktok/ads/get_creative_patterns``
        """
        params = _drop_none({
            "first_industry_id": first_industry_id,
            "period_type": period_type,
            "order_field": order_field,
            "order_type": order_type,
            "week": week,
            "page": page,
            "limit": limit,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_creative_patterns", params=params)

    def get_product_filters(
        self,
    ) -> Any:
        """获取产品筛选器/Get product filters

        ``GET /api/v1/tiktok/ads/get_product_filters``
        """
        return self._client._request("GET", "/api/v1/tiktok/ads/get_product_filters")

    def get_product_metrics(
        self,
        *,
        id: str,
        last: int | None = None,
        metrics: str | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取产品指标数据/Get product metrics

        ``GET /api/v1/tiktok/ads/get_product_metrics``
        """
        params = _drop_none({
            "id": id,
            "last": last,
            "metrics": metrics,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_product_metrics", params=params)

    def get_product_detail(
        self,
        *,
        id: str,
        last: int | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取产品详细信息/Get product detail

        ``GET /api/v1/tiktok/ads/get_product_detail``
        """
        params = _drop_none({
            "id": id,
            "last": last,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_product_detail", params=params)

    def get_hashtag_filters(
        self,
    ) -> Any:
        """获取标签筛选器/Get hashtag filters

        ``GET /api/v1/tiktok/ads/get_hashtag_filters``
        """
        return self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_filters")

    def get_hashtag_creator(
        self,
        *,
        hashtag: str,
    ) -> Any:
        """获取标签创作者信息/Get hashtag creator info

        ``GET /api/v1/tiktok/ads/get_hashtag_creator``
        """
        params = _drop_none({
            "hashtag": hashtag,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_creator", params=params)

    def get_sound_filters(
        self,
        *,
        rank_type: str | None = None,
    ) -> Any:
        """获取音乐筛选器/Get sound filters

        ``GET /api/v1/tiktok/ads/get_sound_filters``
        """
        params = _drop_none({
            "rank_type": rank_type,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_sound_filters", params=params)

    def get_sound_detail(
        self,
        *,
        clip_id: str,
        period: int | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取音乐详情/Get sound detail

        ``GET /api/v1/tiktok/ads/get_sound_detail``
        """
        params = _drop_none({
            "clip_id": clip_id,
            "period": period,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_sound_detail", params=params)

    def search_sound_hint(
        self,
        *,
        keyword: str,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        country_code: str | None = None,
        filter_by_checked: bool | None = None,
        commercial_music: bool | None = None,
    ) -> Any:
        """搜索音乐提示/Search sound hints

        ``GET /api/v1/tiktok/ads/search_sound_hint``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "country_code": country_code,
            "filter_by_checked": filter_by_checked,
            "commercial_music": commercial_music,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/search_sound_hint", params=params)

    def search_sound(
        self,
        *,
        keyword: str,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        new_on_board: bool | None = None,
        commercial_music: bool | None = None,
        country_code: str | None = None,
    ) -> Any:
        """搜索音乐/Search sounds

        ``GET /api/v1/tiktok/ads/search_sound``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "new_on_board": new_on_board,
            "commercial_music": commercial_music,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/search_sound", params=params)

    def get_sound_recommendations(
        self,
        *,
        clip_id: str,
        limit: int | None = None,
    ) -> Any:
        """获取音乐推荐/Get sound recommendations

        ``GET /api/v1/tiktok/ads/get_sound_recommendations``
        """
        params = _drop_none({
            "clip_id": clip_id,
            "limit": limit,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_sound_recommendations", params=params)

    def get_creator_filters(
        self,
    ) -> Any:
        """获取创作者筛选器/Get creator filters

        ``GET /api/v1/tiktok/ads/get_creator_filters``
        """
        return self._client._request("GET", "/api/v1/tiktok/ads/get_creator_filters")

    def get_creator_list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort_by: str | None = None,
        creator_country: str | None = None,
        audience_country: str | None = None,
        audience_count: int | None = None,
        keyword: str | None = None,
    ) -> Any:
        """获取创作者列表/Get creator list

        ``GET /api/v1/tiktok/ads/get_creator_list``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "sort_by": sort_by,
            "creator_country": creator_country,
            "audience_country": audience_country,
            "audience_count": audience_count,
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_creator_list", params=params)

    def search_creators(
        self,
        *,
        keyword: str,
        page: int | None = None,
        limit: int | None = None,
        sort_by: str | None = None,
        creator_country: str | None = None,
    ) -> Any:
        """搜索创作者/Search creators

        ``GET /api/v1/tiktok/ads/search_creators``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "sort_by": sort_by,
            "creator_country": creator_country,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/search_creators", params=params)

    def get_popular_trends(
        self,
        *,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取流行趋势视频/Get popular trend videos

        ``GET /api/v1/tiktok/ads/get_popular_trends``
        """
        params = _drop_none({
            "period": period,
            "page": page,
            "limit": limit,
            "order_by": order_by,
            "country_code": country_code,
        })
        return self._client._request("GET", "/api/v1/tiktok/ads/get_popular_trends", params=params)


class AsyncTiktokAds(AsyncResource):
    """Async ``TikTok-Ads-API`` resource (31 endpoints)."""

    async def get_ads_detail(
        self,
        *,
        ads_id: str,
    ) -> Any:
        """获取单个广告详情/Get single ad detail

        ``GET /api/v1/tiktok/ads/get_ads_detail``
        """
        params = _drop_none({
            "ads_id": ads_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_ads_detail", params=params)

    async def search_ads(
        self,
        *,
        objective: int | None = None,
        like: int | None = None,
        period: int | None = None,
        industry: str | None = None,
        keyword: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
        ad_format: int | None = None,
        ad_language: str | None = None,
        search_id: str | None = None,
    ) -> Any:
        """搜索广告/Search ads

        ``GET /api/v1/tiktok/ads/search_ads``
        """
        params = _drop_none({
            "objective": objective,
            "like": like,
            "period": period,
            "industry": industry,
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "order_by": order_by,
            "country_code": country_code,
            "ad_format": ad_format,
            "ad_language": ad_language,
            "search_id": search_id,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/search_ads", params=params)

    async def get_keyword_insights(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
        industry: str | None = None,
        objective: str | None = None,
        keyword_type: str | None = None,
        keyword: str | None = None,
    ) -> Any:
        """获取关键词洞察数据/Get keyword insights data

        ``GET /api/v1/tiktok/ads/get_keyword_insights``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "order_by": order_by,
            "order_type": order_type,
            "industry": industry,
            "objective": objective,
            "keyword_type": keyword_type,
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_insights", params=params)

    async def get_top_products(
        self,
        *,
        last: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        country_code: str | None = None,
        first_ecom_category_id: str | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
    ) -> Any:
        """获取热门产品列表/Get top products list

        ``GET /api/v1/tiktok/ads/get_top_products``
        """
        params = _drop_none({
            "last": last,
            "page": page,
            "limit": limit,
            "country_code": country_code,
            "first_ecom_category_id": first_ecom_category_id,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "order_by": order_by,
            "order_type": order_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_top_products", params=params)

    async def get_hashtag_list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        sort_by: str | None = None,
        industry_id: str | None = None,
        filter_by: str | None = None,
    ) -> Any:
        """获取热门标签列表/Get popular hashtags list

        ``GET /api/v1/tiktok/ads/get_hashtag_list``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "sort_by": sort_by,
            "industry_id": industry_id,
            "filter_by": filter_by,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_list", params=params)

    async def get_sound_rank_list(
        self,
        *,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        new_on_board: bool | None = None,
        commercial_music: bool | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取热门音乐排行榜/Get popular sound rankings

        ``GET /api/v1/tiktok/ads/get_sound_rank_list``
        """
        params = _drop_none({
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "new_on_board": new_on_board,
            "commercial_music": commercial_music,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_sound_rank_list", params=params)

    async def get_keyword_list(
        self,
        *,
        keyword: str | None = None,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        country_code: str | None = None,
        industry: str | None = None,
    ) -> Any:
        """获取关键词列表/Get keyword list

        ``GET /api/v1/tiktok/ads/get_keyword_list``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "country_code": country_code,
            "industry": industry,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_list", params=params)

    async def get_top_ads_spotlight(
        self,
        *,
        industry: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取热门广告聚光灯/Get top ads spotlight

        ``GET /api/v1/tiktok/ads/get_top_ads_spotlight``
        """
        params = _drop_none({
            "industry": industry,
            "page": page,
            "limit": limit,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_top_ads_spotlight", params=params)

    async def get_ad_keyframe_analysis(
        self,
        *,
        material_id: str,
        metric: str | None = None,
    ) -> Any:
        """获取广告关键帧分析/Get ad keyframe analysis

        ``GET /api/v1/tiktok/ads/get_ad_keyframe_analysis``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric": metric,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_ad_keyframe_analysis", params=params)

    async def get_ad_percentile(
        self,
        *,
        material_id: str,
        metric: str | None = None,
        period_type: int | None = None,
    ) -> Any:
        """获取广告百分位数据/Get ad percentile data

        ``GET /api/v1/tiktok/ads/get_ad_percentile``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric": metric,
            "period_type": period_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_ad_percentile", params=params)

    async def get_ad_interactive_analysis(
        self,
        *,
        material_id: str,
        metric_type: str | None = None,
        period_type: int | None = None,
    ) -> Any:
        """获取广告互动分析/Get ad interactive analysis

        ``GET /api/v1/tiktok/ads/get_ad_interactive_analysis``
        """
        params = _drop_none({
            "material_id": material_id,
            "metric_type": metric_type,
            "period_type": period_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_ad_interactive_analysis", params=params)

    async def get_recommended_ads(
        self,
        *,
        material_id: str,
        industry: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取推荐广告/Get recommended ads

        ``GET /api/v1/tiktok/ads/get_recommended_ads``
        """
        params = _drop_none({
            "material_id": material_id,
            "industry": industry,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_recommended_ads", params=params)

    async def get_query_suggestions(
        self,
        *,
        count: int | None = None,
        scenario: int | None = None,
    ) -> Any:
        """获取查询建议/Get query suggestions

        ``GET /api/v1/tiktok/ads/get_query_suggestions``
        """
        params = _drop_none({
            "count": count,
            "scenario": scenario,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_query_suggestions", params=params)

    async def get_keyword_filters(
        self,
    ) -> Any:
        """获取关键词筛选器/Get keyword filters

        ``GET /api/v1/tiktok/ads/get_keyword_filters``
        """
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_filters")

    async def get_related_keywords(
        self,
        *,
        keyword: str | None = None,
        period: int | None = None,
        country_code: str | None = None,
        rank_type: str | None = None,
        content_type: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取相关关键词/Get related keywords

        ``GET /api/v1/tiktok/ads/get_related_keywords``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "country_code": country_code,
            "rank_type": rank_type,
            "content_type": content_type,
            "page": page,
            "limit": limit,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_related_keywords", params=params)

    async def get_keyword_details(
        self,
        *,
        keyword: str | None = None,
        page: int | None = None,
        limit: int | None = None,
        period: int | None = None,
        country_code: str | None = None,
        order_by: str | None = None,
        order_type: str | None = None,
        industry: str | None = None,
        objective: str | None = None,
        keyword_type: str | None = None,
    ) -> Any:
        """获取关键词详细信息/Get keyword details

        ``GET /api/v1/tiktok/ads/get_keyword_details``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "period": period,
            "country_code": country_code,
            "order_by": order_by,
            "order_type": order_type,
            "industry": industry,
            "objective": objective,
            "keyword_type": keyword_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_keyword_details", params=params)

    async def get_creative_patterns(
        self,
        *,
        first_industry_id: str | None = None,
        period_type: str | None = None,
        order_field: str | None = None,
        order_type: str | None = None,
        week: str | None = None,
        page: int | None = None,
        limit: int | None = None,
    ) -> Any:
        """获取创意模式排行榜/Get creative pattern rankings

        ``GET /api/v1/tiktok/ads/get_creative_patterns``
        """
        params = _drop_none({
            "first_industry_id": first_industry_id,
            "period_type": period_type,
            "order_field": order_field,
            "order_type": order_type,
            "week": week,
            "page": page,
            "limit": limit,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_creative_patterns", params=params)

    async def get_product_filters(
        self,
    ) -> Any:
        """获取产品筛选器/Get product filters

        ``GET /api/v1/tiktok/ads/get_product_filters``
        """
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_product_filters")

    async def get_product_metrics(
        self,
        *,
        id: str,
        last: int | None = None,
        metrics: str | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取产品指标数据/Get product metrics

        ``GET /api/v1/tiktok/ads/get_product_metrics``
        """
        params = _drop_none({
            "id": id,
            "last": last,
            "metrics": metrics,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_product_metrics", params=params)

    async def get_product_detail(
        self,
        *,
        id: str,
        last: int | None = None,
        ecom_type: str | None = None,
        period_type: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取产品详细信息/Get product detail

        ``GET /api/v1/tiktok/ads/get_product_detail``
        """
        params = _drop_none({
            "id": id,
            "last": last,
            "ecom_type": ecom_type,
            "period_type": period_type,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_product_detail", params=params)

    async def get_hashtag_filters(
        self,
    ) -> Any:
        """获取标签筛选器/Get hashtag filters

        ``GET /api/v1/tiktok/ads/get_hashtag_filters``
        """
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_filters")

    async def get_hashtag_creator(
        self,
        *,
        hashtag: str,
    ) -> Any:
        """获取标签创作者信息/Get hashtag creator info

        ``GET /api/v1/tiktok/ads/get_hashtag_creator``
        """
        params = _drop_none({
            "hashtag": hashtag,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_hashtag_creator", params=params)

    async def get_sound_filters(
        self,
        *,
        rank_type: str | None = None,
    ) -> Any:
        """获取音乐筛选器/Get sound filters

        ``GET /api/v1/tiktok/ads/get_sound_filters``
        """
        params = _drop_none({
            "rank_type": rank_type,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_sound_filters", params=params)

    async def get_sound_detail(
        self,
        *,
        clip_id: str,
        period: int | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取音乐详情/Get sound detail

        ``GET /api/v1/tiktok/ads/get_sound_detail``
        """
        params = _drop_none({
            "clip_id": clip_id,
            "period": period,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_sound_detail", params=params)

    async def search_sound_hint(
        self,
        *,
        keyword: str,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        country_code: str | None = None,
        filter_by_checked: bool | None = None,
        commercial_music: bool | None = None,
    ) -> Any:
        """搜索音乐提示/Search sound hints

        ``GET /api/v1/tiktok/ads/search_sound_hint``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "country_code": country_code,
            "filter_by_checked": filter_by_checked,
            "commercial_music": commercial_music,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/search_sound_hint", params=params)

    async def search_sound(
        self,
        *,
        keyword: str,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        rank_type: str | None = None,
        new_on_board: bool | None = None,
        commercial_music: bool | None = None,
        country_code: str | None = None,
    ) -> Any:
        """搜索音乐/Search sounds

        ``GET /api/v1/tiktok/ads/search_sound``
        """
        params = _drop_none({
            "keyword": keyword,
            "period": period,
            "page": page,
            "limit": limit,
            "rank_type": rank_type,
            "new_on_board": new_on_board,
            "commercial_music": commercial_music,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/search_sound", params=params)

    async def get_sound_recommendations(
        self,
        *,
        clip_id: str,
        limit: int | None = None,
    ) -> Any:
        """获取音乐推荐/Get sound recommendations

        ``GET /api/v1/tiktok/ads/get_sound_recommendations``
        """
        params = _drop_none({
            "clip_id": clip_id,
            "limit": limit,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_sound_recommendations", params=params)

    async def get_creator_filters(
        self,
    ) -> Any:
        """获取创作者筛选器/Get creator filters

        ``GET /api/v1/tiktok/ads/get_creator_filters``
        """
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_creator_filters")

    async def get_creator_list(
        self,
        *,
        page: int | None = None,
        limit: int | None = None,
        sort_by: str | None = None,
        creator_country: str | None = None,
        audience_country: str | None = None,
        audience_count: int | None = None,
        keyword: str | None = None,
    ) -> Any:
        """获取创作者列表/Get creator list

        ``GET /api/v1/tiktok/ads/get_creator_list``
        """
        params = _drop_none({
            "page": page,
            "limit": limit,
            "sort_by": sort_by,
            "creator_country": creator_country,
            "audience_country": audience_country,
            "audience_count": audience_count,
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_creator_list", params=params)

    async def search_creators(
        self,
        *,
        keyword: str,
        page: int | None = None,
        limit: int | None = None,
        sort_by: str | None = None,
        creator_country: str | None = None,
    ) -> Any:
        """搜索创作者/Search creators

        ``GET /api/v1/tiktok/ads/search_creators``
        """
        params = _drop_none({
            "keyword": keyword,
            "page": page,
            "limit": limit,
            "sort_by": sort_by,
            "creator_country": creator_country,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/search_creators", params=params)

    async def get_popular_trends(
        self,
        *,
        period: int | None = None,
        page: int | None = None,
        limit: int | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
    ) -> Any:
        """获取流行趋势视频/Get popular trend videos

        ``GET /api/v1/tiktok/ads/get_popular_trends``
        """
        params = _drop_none({
            "period": period,
            "page": page,
            "limit": limit,
            "order_by": order_by,
            "country_code": country_code,
        })
        return await self._client._request("GET", "/api/v1/tiktok/ads/get_popular_trends", params=params)
