# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""WeChat-Channels-V2-API resource.

OpenAPI tag: ``WeChat-Channels-V2-API``
SDK attribute: ``client.wechat_channels_v2`` / ``async_client.wechat_channels_v2``

Endpoints: 12
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncWechatChannelsV2", "WechatChannelsV2"]


class WechatChannelsV2(SyncResource):
    """Sync ``WeChat-Channels-V2-API`` resource (12 endpoints)."""

    def fetch_channel_info(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号账号信息/Get WeChat Channels Account Info

        ``POST /api/v1/wechat_channels/v2/fetch_channel_info``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_channel_info", json=json_body)

    def fetch_channel_id_to_username(
        self,
        *,
        channel_id: str,
        raw: bool | None = None,
    ) -> Any:
        """视频号ID转finder username/Convert Channel ID to Finder Username

        ``POST /api/v1/wechat_channels/v2/fetch_channel_id_to_username``
        """
        json_body = _drop_none({
            "channel_id": channel_id,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_channel_id_to_username", json=json_body)

    def fetch_user_videos(
        self,
        *,
        username: str,
        last_buffer: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号用户作品列表/Get WeChat Channels User Videos

        ``POST /api/v1/wechat_channels/v2/fetch_user_videos``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_videos", json=json_body)

    def fetch_video_detail(
        self,
        *,
        object_id: Any | None = None,
        export_id: Any | None = None,
        object_nonce_id: Any | None = None,
        share_url: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号作品详情/Get WeChat Channels Video Detail

        ``POST /api/v1/wechat_channels/v2/fetch_video_detail``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "export_id": export_id,
            "object_nonce_id": object_nonce_id,
            "share_url": share_url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_detail", json=json_body)

    def fetch_video_comments(
        self,
        *,
        object_id: str,
        last_buffer: Any | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号作品评论/Get WeChat Channels Video Comments

        ``POST /api/v1/wechat_channels/v2/fetch_video_comments``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "last_buffer": last_buffer,
            "comment_id": comment_id,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_comments", json=json_body)

    def fetch_video_share_url(
        self,
        *,
        object_id: str,
        raw: bool | None = None,
    ) -> Any:
        """生成视频号作品分享链接/Generate WeChat Channels Video Share URL

        ``POST /api/v1/wechat_channels/v2/fetch_video_share_url``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_share_url", json=json_body)

    def fetch_user_profile(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号账号主页资料+统计/Get WeChat Channels User Profile & Stats

        ``POST /api/v1/wechat_channels/v2/fetch_user_profile``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_profile", json=json_body)

    def fetch_user_collections(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号合集列表/Get WeChat Channels User Collections

        ``POST /api/v1/wechat_channels/v2/fetch_user_collections``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_collections", json=json_body)

    def fetch_collection_videos(
        self,
        *,
        topic_id: str,
        topic: Any | None = None,
        username: Any | None = None,
        last_buffer: Any | None = None,
        topic_type: int | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号合集内视频/Get WeChat Channels Collection Videos

        ``POST /api/v1/wechat_channels/v2/fetch_collection_videos``
        """
        json_body = _drop_none({
            "topic_id": topic_id,
            "topic": topic,
            "username": username,
            "last_buffer": last_buffer,
            "topic_type": topic_type,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_collection_videos", json=json_body)

    def fetch_live_history(
        self,
        *,
        username: str,
        last_buffer: Any | None = None,
        flag: int | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号直播回放列表/Get WeChat Channels Live History

        ``POST /api/v1/wechat_channels/v2/fetch_live_history``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
            "flag": flag,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_live_history", json=json_body)

    def fetch_live_detail(
        self,
        *,
        live_id: str,
        scene: int | None = None,
        finder_username: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号直播间详情/Get WeChat Channels Live Detail

        ``POST /api/v1/wechat_channels/v2/fetch_live_detail``
        """
        json_body = _drop_none({
            "live_id": live_id,
            "scene": scene,
            "finder_username": finder_username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_live_detail", json=json_body)

    def fetch_search_channel_videos(
        self,
        *,
        username: str,
        keyword: str,
        cursor: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """视频号号内搜索/Search Videos Within a WeChat Channel

        ``POST /api/v1/wechat_channels/v2/fetch_search_channel_videos``
        """
        json_body = _drop_none({
            "username": username,
            "keyword": keyword,
            "cursor": cursor,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_search_channel_videos", json=json_body)


class AsyncWechatChannelsV2(AsyncResource):
    """Async ``WeChat-Channels-V2-API`` resource (12 endpoints)."""

    async def fetch_channel_info(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号账号信息/Get WeChat Channels Account Info

        ``POST /api/v1/wechat_channels/v2/fetch_channel_info``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_channel_info", json=json_body)

    async def fetch_channel_id_to_username(
        self,
        *,
        channel_id: str,
        raw: bool | None = None,
    ) -> Any:
        """视频号ID转finder username/Convert Channel ID to Finder Username

        ``POST /api/v1/wechat_channels/v2/fetch_channel_id_to_username``
        """
        json_body = _drop_none({
            "channel_id": channel_id,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_channel_id_to_username", json=json_body)

    async def fetch_user_videos(
        self,
        *,
        username: str,
        last_buffer: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号用户作品列表/Get WeChat Channels User Videos

        ``POST /api/v1/wechat_channels/v2/fetch_user_videos``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_videos", json=json_body)

    async def fetch_video_detail(
        self,
        *,
        object_id: Any | None = None,
        export_id: Any | None = None,
        object_nonce_id: Any | None = None,
        share_url: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号作品详情/Get WeChat Channels Video Detail

        ``POST /api/v1/wechat_channels/v2/fetch_video_detail``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "export_id": export_id,
            "object_nonce_id": object_nonce_id,
            "share_url": share_url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_detail", json=json_body)

    async def fetch_video_comments(
        self,
        *,
        object_id: str,
        last_buffer: Any | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号作品评论/Get WeChat Channels Video Comments

        ``POST /api/v1/wechat_channels/v2/fetch_video_comments``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "last_buffer": last_buffer,
            "comment_id": comment_id,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_comments", json=json_body)

    async def fetch_video_share_url(
        self,
        *,
        object_id: str,
        raw: bool | None = None,
    ) -> Any:
        """生成视频号作品分享链接/Generate WeChat Channels Video Share URL

        ``POST /api/v1/wechat_channels/v2/fetch_video_share_url``
        """
        json_body = _drop_none({
            "object_id": object_id,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_video_share_url", json=json_body)

    async def fetch_user_profile(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号账号主页资料+统计/Get WeChat Channels User Profile & Stats

        ``POST /api/v1/wechat_channels/v2/fetch_user_profile``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_profile", json=json_body)

    async def fetch_user_collections(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号合集列表/Get WeChat Channels User Collections

        ``POST /api/v1/wechat_channels/v2/fetch_user_collections``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_user_collections", json=json_body)

    async def fetch_collection_videos(
        self,
        *,
        topic_id: str,
        topic: Any | None = None,
        username: Any | None = None,
        last_buffer: Any | None = None,
        topic_type: int | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号合集内视频/Get WeChat Channels Collection Videos

        ``POST /api/v1/wechat_channels/v2/fetch_collection_videos``
        """
        json_body = _drop_none({
            "topic_id": topic_id,
            "topic": topic,
            "username": username,
            "last_buffer": last_buffer,
            "topic_type": topic_type,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_collection_videos", json=json_body)

    async def fetch_live_history(
        self,
        *,
        username: str,
        last_buffer: Any | None = None,
        flag: int | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号直播回放列表/Get WeChat Channels Live History

        ``POST /api/v1/wechat_channels/v2/fetch_live_history``
        """
        json_body = _drop_none({
            "username": username,
            "last_buffer": last_buffer,
            "flag": flag,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_live_history", json=json_body)

    async def fetch_live_detail(
        self,
        *,
        live_id: str,
        scene: int | None = None,
        finder_username: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取视频号直播间详情/Get WeChat Channels Live Detail

        ``POST /api/v1/wechat_channels/v2/fetch_live_detail``
        """
        json_body = _drop_none({
            "live_id": live_id,
            "scene": scene,
            "finder_username": finder_username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_live_detail", json=json_body)

    async def fetch_search_channel_videos(
        self,
        *,
        username: str,
        keyword: str,
        cursor: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """视频号号内搜索/Search Videos Within a WeChat Channel

        ``POST /api/v1/wechat_channels/v2/fetch_search_channel_videos``
        """
        json_body = _drop_none({
            "username": username,
            "keyword": keyword,
            "cursor": cursor,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_channels/v2/fetch_search_channel_videos", json=json_body)
