# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""WeChat-Media-Platform-V2-API resource.

OpenAPI tag: ``WeChat-Media-Platform-V2-API``
SDK attribute: ``client.wechat_media_platform_v2`` / ``async_client.wechat_media_platform_v2``

Endpoints: 11
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncWechatMediaPlatformV2", "WechatMediaPlatformV2"]


class WechatMediaPlatformV2(SyncResource):
    """Sync ``WeChat-Media-Platform-V2-API`` resource (11 endpoints)."""

    def fetch_article_detail(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章详情/Get WeChat MP Article Detail

        ``POST /api/v1/wechat_mp/v2/fetch_article_detail``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_detail", json=json_body)

    def fetch_article_detail_h5(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章详情（H5 版本，推荐）/Get WeChat MP Article Detail (H5, Recommended)

        ``POST /api/v1/wechat_mp/v2/fetch_article_detail_h5``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_detail_h5", json=json_body)

    def fetch_article_stats_h5(
        self,
        *,
        url: str,
        raw: bool | None = None,
        comment_id: Any | None = None,
    ) -> Any:
        """获取公众号文章互动数据（H5 版本）/Get WeChat MP Article Stats (H5)

        ``POST /api/v1/wechat_mp/v2/fetch_article_stats_h5``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
            "comment_id": comment_id,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_stats_h5", json=json_body)

    def fetch_article_stats(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章互动数据/Get WeChat MP Article Stats

        ``POST /api/v1/wechat_mp/v2/fetch_article_stats``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_stats", json=json_body)

    def fetch_article_comments(
        self,
        *,
        url: str,
        buffer: Any | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章评论/Get WeChat MP Article Comments

        ``POST /api/v1/wechat_mp/v2/fetch_article_comments``
        """
        json_body = _drop_none({
            "url": url,
            "buffer": buffer,
            "comment_id": comment_id,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_comments", json=json_body)

    def fetch_comment_replies(
        self,
        *,
        url: str,
        content_id: Any | None = None,
        offset: int | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号评论的二级回复/Get WeChat MP Comment Replies

        ``POST /api/v1/wechat_mp/v2/fetch_comment_replies``
        """
        json_body = _drop_none({
            "url": url,
            "content_id": content_id,
            "offset": offset,
            "comment_id": comment_id,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_comment_replies", json=json_body)

    def fetch_related_articles(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号关联文章/Get WeChat MP Related Articles

        ``POST /api/v1/wechat_mp/v2/fetch_related_articles``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_related_articles", json=json_body)

    def fetch_article_ad(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章广告/Get WeChat MP Article Ads

        ``POST /api/v1/wechat_mp/v2/fetch_article_ad``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_ad", json=json_body)

    def fetch_account_profile(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号资料页/Get WeChat MP Account Profile

        ``POST /api/v1/wechat_mp/v2/fetch_account_profile``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_profile", json=json_body)

    def fetch_account_articles(
        self,
        *,
        username: str,
        page_size: int | None = None,
        offset: Any | None = None,
        item_show_type: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章列表/Get WeChat MP Account Articles

        ``POST /api/v1/wechat_mp/v2/fetch_account_articles``
        """
        json_body = _drop_none({
            "username": username,
            "page_size": page_size,
            "offset": offset,
            "item_show_type": item_show_type,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_articles", json=json_body)

    def fetch_account_services(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号服务/自定义菜单/Get WeChat MP Account Services & Custom Menu

        ``POST /api/v1/wechat_mp/v2/fetch_account_services``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_services", json=json_body)


class AsyncWechatMediaPlatformV2(AsyncResource):
    """Async ``WeChat-Media-Platform-V2-API`` resource (11 endpoints)."""

    async def fetch_article_detail(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章详情/Get WeChat MP Article Detail

        ``POST /api/v1/wechat_mp/v2/fetch_article_detail``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_detail", json=json_body)

    async def fetch_article_detail_h5(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章详情（H5 版本，推荐）/Get WeChat MP Article Detail (H5, Recommended)

        ``POST /api/v1/wechat_mp/v2/fetch_article_detail_h5``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_detail_h5", json=json_body)

    async def fetch_article_stats_h5(
        self,
        *,
        url: str,
        raw: bool | None = None,
        comment_id: Any | None = None,
    ) -> Any:
        """获取公众号文章互动数据（H5 版本）/Get WeChat MP Article Stats (H5)

        ``POST /api/v1/wechat_mp/v2/fetch_article_stats_h5``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
            "comment_id": comment_id,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_stats_h5", json=json_body)

    async def fetch_article_stats(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章互动数据/Get WeChat MP Article Stats

        ``POST /api/v1/wechat_mp/v2/fetch_article_stats``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_stats", json=json_body)

    async def fetch_article_comments(
        self,
        *,
        url: str,
        buffer: Any | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章评论/Get WeChat MP Article Comments

        ``POST /api/v1/wechat_mp/v2/fetch_article_comments``
        """
        json_body = _drop_none({
            "url": url,
            "buffer": buffer,
            "comment_id": comment_id,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_comments", json=json_body)

    async def fetch_comment_replies(
        self,
        *,
        url: str,
        content_id: Any | None = None,
        offset: int | None = None,
        comment_id: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号评论的二级回复/Get WeChat MP Comment Replies

        ``POST /api/v1/wechat_mp/v2/fetch_comment_replies``
        """
        json_body = _drop_none({
            "url": url,
            "content_id": content_id,
            "offset": offset,
            "comment_id": comment_id,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_comment_replies", json=json_body)

    async def fetch_related_articles(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号关联文章/Get WeChat MP Related Articles

        ``POST /api/v1/wechat_mp/v2/fetch_related_articles``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_related_articles", json=json_body)

    async def fetch_article_ad(
        self,
        *,
        url: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章广告/Get WeChat MP Article Ads

        ``POST /api/v1/wechat_mp/v2/fetch_article_ad``
        """
        json_body = _drop_none({
            "url": url,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_article_ad", json=json_body)

    async def fetch_account_profile(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号资料页/Get WeChat MP Account Profile

        ``POST /api/v1/wechat_mp/v2/fetch_account_profile``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_profile", json=json_body)

    async def fetch_account_articles(
        self,
        *,
        username: str,
        page_size: int | None = None,
        offset: Any | None = None,
        item_show_type: Any | None = None,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号文章列表/Get WeChat MP Account Articles

        ``POST /api/v1/wechat_mp/v2/fetch_account_articles``
        """
        json_body = _drop_none({
            "username": username,
            "page_size": page_size,
            "offset": offset,
            "item_show_type": item_show_type,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_articles", json=json_body)

    async def fetch_account_services(
        self,
        *,
        username: str,
        raw: bool | None = None,
    ) -> Any:
        """获取公众号服务/自定义菜单/Get WeChat MP Account Services & Custom Menu

        ``POST /api/v1/wechat_mp/v2/fetch_account_services``
        """
        json_body = _drop_none({
            "username": username,
            "raw": raw,
        })
        return await self._client._request("POST", "/api/v1/wechat_mp/v2/fetch_account_services", json=json_body)
