# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""Xiaohongshu-Web-V3-API resource.

OpenAPI tag: ``Xiaohongshu-Web-V3-API``
SDK attribute: ``client.xiaohongshu_web_v3`` / ``async_client.xiaohongshu_web_v3``

Endpoints: 5
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncXiaohongshuWebV3", "XiaohongshuWebV3"]


class XiaohongshuWebV3(SyncResource):
    """Sync ``Xiaohongshu-Web-V3-API`` resource (5 endpoints)."""

    def fetch_note_detail(
        self,
        *,
        note_id: str,
        xsec_token: str,
    ) -> Any:
        """获取笔记详情/Fetch note detail

        ``GET /api/v1/xiaohongshu/web_v3/fetch_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "xsec_token": xsec_token,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_note_detail", params=params)

    def fetch_search_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取搜索联想词/Fetch search suggestions

        ``GET /api/v1/xiaohongshu/web_v3/fetch_search_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_search_suggest", params=params)

    def fetch_homefeed(
        self,
        *,
        num: int | None = None,
        cursor_score: str | None = None,
        category: str | None = None,
        need_filter_image: bool | None = None,
    ) -> Any:
        """获取首页推荐/Fetch homepage feed

        ``GET /api/v1/xiaohongshu/web_v3/fetch_homefeed``
        """
        params = _drop_none({
            "num": num,
            "cursor_score": cursor_score,
            "category": category,
            "need_filter_image": need_filter_image,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_homefeed", params=params)

    def fetch_homefeed_categories(
        self,
    ) -> Any:
        """获取首页分类列表/Fetch homepage categories

        ``GET /api/v1/xiaohongshu/web_v3/fetch_homefeed_categories``
        """
        return self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_homefeed_categories")

    def fetch_user_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户信息/Fetch user info

        ``GET /api/v1/xiaohongshu/web_v3/fetch_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_user_info", params=params)


class AsyncXiaohongshuWebV3(AsyncResource):
    """Async ``Xiaohongshu-Web-V3-API`` resource (5 endpoints)."""

    async def fetch_note_detail(
        self,
        *,
        note_id: str,
        xsec_token: str,
    ) -> Any:
        """获取笔记详情/Fetch note detail

        ``GET /api/v1/xiaohongshu/web_v3/fetch_note_detail``
        """
        params = _drop_none({
            "note_id": note_id,
            "xsec_token": xsec_token,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_note_detail", params=params)

    async def fetch_search_suggest(
        self,
        *,
        keyword: str | None = None,
    ) -> Any:
        """获取搜索联想词/Fetch search suggestions

        ``GET /api/v1/xiaohongshu/web_v3/fetch_search_suggest``
        """
        params = _drop_none({
            "keyword": keyword,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_search_suggest", params=params)

    async def fetch_homefeed(
        self,
        *,
        num: int | None = None,
        cursor_score: str | None = None,
        category: str | None = None,
        need_filter_image: bool | None = None,
    ) -> Any:
        """获取首页推荐/Fetch homepage feed

        ``GET /api/v1/xiaohongshu/web_v3/fetch_homefeed``
        """
        params = _drop_none({
            "num": num,
            "cursor_score": cursor_score,
            "category": category,
            "need_filter_image": need_filter_image,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_homefeed", params=params)

    async def fetch_homefeed_categories(
        self,
    ) -> Any:
        """获取首页分类列表/Fetch homepage categories

        ``GET /api/v1/xiaohongshu/web_v3/fetch_homefeed_categories``
        """
        return await self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_homefeed_categories")

    async def fetch_user_info(
        self,
        *,
        user_id: str,
    ) -> Any:
        """获取用户信息/Fetch user info

        ``GET /api/v1/xiaohongshu/web_v3/fetch_user_info``
        """
        params = _drop_none({
            "user_id": user_id,
        })
        return await self._client._request("GET", "/api/v1/xiaohongshu/web_v3/fetch_user_info", params=params)
