# AUTO-GENERATED by scripts/generate_resources.py - do not edit by hand.
# Run the script again to refresh from spec/openapi.json.
"""YouTube-Web-API resource.

OpenAPI tag: ``YouTube-Web-API``
SDK attribute: ``client.youtube_web`` / ``async_client.youtube_web``

Endpoints: 8
"""

from __future__ import annotations

from typing import Any

from tikhub.resources._base import AsyncResource, SyncResource


def _drop_none(d: dict[str, Any]) -> dict[str, Any]:
    """Filter out keys whose value is ``None``."""
    return {k: v for k, v in d.items() if v is not None}


__all__ = ["AsyncYoutubeWeb", "YoutubeWeb"]


class YoutubeWeb(SyncResource):
    """Sync ``YouTube-Web-API`` resource (8 endpoints)."""

    def get_relate_video(
        self,
        *,
        video_id: str,
        continuation_token: str | None = None,
    ) -> Any:
        """获取推荐视频/Get related videos

        ``GET /api/v1/youtube/web/get_relate_video``
        """
        params = _drop_none({
            "video_id": video_id,
            "continuation_token": continuation_token,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_relate_video", params=params)

    def search_video(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
    ) -> Any:
        """搜索视频/Search video

        ``GET /api/v1/youtube/web/search_video``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "order_by": order_by,
            "country_code": country_code,
            "continuation_token": continuation_token,
        })
        return self._client._request("GET", "/api/v1/youtube/web/search_video", params=params)

    def get_channel_id(
        self,
        *,
        channel_name: str,
    ) -> Any:
        """获取频道ID/Get channel ID

        ``GET /api/v1/youtube/web/get_channel_id``
        """
        params = _drop_none({
            "channel_name": channel_name,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_channel_id", params=params)

    def get_channel_id_v2(
        self,
        *,
        channel_url: str,
    ) -> Any:
        """从频道URL获取频道ID V2/Get channel ID from URL V2

        ``GET /api/v1/youtube/web/get_channel_id_v2``
        """
        params = _drop_none({
            "channel_url": channel_url,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_channel_id_v2", params=params)

    def get_channel_url(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """从频道ID获取频道URL/Get channel URL from channel ID

        ``GET /api/v1/youtube/web/get_channel_url``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_channel_url", params=params)

    def get_channel_info(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """获取频道信息/Get channel information

        ``GET /api/v1/youtube/web/get_channel_info``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_channel_info", params=params)

    def get_channel_short_videos(
        self,
        *,
        channel_id: str,
        continuation_token: str | None = None,
    ) -> Any:
        """获取频道短视频/Get channel short videos

        ``GET /api/v1/youtube/web/get_channel_short_videos``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "continuation_token": continuation_token,
        })
        return self._client._request("GET", "/api/v1/youtube/web/get_channel_short_videos", params=params)

    def search_channel(
        self,
        *,
        channel_id: str,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
    ) -> Any:
        """搜索频道/Search channel

        ``GET /api/v1/youtube/web/search_channel``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
        })
        return self._client._request("GET", "/api/v1/youtube/web/search_channel", params=params)


class AsyncYoutubeWeb(AsyncResource):
    """Async ``YouTube-Web-API`` resource (8 endpoints)."""

    async def get_relate_video(
        self,
        *,
        video_id: str,
        continuation_token: str | None = None,
    ) -> Any:
        """获取推荐视频/Get related videos

        ``GET /api/v1/youtube/web/get_relate_video``
        """
        params = _drop_none({
            "video_id": video_id,
            "continuation_token": continuation_token,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_relate_video", params=params)

    async def search_video(
        self,
        *,
        search_query: str,
        language_code: str | None = None,
        order_by: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
    ) -> Any:
        """搜索视频/Search video

        ``GET /api/v1/youtube/web/search_video``
        """
        params = _drop_none({
            "search_query": search_query,
            "language_code": language_code,
            "order_by": order_by,
            "country_code": country_code,
            "continuation_token": continuation_token,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/search_video", params=params)

    async def get_channel_id(
        self,
        *,
        channel_name: str,
    ) -> Any:
        """获取频道ID/Get channel ID

        ``GET /api/v1/youtube/web/get_channel_id``
        """
        params = _drop_none({
            "channel_name": channel_name,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_channel_id", params=params)

    async def get_channel_id_v2(
        self,
        *,
        channel_url: str,
    ) -> Any:
        """从频道URL获取频道ID V2/Get channel ID from URL V2

        ``GET /api/v1/youtube/web/get_channel_id_v2``
        """
        params = _drop_none({
            "channel_url": channel_url,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_channel_id_v2", params=params)

    async def get_channel_url(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """从频道ID获取频道URL/Get channel URL from channel ID

        ``GET /api/v1/youtube/web/get_channel_url``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_channel_url", params=params)

    async def get_channel_info(
        self,
        *,
        channel_id: str,
    ) -> Any:
        """获取频道信息/Get channel information

        ``GET /api/v1/youtube/web/get_channel_info``
        """
        params = _drop_none({
            "channel_id": channel_id,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_channel_info", params=params)

    async def get_channel_short_videos(
        self,
        *,
        channel_id: str,
        continuation_token: str | None = None,
    ) -> Any:
        """获取频道短视频/Get channel short videos

        ``GET /api/v1/youtube/web/get_channel_short_videos``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "continuation_token": continuation_token,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/get_channel_short_videos", params=params)

    async def search_channel(
        self,
        *,
        channel_id: str,
        search_query: str,
        language_code: str | None = None,
        country_code: str | None = None,
        continuation_token: str | None = None,
    ) -> Any:
        """搜索频道/Search channel

        ``GET /api/v1/youtube/web/search_channel``
        """
        params = _drop_none({
            "channel_id": channel_id,
            "search_query": search_query,
            "language_code": language_code,
            "country_code": country_code,
            "continuation_token": continuation_token,
        })
        return await self._client._request("GET", "/api/v1/youtube/web/search_channel", params=params)
