"""Example: Bilibili-Web-API

SDK attribute: ``client.bilibili_web``
Endpoints: 30

Usage::

    python examples/bilibili_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/bilibili/web/fetch_one_video
        # 获取单个视频详情信息/Get single video data
        result = await client.bilibili_web.fetch_one_video(bv_id='BV1M1421t7hT')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_one_video_v2
        # 获取单个视频详情信息V2/Get single video data V2
        result = await client.bilibili_web.fetch_one_video_v2(a_id='114006081739452', c_id='28400484458')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_one_video_v3
        # 获取单个视频详情信息V3/Get single video data V3
        result = await client.bilibili_web.fetch_one_video_v3(url='https://www.bilibili.com/video/BV1S5uKzzE4r')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_detail
        # 获取单个视频详情/Get single video detail
        result = await client.bilibili_web.fetch_video_detail(aid='114902186396822')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_play_info
        # 获取单个视频播放信息/Get single video play info
        result = await client.bilibili_web.fetch_video_play_info(url='https://www.bilibili.com/video/BV1S5uKzzE4r')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_subtitle
        # 获取视频字幕信息/Get video subtitle info
        result = await client.bilibili_web.fetch_video_subtitle(a_id='114006081739452', c_id='28400484458')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_hot_search
        # 获取热门搜索信息/Get hot search data
        result = await client.bilibili_web.fetch_hot_search(limit=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_general_search
        # 获取综合搜索信息/Get general search data
        result = await client.bilibili_web.fetch_general_search(keyword='火影忍者', order='totalrank', page=1, page_size=42, duration=0, pubtime_begin_s=0, pubtime_end_s=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_playurl
        # 获取视频流地址/Get video playurl
        result = await client.bilibili_web.fetch_video_playurl(bv_id='BV1y7411Q7Eq', cid='171776208')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/bilibili/web/fetch_vip_video_playurl
        # 获取大会员清晰度视频流地址/Get VIP video playurl
        result = await client.bilibili_web.fetch_vip_video_playurl(bv_id='BV1y7411Q7Eq', cid='171776208', cookie='your_vip_bilibili_cookie')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_post_videos
        # 获取用户主页作品数据/Get user homepage video data
        result = await client.bilibili_web.fetch_user_post_videos(uid='178360345', pn=1, order='pubdate')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_collect_folders
        # 获取用户所有收藏夹信息/Get user collection folders
        result = await client.bilibili_web.fetch_collect_folders(uid='178360345')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_collection_videos
        # 获取指定收藏夹内视频数据/Gets video data from a collection folder
        result = await client.bilibili_web.fetch_user_collection_videos(folder_id='1756059545', pn=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_profile
        # 获取指定用户的信息/Get information of specified user
        result = await client.bilibili_web.fetch_user_profile(uid='178360345')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_up_stat
        # 获取UP主状态统计/Get UP stat (total likes and views)
        result = await client.bilibili_web.fetch_user_up_stat(uid='178360345')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_relation_stat
        # 获取用户关系状态统计/Get user relation stat (following and followers)
        result = await client.bilibili_web.fetch_user_relation_stat(uid='178360345')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_com_popular
        # 获取综合热门视频信息/Get comprehensive popular video information
        result = await client.bilibili_web.fetch_com_popular(pn=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_comments
        # 获取指定视频的评论/Get comments on the specified video
        result = await client.bilibili_web.fetch_video_comments(bv_id='BV1M1421t7hT', pn=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_comment_reply
        # 获取视频下指定评论的回复/Get reply to the specified comment
        result = await client.bilibili_web.fetch_comment_reply(bv_id='BV1M1421t7hT', pn=1, rpid='237109455120')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_user_dynamic
        # 获取指定用户动态/Get dynamic information of specified user
        result = await client.bilibili_web.fetch_user_dynamic(uid='16015678', offset='953154282154098691')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_dynamic_detail
        # 获取动态详情/Get dynamic detail
        result = await client.bilibili_web.fetch_dynamic_detail(dynamic_id='1172584638000922630')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_dynamic_detail_v2
        # 获取动态详情v2/Get dynamic detail v2
        result = await client.bilibili_web.fetch_dynamic_detail_v2(dynamic_id='1172584638000922630')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_danmaku
        # 获取视频实时弹幕/Get Video Danmaku
        result = await client.bilibili_web.fetch_video_danmaku(cid='1639235405')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_live_room_detail
        # 获取指定直播间信息/Get information of specified live room
        result = await client.bilibili_web.fetch_live_room_detail(room_id='22816111')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_live_videos
        # 获取直播间视频流/Get live video data of specified room
        result = await client.bilibili_web.fetch_live_videos(room_id='1815229528')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_live_streamers
        # 获取指定分区正在直播的主播/Get live streamers of specified live area
        result = await client.bilibili_web.fetch_live_streamers(area_id='9', pn=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_all_live_areas
        # 获取所有直播分区列表/Get a list of all live areas
        result = await client.bilibili_web.fetch_all_live_areas()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/bv_to_aid
        # 通过bv号获得视频aid号/Generate aid by bvid
        result = await client.bilibili_web.bv_to_aid(bv_id='BV1M1421t7hT')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_video_parts
        # 通过bv号获得视频分p信息/Get Video Parts By bvid
        result = await client.bilibili_web.fetch_video_parts(bv_id='BV1vf421i7hV')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/web/fetch_get_user_id
        # 提取用户ID/Extract user ID
        result = await client.bilibili_web.fetch_get_user_id(share_link='https://b23.tv/1ZuB5NC')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
