"""Example: Bilibili-App-API

SDK attribute: ``client.bilibili_app``
Endpoints: 11

Usage::

    python examples/bilibili_app.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/bilibili/app/fetch_one_video
        # 获取单个视频详情信息/Get single video data
        result = await client.bilibili_app.fetch_one_video(av_id='115568241811221', bv_id='BV18SCrBGE9E')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_video_comments
        # 获取视频评论列表/Get video comments
        result = await client.bilibili_app.fetch_video_comments(av_id='115568241811221', bv_id='BV18SCrBGE9E', mode=3, next_offset=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_reply_detail
        # 获取二级评论回复/Get reply detail
        result = await client.bilibili_app.fetch_reply_detail(root='241743663521', av_id='113100682434775', bv_id='BV18SCrBGE9E', next_offset=0, ps=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_user_videos
        # 获取用户投稿视频/Get user videos
        result = await client.bilibili_app.fetch_user_videos(user_id='203680252', post_filter='archive', page=1, ps=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_user_info
        # 获取用户信息/Get user info
        result = await client.bilibili_app.fetch_user_info(user_id='203680252')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_home_feed
        # 获取主页推荐视频流/Get home feed
        result = await client.bilibili_app.fetch_home_feed(flush=0, pull=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_popular_feed
        # 获取热门推荐/Get popular feed
        result = await client.bilibili_app.fetch_popular_feed(idx=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_search_all
        # 综合搜索/search all
        result = await client.bilibili_app.fetch_search_all(keyword='原神', page=1, page_size=20, order=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_search_by_type
        # 分类搜索/ search by type
        result = await client.bilibili_app.fetch_search_by_type(keyword='原神', search_type='video', page=1, page_size=20, order=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_cinema_tab
        # 获取影视推荐/Get cinema tab
        result = await client.bilibili_app.fetch_cinema_tab()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/bilibili/app/fetch_bangumi_tab
        # 获取番剧推荐/Get bangumi tab
        result = await client.bilibili_app.fetch_bangumi_tab()
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
