"""Example: Douyin-Creator-V2-API

SDK attribute: ``client.douyin_creator_v2``
Endpoints: 14

Usage::

    python examples/douyin_creator_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # POST /api/v1/douyin/creator_v2/fetch_item_overview_data
        # 获取作品总览数据/Fetch item overview data
        result = await client.douyin_creator_v2.fetch_item_overview_data(cookie='Your_Cookie_Here', ids='7559536212910853422,7559536212910853423', fields='metrics,review,play_info,dou_plus,integrated_incentive,incentive_life,content_analysis')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_play_source
        # 获取作品流量来源统计/Fetch item play source statistics
        result = await client.douyin_creator_v2.fetch_item_play_source(cookie='Your_Cookie_Here', item_id='7559536212910853422')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_search_keyword
        # 获取作品搜索关键词统计/Fetch item search keywords statistics
        result = await client.douyin_creator_v2.fetch_item_search_keyword(cookie='Your_Cookie_Here', item_id='7559536212910853422')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_watch_trend
        # 获取作品观看趋势分析/Fetch item watch trend analysis
        result = await client.douyin_creator_v2.fetch_item_watch_trend(cookie='Your_Cookie_Here', item_id='7559536212910853422', analysis_type=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_danmaku_analysis
        # 获取作品弹幕分析/Fetch item bullet analysis
        result = await client.douyin_creator_v2.fetch_item_danmaku_analysis(cookie='Your_Cookie_Here', item_id='7559536212910853422')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_audience_portrait
        # 获取作品观众数据分析/Fetch item audience portrait
        result = await client.douyin_creator_v2.fetch_item_audience_portrait(cookie='Your_Cookie_Here', item_id='7559536212910853422')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_audience_others
        # 获取作品观众其他数据分析/Fetch item audience others analysis
        result = await client.douyin_creator_v2.fetch_item_audience_others(cookie='Your_Cookie_Here', item_id='7559536212910853422')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_analysis_involved_vertical
        # 获取作品垂类标签/Fetch item analysis involved vertical
        result = await client.douyin_creator_v2.fetch_item_analysis_involved_vertical(cookie='Your_Cookie_Here', start_date='20250713', end_date='20251011')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_analysis_overview
        # 获取投稿分析概览/Fetch item analysis overview
        result = await client.douyin_creator_v2.fetch_item_analysis_overview(cookie='Your_Cookie_Here', start_date='20250713', end_date='20251011', genres=[1, 2, 3, 4, 5, 8], primary_verticals=['动物'])
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_analysis_item_performance
        # 获取投稿表现数据/Fetch item analysis item performance
        result = await client.douyin_creator_v2.fetch_item_analysis_item_performance(cookie='Your_Cookie_Here', start_date='20250713', end_date='20251011', genres=[2, 3, 4, 5, 8], primary_verticals=['动物'], metric_type=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_list
        # 获取投稿作品列表/Fetch item list
        result = await client.douyin_creator_v2.fetch_item_list(cookie='Your_Cookie_Here', count=10, order_by=1, fields='metrics,review,visibility', need_cooperation=True, start_time=1758988800000, end_time=1760198399000, need_long_article=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_item_list_download
        # 导出投稿作品列表/Download item list
        result = await client.douyin_creator_v2.fetch_item_list_download(cookie='Your_Cookie_Here', min_cursor=1752336000000, max_cursor=1760198399000, type_filters=[2, 3, 4, 5, 1, 8], need_long_article=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_live_room_history_list
        # 获取直播场次历史记录/Fetch live room history list
        result = await client.douyin_creator_v2.fetch_live_room_history_list(cookie='Your_Cookie_Here', start_date='2025-09-11', end_date='2025-10-11', limit=400, need_living=1, download=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/creator_v2/fetch_author_diagnosis
        # 获取创作者账号诊断/Fetch author diagnosis
        result = await client.douyin_creator_v2.fetch_author_diagnosis(cookie='Your_Cookie_Here')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
