"""Example: Douyin-Xingtu-API

SDK attribute: ``client.douyin_xingtu``
Endpoints: 22

Usage::

    python examples/douyin_xingtu.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/douyin/xingtu/get_sign_image
        # 获取加密图片解析/Get Sign Image
        result = await client.douyin_xingtu.get_sign_image(uri='tos-cn-i-0813c000-ce/oMKzDA3A9QGAuebfsDIAwlDoAfCFEEzSEw8FQZ', durationTS=86400, format='webp')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_uid
        # 根据抖音用户ID获取游客星图kolid/Get XingTu kolid by Douyin User ID
        result = await client.douyin_xingtu.get_xingtu_kolid_by_uid(uid='70452002324')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_sec_user_id
        # 根据抖音sec_user_id获取游客星图kolid/Get XingTu kolid by Douyin sec_user_id
        result = await client.douyin_xingtu.get_xingtu_kolid_by_sec_user_id(sec_user_id='MS4wLjABAAAAoxwUZouIdKL6sZ8EB96KDjkrhfBMS1KbCgsMJR1kIUs')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/get_xingtu_kolid_by_unique_id
        # 根据抖音号获取游客星图kolid/Get XingTu kolid by Douyin unique_id
        result = await client.douyin_xingtu.get_xingtu_kolid_by_unique_id(unique_id='m6640150')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_base_info_v1
        # 获取kol基本信息V1/Get kol Base Info V1
        result = await client.douyin_xingtu.kol_base_info_v1(kolId='7048929565493690398', platformChannel='_1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_audience_portrait_v1
        # 获取kol观众画像V1/Get kol Audience Portrait V1
        result = await client.douyin_xingtu.kol_audience_portrait_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_fans_portrait_v1
        # 获取kol粉丝画像V1/Get kol Fans Portrait V1
        result = await client.douyin_xingtu.kol_fans_portrait_v1(kolId='7048929565493690398', fansType='_1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_service_price_v1
        # 获取kol服务报价V1/Get kol Service Price V1
        result = await client.douyin_xingtu.kol_service_price_v1(kolId='7048929565493690398', platformChannel='_1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_data_overview_v1
        # 获取kol数据概览V1/Get kol Data Overview V1
        result = await client.douyin_xingtu.kol_data_overview_v1(kolId='7048929565493690398', _type='_1', _range='_2', flowType=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/search_kol_v1
        # 关键词搜索kol V1/Search Kol V1
        result = await client.douyin_xingtu.search_kol_v1(keyword='抖音', platformSource='_1', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/search_kol_v2
        # 高级搜索kol V2/Search Kol Advanced V2
        result = await client.douyin_xingtu.search_kol_v2(keyword='美妆', followerRange='10-100', contentTag='tag-1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_conversion_ability_analysis_v1
        # 获取kol转化能力分析V1/Get kol Conversion Ability Analysis V1
        result = await client.douyin_xingtu.kol_conversion_ability_analysis_v1(kolId='7048929565493690398', _range='_1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_video_performance_v1
        # 获取kol视频表现V1/Get kol Video Performance V1
        result = await client.douyin_xingtu.kol_video_performance_v1(kolId='7048929565493690398', onlyAssign=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_xingtu_index_v1
        # 获取kol星图指数V1/Get kol Xingtu Index V1
        result = await client.douyin_xingtu.kol_xingtu_index_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_convert_video_display_v1
        # 获取kol转化视频展示V1/Get kol Convert Video Display V1
        result = await client.douyin_xingtu.kol_convert_video_display_v1(kolId='7048929565493690398', detailType='_1', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_link_struct_v1
        # 获取kol连接用户V1/Get kol Link Struct V1
        result = await client.douyin_xingtu.kol_link_struct_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_touch_distribution_v1
        # 获取kol连接用户来源V1/Get kol Touch Distribution V1
        result = await client.douyin_xingtu.kol_touch_distribution_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_cp_info_v1
        # 获取kol性价比能力分析V1/Get kol Cp Info V1
        result = await client.douyin_xingtu.kol_cp_info_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_rec_videos_v1
        # 获取kol内容表现V1/Get kol Rec Videos V1
        result = await client.douyin_xingtu.kol_rec_videos_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/kol_daily_fans_v1
        # 获取kol粉丝趋势V1/Get kol Daily Fans V1
        result = await client.douyin_xingtu.kol_daily_fans_v1(kolId='7048929565493690398', startDate='2024-12-01', endDate='2025-01-01')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/author_hot_comment_tokens_v1
        # 获取kol热词分析评论V1/Get Author Hot Comment Tokens V1
        result = await client.douyin_xingtu.author_hot_comment_tokens_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/xingtu/author_content_hot_comment_keywords_v1
        # 获取kol热词分析内容V1/Get Author Content Hot Comment Keywords V1
        result = await client.douyin_xingtu.author_content_hot_comment_keywords_v1(kolId='7048929565493690398')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
