"""Example: Douyin-DouPlus-API

SDK attribute: ``client.douyin_douplus``
Endpoints: 17

Usage::

    python examples/douyin_douplus.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # POST /api/v1/douyin/douplus/fetch_promotable_item_list
        # 获取可推广作品列表(含点赞评论量)/Get promotable item list (with like & comment counts)
        result = await client.douyin_douplus.fetch_promotable_item_list(sec_uid='MS4wLjABAAAA9fe7vGjwyiaOjL6REhX8rvmSb32VzA_XsKca9F3_YSHRXlEqgT2cpX54WGbtgnsA', count=30, target_id=31)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/search_user
        # 搜索 DOU+ 用户/Search DOU+ user
        result = await client.douyin_douplus.search_user(keyword='啵', count=20, cursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/search_user_v2
        # 搜索用户 V2/Search user V2
        result = await client.douyin_douplus.search_user_v2(keyword='啵', cursor=0, count=10, scope=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_video_ranking
        # 获取 DOU+ 视频排行榜/Get DOU+ video ranking
        result = await client.douyin_douplus.fetch_video_ranking(time_range=2, tag_id=634, dim_type=5, adv_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_sec_token
        # 获取DOU+ POST请求所需的sec_token/Get DOU+ sec_token for POST requests
        result = await client.douyin_douplus.fetch_sec_token(cookie='Your_Cookie_Here')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/calculate_cost
        # DOU+成本计算/DOU+ cost estimation
        result = await client.douyin_douplus.calculate_cost(cookie='Your_Cookie_Here', sec_uid='MS4wLjABAAAA9fe7vGjwyiaOjL6REhX8rvmSb32VzA_XsKca9F3_YSHRXlEqgT2cpX54WGbtgnsA', item_ids='7651166972160446949', target_id=31)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_delivery_effect_estimate
        # 获取DOU+预计投放效果/Get DOU+ estimated delivery results
        result = await client.douyin_douplus.fetch_delivery_effect_estimate(item_ids='7677202522116819185', external_action=44, target_id=31, schema=0, is_max_cv=True, pay_type=1, cost_int=30000, duration_seconds=21600)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_promoted_accounts
        # 获取投放过的账号/Get promoted accounts
        result = await client.douyin_douplus.fetch_promoted_accounts(cookie='Your_Cookie_Here', limit=20, cursor='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_analyse_overview
        # 投放数据概览(账号/视频/直播)/Delivery analysis overview
        result = await client.douyin_douplus.fetch_analyse_overview(cookie='Your_Cookie_Here', query={'CollectWayIds': [], 'SecondaryTargetIds': [], 'analysisType': 1, 'authorSecIdList': [], 'endTime': '1781625599', 'metrics': ['stat_cost', 'total_play', 'play_duration_5s_rate', 'total_like', 'dy_comment', 'dy_share', 'dy_home_visited', 'dy_follow'], 'startTime': '1780934400', 'statusList': []})
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_analyse_graph
        # 投放数据趋势图/Delivery analysis trend graph
        result = await client.douyin_douplus.fetch_analyse_graph(cookie='Your_Cookie_Here', query={'CollectWayIds': [], 'SecondaryTargetIds': [], 'analysisType': 1, 'authorSecIdList': [], 'endTime': '1781625599', 'metrics': ['stat_cost', 'total_play', 'play_duration_5s_rate', 'total_like', 'dy_comment', 'dy_share', 'dy_home_visited', 'dy_follow'], 'startTime': '1780934400', 'statusList': []})
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_analyse_detail
        # 投放数据明细/Delivery analysis detail
        result = await client.douyin_douplus.fetch_analyse_detail(cookie='Your_Cookie_Here', query={'CollectWayIds': [], 'SecondaryTargetIds': [], 'analysisType': 1, 'authorSecIdList': [], 'endTime': '1781625599', 'metrics': ['stat_cost', 'total_play', 'play_duration_5s_rate', 'total_like', 'dy_comment', 'dy_share', 'dy_home_visited', 'dy_follow'], 'startTime': '1780934400', 'statusList': []})
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_talent_categories
        # 获取达人分类/Get talent categories
        result = await client.douyin_douplus.fetch_talent_categories()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_talents_by_category
        # 按分类搜索达人/Search talents by category
        result = await client.douyin_douplus.fetch_talents_by_category(name='音乐', page=0, limit=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_user_posts
        # 获取用户主页作品/Get user homepage posts
        result = await client.douyin_douplus.fetch_user_posts(sec_uid='MS4wLjABAAAA9fe7vGjwyiaOjL6REhX8rvmSb32VzA_XsKca9F3_YSHRXlEqgT2cpX54WGbtgnsA', cursor='0', count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/search_video
        # 搜索视频(按标题)/Search videos (by title)
        result = await client.douyin_douplus.search_video(keyword='major', cursor=0, count=12)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/fetch_video_detail
        # 获取视频详情(按ID或链接)/Get video detail (by id or link)
        result = await client.douyin_douplus.fetch_video_detail(video='7651708301280906538')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/douplus/search_live_room
        # 搜索直播间(抖音号/昵称)/Search live rooms (by Douyin ID or nickname)
        result = await client.douyin_douplus.search_live_room(keyword='小耳朵', cursor=0, count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
