"""Example: Douyin-Billboard-API

SDK attribute: ``client.douyin_billboard``
Endpoints: 31

Usage::

    python examples/douyin_billboard.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/douyin/billboard/fetch_city_list
        # 获取中国城市列表/Fetch Chinese city list
        result = await client.douyin_billboard.fetch_city_list()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_content_tag
        # 获取垂类内容标签/Fetch vertical content tags
        result = await client.douyin_billboard.fetch_content_tag()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_category_list
        # 获取热点榜分类/Fetch hot list category
        result = await client.douyin_billboard.fetch_hot_category_list(billboard_type='rise', snapshot_time='20250106151500', start_date='', end_date='', keyword='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_rise_list
        # 获取上升热点榜/Fetch rising hot list
        result = await client.douyin_billboard.fetch_hot_rise_list(page=1, page_size=10, order='rank', sentence_tag='', keyword='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_city_list
        # 获取同城热点榜/Fetch city hot list
        result = await client.douyin_billboard.fetch_hot_city_list(page=1, page_size=10, order='rank', city_code='', sentence_tag='', keyword='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_challenge_list
        # 获取挑战热榜/Fetch hot challenge list
        result = await client.douyin_billboard.fetch_hot_challenge_list(page=1, page_size=10, keyword='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_total_list
        # 获取热点总榜/Fetch total hot list
        result = await client.douyin_billboard.fetch_hot_total_list(page=1, page_size=10, type='snapshot', snapshot_time='20250106151500', start_date='', end_date='', sentence_tag='', keyword='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_calendar_list
        # 获取活动日历/Fetch activity calendar
        result = await client.douyin_billboard.fetch_hot_calendar_list(city_code='', category_code='', end_date=1735488000, start_date=1734902400)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_calendar_detail
        # 获取活动日历详情/Fetch activity calendar detail
        result = await client.douyin_billboard.fetch_hot_calendar_detail(calendar_id='1720')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_user_portrait_list
        # 获取作品点赞观众画像-仅限热门榜/Fetch work like audience portrait - hot list only
        result = await client.douyin_billboard.fetch_hot_user_portrait_list(aweme_id='7456035425539329340', option=4)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_comment_word_list
        # 获取作品评论分析-词云权重/Fetch work comment analysis word cloud weight
        result = await client.douyin_billboard.fetch_hot_comment_word_list(aweme_id='7456035425539329340')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_item_trends_list
        # 获取作品数据趋势/Fetch post data trend
        result = await client.douyin_billboard.fetch_hot_item_trends_list(aweme_id='', option=7, date_window=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_account_list
        # 获取热门账号/Fetch hot account list
        result = await client.douyin_billboard.fetch_hot_account_list(date_window=24, page_num=1, page_size=10, query_tag={})
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_search_list
        # 搜索用户名或抖音号/Fetch account search list
        result = await client.douyin_billboard.fetch_hot_account_search_list(keyword='rmrbxmt', cursor=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_trends_list
        # 获取账号粉丝数据趋势/Fetch account fan data trend
        result = await client.douyin_billboard.fetch_hot_account_trends_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4', option=2, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_item_analysis_list
        # 获取账号作品分析-上周/Fetch account work analysis - last week
        result = await client.douyin_billboard.fetch_hot_account_item_analysis_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_fans_portrait_list
        # 获取粉丝画像/Fetch fan portrait
        result = await client.douyin_billboard.fetch_hot_account_fans_portrait_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4', option=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_fans_interest_account_list
        # 获取粉丝兴趣作者 20个用户/Fetch fan interest author 20 users
        result = await client.douyin_billboard.fetch_hot_account_fans_interest_account_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_fans_interest_topic_list
        # 获取粉丝近3天感兴趣的话题 10个话题/Fetch fan interest topic in the last 3 days 10 topics
        result = await client.douyin_billboard.fetch_hot_account_fans_interest_topic_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_account_fans_interest_search_list
        # 获取粉丝近3天搜索词 10个搜索词/Fetch fan interest search term in the last 3 days 10 search terms
        result = await client.douyin_billboard.fetch_hot_account_fans_interest_search_list(sec_uid='MS4wLjABAAAA8U_l6rBzmy7bcy6xOJel4v0RzoR_wfAubGPeJimN__4')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_video_list
        # 获取视频热榜/Fetch video hot list
        result = await client.douyin_billboard.fetch_hot_total_video_list(page=1, page_size=10, date_window=24, sub_type=1001)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_low_fan_list
        # 获取低粉爆款榜/Fetch low fan explosion list
        result = await client.douyin_billboard.fetch_hot_total_low_fan_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_high_play_list
        # 获取高完播率榜/Fetch high completion rate list
        result = await client.douyin_billboard.fetch_hot_total_high_play_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_high_like_list
        # 获取高点赞率榜/Fetch high like rate list
        result = await client.douyin_billboard.fetch_hot_total_high_like_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_high_fan_list
        # 获取高涨粉率榜/Fetch high fan rate list
        result = await client.douyin_billboard.fetch_hot_total_high_fan_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_topic_list
        # 获取话题热榜/Fetch topic hot list
        result = await client.douyin_billboard.fetch_hot_total_topic_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_high_topic_list
        # 获取热度飙升的话题榜/Fetch topic list with rising popularity
        result = await client.douyin_billboard.fetch_hot_total_high_topic_list(page=1, page_size=10, date_window=24)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_search_list
        # 获取搜索热榜/Fetch search hot list
        result = await client.douyin_billboard.fetch_hot_total_search_list(page_num=1, page_size=10, date_window=24, keyword='抖音')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_high_search_list
        # 获取热度飙升的搜索榜/Fetch search list with rising popularity
        result = await client.douyin_billboard.fetch_hot_total_high_search_list(page_num=1, page_size=10, date_window=24, keyword='抖音')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/douyin/billboard/fetch_hot_total_hot_word_list
        # 获取全部热门内容词/Fetch all hot content words
        result = await client.douyin_billboard.fetch_hot_total_hot_word_list(page_num=1, page_size=10, date_window=24, keyword='抖音')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/douyin/billboard/fetch_hot_total_hot_word_detail_list
        # 获取内容词详情/Fetch content word details
        result = await client.douyin_billboard.fetch_hot_total_hot_word_detail_list(keyword='', word_id='', query_day=20250105)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
