"""Example: Instagram-V2-API

SDK attribute: ``client.instagram_v2``
Endpoints: 27

Usage::

    python examples/instagram_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/instagram/v2/shortcode_to_media_id
        # Shortcode转Media ID/Convert shortcode to media ID
        result = await client.instagram_v2.shortcode_to_media_id(shortcode='DRhvwVLAHAG')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/media_id_to_shortcode
        # Media ID转Shortcode/Convert media ID to shortcode
        result = await client.instagram_v2.media_id_to_shortcode(media_id='3774507992167247878')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/user_id_to_username
        # 用户ID转用户信息/Get user info by user ID
        result = await client.instagram_v2.user_id_to_username(user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_info
        # 获取用户信息/Get user info
        result = await client.instagram_v2.fetch_user_info(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_posts
        # 获取用户帖子/Get user posts
        result = await client.instagram_v2.fetch_user_posts(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_reels
        # 获取用户Reels/Get user reels
        result = await client.instagram_v2.fetch_user_reels(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_followers
        # 获取用户粉丝/Get user followers
        result = await client.instagram_v2.fetch_user_followers(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_following
        # 获取用户关注/Get user following
        result = await client.instagram_v2.fetch_user_following(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_stories
        # 获取用户故事/Get user stories
        result = await client.instagram_v2.fetch_user_stories(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_highlights
        # 获取用户精选/Get user highlights
        result = await client.instagram_v2.fetch_user_highlights(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_highlight_stories
        # 获取精选故事详情/Get highlight stories
        result = await client.instagram_v2.fetch_highlight_stories(highlight_id='17895069621772257')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_user_tagged_posts
        # 获取用户被标记的帖子/Get user tagged posts
        result = await client.instagram_v2.fetch_user_tagged_posts(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_similar_users
        # 获取相似用户/Get similar users
        result = await client.instagram_v2.fetch_similar_users(username='instagram', user_id='18527')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_users
        # 搜索用户/Search users
        result = await client.instagram_v2.search_users(keyword='instagram')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/general_search
        # 综合搜索/General search
        result = await client.instagram_v2.general_search(keyword='cat')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_reels
        # 搜索Reels/Search reels
        result = await client.instagram_v2.search_reels(keyword='cat')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_music
        # 搜索音乐/Search music
        result = await client.instagram_v2.search_music(keyword='happy')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_hashtags
        # 搜索话题标签/Search hashtags
        result = await client.instagram_v2.search_hashtags(keyword='cat')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_locations
        # 搜索地点/Search locations
        result = await client.instagram_v2.search_locations(keyword='paris')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/search_by_coordinates
        # 根据坐标搜索地点/Search locations by coordinates
        result = await client.instagram_v2.search_by_coordinates(latitude=40.7, longitude=-74)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_post_info
        # 获取帖子详情/Get post info
        result = await client.instagram_v2.fetch_post_info(code_or_url='DRhvwVLAHAG')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_post_likes
        # 获取帖子点赞列表/Get post likes
        result = await client.instagram_v2.fetch_post_likes(code_or_url='DRhvwVLAHAG')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_post_comments
        # 获取帖子评论/Get post comments
        result = await client.instagram_v2.fetch_post_comments(code_or_url='DRhvwVLAHAG', sort_by='recent', pagination_token='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_comment_replies
        # 获取评论回复/Get comment replies
        result = await client.instagram_v2.fetch_comment_replies(code_or_url='DRhvwVLAHAG', comment_id='18067775592012345')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_music_posts
        # 获取音乐帖子/Get music posts
        result = await client.instagram_v2.fetch_music_posts(audio_canonical_id='564058920086577')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_location_posts
        # 获取地点帖子/Get location posts
        result = await client.instagram_v2.fetch_location_posts(location_id='331004901')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/instagram/v2/fetch_hashtag_posts
        # 获取话题帖子/Get hashtag posts
        result = await client.instagram_v2.fetch_hashtag_posts(keyword='cat', feed_type='top')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
