"""Example: Kuaishou-App-API

SDK attribute: ``client.kuaishou_app``
Endpoints: 20

Usage::

    python examples/kuaishou_app.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/kuaishou/app/fetch_one_video
        # 视频详情V1/Video detailsV1
        result = await client.kuaishou_app.fetch_one_video(photo_id='3xhpk3xcf6e4iac')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_videos_batch
        # 快手批量视频查询接口/Kuaishou batch video query API
        result = await client.kuaishou_app.fetch_videos_batch(photo_ids='5228960823332207296,5196309727975443273,5222486898325987583')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_one_video_by_url
        # 根据链接获取单个作品数据/Fetch single video by URL
        result = await client.kuaishou_app.fetch_one_video_by_url(share_text='https://v.kuaishou.com/cNYP0Z')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_one_video_comment
        # 获取单个作品评论数据/Get single video comment data
        result = await client.kuaishou_app.fetch_one_video_comment(photo_id='3x7gxp2zhgjv832')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_one_user_v2
        # 获取单个用户数据V2/Get single user data V2
        result = await client.kuaishou_app.fetch_one_user_v2(user_id='3xz63mn6fngqtiq')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_user_live_info
        # 获取用户直播信息/Get user live info
        result = await client.kuaishou_app.fetch_user_live_info(user_id='1377082950')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_user_hot_post
        # 获取用户热门作品数据/Get user hot post data
        result = await client.kuaishou_app.fetch_user_hot_post(user_id='228905802')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_user_post_v2
        # 用户视频列表V2/User video list V2
        result = await client.kuaishou_app.fetch_user_post_v2(user_id='903511772')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/search_comprehensive
        # 综合搜索/Comprehensive search
        result = await client.kuaishou_app.search_comprehensive(keyword='汽车之家', sort_type='all', publish_time='all', duration='all', search_scope='all')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/search_video_v2
        # 搜索视频V2/Search video V2
        result = await client.kuaishou_app.search_video_v2(keyword='人工智能', page='1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/search_user_v2
        # 搜索用户V2/Search user V2
        result = await client.kuaishou_app.search_user_v2(keyword='人工智能', page='1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_hot_board_categories
        # 快手热榜分类/Kuaishou hot categories
        result = await client.kuaishou_app.fetch_hot_board_categories()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_hot_board_detail
        # 快手热榜详情/Kuaishou hot board detail
        result = await client.kuaishou_app.fetch_hot_board_detail(boardType=1, boardId='1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_hot_search_person
        # 快手热搜人物榜单/Kuaishou hot search person board
        result = await client.kuaishou_app.fetch_hot_search_person()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_live_top_list
        # 快手直播榜单/Kuaishou live top list
        result = await client.kuaishou_app.fetch_live_top_list(subTabId=0, subTabName='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_shopping_top_list
        # 快手购物榜单/Kuaishou shopping top list
        result = await client.kuaishou_app.fetch_shopping_top_list(subTabId=0, subTabName='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_brand_top_list
        # 快手品牌榜单/Kuaishou brand top list
        result = await client.kuaishou_app.fetch_brand_top_list(subTabId=0, subTabName='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/generate_kuaishou_share_link
        # 生成快手分享链接/Generate Kuaishou share link
        result = await client.kuaishou_app.generate_kuaishou_share_link(shareObjectId='3xg5wjqdtekbb3u')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_magic_face_usage
        # 获取魔法表情使用人数/Fetch magic face usage count
        result = await client.kuaishou_app.fetch_magic_face_usage(magic_face_id='11541661')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/app/fetch_magic_face_hot
        # 获取魔法表情热门视频/Fetch magic face hot videos
        result = await client.kuaishou_app.fetch_magic_face_hot(magic_face_id='11541661', pcursor='0', count=18)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
