"""Example: Kuaishou-Web-API

SDK attribute: ``client.kuaishou_web``
Endpoints: 13

Usage::

    python examples/kuaishou_web.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/kuaishou/web/fetch_one_video
        # 获取单个作品数据 V1/Get single video data V1
        result = await client.kuaishou_web.fetch_one_video(share_text='https://www.kuaishou.com/f/X-f2k5KJpiXN1SY')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_one_video_v2
        # 获取单个作品数据 V2/Get single video data V2
        result = await client.kuaishou_web.fetch_one_video_v2(photo_id='3xtdqvdnqd3psuc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_one_video_by_url
        # 链接获取作品数据/Fetch single video by URL
        result = await client.kuaishou_web.fetch_one_video_by_url(url='https://v.kuaishou.com/GKTpYm')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_one_video_comment
        # 获取作品一级评论/Fetch video comments
        result = await client.kuaishou_web.fetch_one_video_comment(photo_id='3x7gxp2zhgjv832')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_one_video_sub_comment
        # 获取作品二级评论/Fetch video sub comments
        result = await client.kuaishou_web.fetch_one_video_sub_comment(photo_id='3xgarycnydawq3g', pcursor='909377053156', root_comment_id='908850553827')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/generate_share_short_url
        # 生成分享短连接/Generate share short URL
        result = await client.kuaishou_web.generate_share_short_url(photo_id='3xtdqvdnqd3psuc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_user_info
        # 获取用户信息/Fetch user info
        result = await client.kuaishou_web.fetch_user_info(user_id='3xz63mn6fngqtiq')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_user_post
        # 获取用户发布作品/Fetch user posts
        result = await client.kuaishou_web.fetch_user_post(user_id='3xz63mn6fngqtiq')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_user_live_replay
        # 获取用户直播回放/Fetch user live replay
        result = await client.kuaishou_web.fetch_user_live_replay(user_id='3xz63mn6fngqtiq')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_user_collect
        # 获取用户收藏作品/Fetch user collect
        result = await client.kuaishou_web.fetch_user_collect(user_id='3xz63mn6fngqtiq')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_kuaishou_hot_list_v1
        # 获取快手热榜 V1/Fetch Kuaishou Hot List V1
        result = await client.kuaishou_web.fetch_kuaishou_hot_list_v1()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_kuaishou_hot_list_v2
        # 获取快手热榜 V2/Fetch Kuaishou Hot List V2
        result = await client.kuaishou_web.fetch_kuaishou_hot_list_v2(board_type='1')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/kuaishou/web/fetch_get_user_id
        # 获取用户ID/Fetch user ID
        result = await client.kuaishou_web.fetch_get_user_id(share_link='https://v.kuaishou.com/KcdKDwFp')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
