"""Example: TikHub-Downloader-API

SDK attribute: ``client.tikhub_downloader``
Endpoints: 2

Usage::

    python examples/tikhub_downloader.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/tikhub/downloader/version
        # 检查TikHub下载器的版本更新 / Check for TikHub Downloader version updates
        result = await client.tikhub_downloader.version()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tikhub/downloader/redirect_download
        # 重定向到最新版本的下载链接 / Redirect to the latest version download link
        result = await client.tikhub_downloader.redirect_download()
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
