"""Example: TikTok-Ads-API

SDK attribute: ``client.tiktok_ads``
Endpoints: 31

Usage::

    python examples/tiktok_ads.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/tiktok/ads/get_ads_detail
        # 获取单个广告详情/Get single ad detail
        result = await client.tiktok_ads.get_ads_detail(ads_id='7131673574381518849')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/search_ads
        # 搜索广告/Search ads
        result = await client.tiktok_ads.search_ads(objective=1, like=1, period=180, page=1, limit=20, order_by='for_you', country_code='US', ad_format=1, ad_language='en')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_keyword_insights
        # 获取关键词洞察数据/Get keyword insights data
        result = await client.tiktok_ads.get_keyword_insights(page=1, limit=20, period=7, country_code='US', order_by='post', order_type='desc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_top_products
        # 获取热门产品列表/Get top products list
        result = await client.tiktok_ads.get_top_products(last=7, page=1, limit=20, country_code='US', first_ecom_category_id='', ecom_type='l3', period_type='last', order_by='post', order_type='desc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_hashtag_list
        # 获取热门标签列表/Get popular hashtags list
        result = await client.tiktok_ads.get_hashtag_list(page=1, limit=20, period=120, country_code='US', sort_by='popular', industry_id='', filter_by='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_sound_rank_list
        # 获取热门音乐排行榜/Get popular sound rankings
        result = await client.tiktok_ads.get_sound_rank_list(period=30, page=1, limit=20, rank_type='popular', new_on_board=False, commercial_music=False, country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_keyword_list
        # 获取关键词列表/Get keyword list
        result = await client.tiktok_ads.get_keyword_list(keyword='cat toy', period=120, page=1, limit=6, country_code='US', industry='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_top_ads_spotlight
        # 获取热门广告聚光灯/Get top ads spotlight
        result = await client.tiktok_ads.get_top_ads_spotlight(industry='25000000000', page=1, limit=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_ad_keyframe_analysis
        # 获取广告关键帧分析/Get ad keyframe analysis
        result = await client.tiktok_ads.get_ad_keyframe_analysis(material_id='7213258221116751874', metric='retain_ctr')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_ad_percentile
        # 获取广告百分位数据/Get ad percentile data
        result = await client.tiktok_ads.get_ad_percentile(material_id='7213258221116751874', metric='ctr_percentile', period_type=180)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_ad_interactive_analysis
        # 获取广告互动分析/Get ad interactive analysis
        result = await client.tiktok_ads.get_ad_interactive_analysis(material_id='7213258221116751874', metric_type='remain', period_type=180)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_recommended_ads
        # 获取推荐广告/Get recommended ads
        result = await client.tiktok_ads.get_recommended_ads(material_id='7213258221116751874', industry='25308000000', country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_query_suggestions
        # 获取查询建议/Get query suggestions
        result = await client.tiktok_ads.get_query_suggestions(count=50, scenario=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_keyword_filters
        # 获取关键词筛选器/Get keyword filters
        result = await client.tiktok_ads.get_keyword_filters()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_related_keywords
        # 获取相关关键词/Get related keywords
        result = await client.tiktok_ads.get_related_keywords(keyword='free shipping', period=7, country_code='US', rank_type='popular', content_type='keyword', page=1, limit=50)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_keyword_details
        # 获取关键词详细信息/Get keyword details
        result = await client.tiktok_ads.get_keyword_details(keyword='', page=1, limit=20, period=7, country_code='US', order_by='post', order_type='desc')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_creative_patterns
        # 获取创意模式排行榜/Get creative pattern rankings
        result = await client.tiktok_ads.get_creative_patterns(first_industry_id='25000000000', period_type='week', order_field='ctr', order_type='desc', page=1, limit=20)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_product_filters
        # 获取产品筛选器/Get product filters
        result = await client.tiktok_ads.get_product_filters()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_product_metrics
        # 获取产品指标数据/Get product metrics
        result = await client.tiktok_ads.get_product_metrics(id='601583', last=30, metrics='post,ctr', ecom_type='l3', period_type='last', country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_product_detail
        # 获取产品详细信息/Get product detail
        result = await client.tiktok_ads.get_product_detail(id='601583', last=30, ecom_type='l3', period_type='last', country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_hashtag_filters
        # 获取标签筛选器/Get hashtag filters
        result = await client.tiktok_ads.get_hashtag_filters()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_hashtag_creator
        # 获取标签创作者信息/Get hashtag creator info
        result = await client.tiktok_ads.get_hashtag_creator(hashtag='blowup')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_sound_filters
        # 获取音乐筛选器/Get sound filters
        result = await client.tiktok_ads.get_sound_filters(rank_type='popular')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_sound_detail
        # 获取音乐详情/Get sound detail
        result = await client.tiktok_ads.get_sound_detail(clip_id='7251810329461147649', period=120, country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/search_sound_hint
        # 搜索音乐提示/Search sound hints
        result = await client.tiktok_ads.search_sound_hint(keyword='taylor swift', period=7, page=1, limit=5, rank_type='popular', country_code='US', filter_by_checked=False, commercial_music=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/search_sound
        # 搜索音乐/Search sounds
        result = await client.tiktok_ads.search_sound(keyword='taylor swift', period=7, page=1, limit=20, rank_type='popular', new_on_board=False, commercial_music=False, country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_sound_recommendations
        # 获取音乐推荐/Get sound recommendations
        result = await client.tiktok_ads.get_sound_recommendations(clip_id='7156826385225353217', limit=6)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_creator_filters
        # 获取创作者筛选器/Get creator filters
        result = await client.tiktok_ads.get_creator_filters()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_creator_list
        # 获取创作者列表/Get creator list
        result = await client.tiktok_ads.get_creator_list(page=1, limit=20, sort_by='follower', creator_country='US', audience_country='', audience_count=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/search_creators
        # 搜索创作者/Search creators
        result = await client.tiktok_ads.search_creators(keyword='jo', page=1, limit=20, sort_by='follower', creator_country='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/tiktok/ads/get_popular_trends
        # 获取流行趋势视频/Get popular trend videos
        result = await client.tiktok_ads.get_popular_trends(period=7, page=1, limit=10, order_by='vv', country_code='US')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
