"""Example: Toutiao-App-API

SDK attribute: ``client.toutiao_app``
Endpoints: 5

Usage::

    python examples/toutiao_app.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/toutiao/app/get_article_info
        # 获取指定文章的信息/Get information of specified article
        result = await client.toutiao_app.get_article_info(group_id='7450114952884503059')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/toutiao/app/get_video_info
        # 获取指定视频的信息/Get information of specified video
        result = await client.toutiao_app.get_video_info(group_id='7431543350882206242')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/toutiao/app/get_comments
        # 获取指定作品的评论/Get comments of specified post
        result = await client.toutiao_app.get_comments(group_id='7453372680222523931', offset='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/toutiao/app/get_user_info
        # 获取指定用户的信息/Get information of specified user
        result = await client.toutiao_app.get_user_info(user_id='1352838578180211')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/toutiao/app/get_user_id
        # 从头条用户主页获取用户user_id/Get user_id from user profile
        result = await client.toutiao_app.get_user_id(user_profile_url='https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
