"""Example: WeChat-Channels-V2-API

SDK attribute: ``client.wechat_channels_v2``
Endpoints: 12

Usage::

    python examples/wechat_channels_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # POST /api/v1/wechat_channels/v2/fetch_channel_info
        # 获取视频号账号信息/Get WeChat Channels Account Info
        result = await client.wechat_channels_v2.fetch_channel_info(username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_channel_id_to_username
        # 视频号ID转finder username/Convert Channel ID to Finder Username
        result = await client.wechat_channels_v2.fetch_channel_id_to_username(channel_id='sphi9BjV8GK0Zsl', raw=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_user_videos
        # 获取视频号用户作品列表/Get WeChat Channels User Videos
        result = await client.wechat_channels_v2.fetch_user_videos(username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', last_buffer='', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_video_detail
        # 获取视频号作品详情/Get WeChat Channels Video Detail
        result = await client.wechat_channels_v2.fetch_video_detail(object_id='14941130915890399732', export_id='', object_nonce_id='', share_url='', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_video_comments
        # 获取视频号作品评论/Get WeChat Channels Video Comments
        result = await client.wechat_channels_v2.fetch_video_comments(object_id='14941130915890399732', last_buffer='', comment_id='', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_video_share_url
        # 生成视频号作品分享链接/Generate WeChat Channels Video Share URL
        result = await client.wechat_channels_v2.fetch_video_share_url(object_id='14941130915890399732', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_user_profile
        # 获取视频号账号主页资料+统计/Get WeChat Channels User Profile & Stats
        result = await client.wechat_channels_v2.fetch_user_profile(username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_user_collections
        # 获取视频号合集列表/Get WeChat Channels User Collections
        result = await client.wechat_channels_v2.fetch_user_collections(username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_collection_videos
        # 获取视频号合集内视频/Get WeChat Channels Collection Videos
        result = await client.wechat_channels_v2.fetch_collection_videos(topic_id='14616794565351966924', topic='早安中国', username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', last_buffer='', topic_type=16, raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_live_history
        # 获取视频号直播回放列表/Get WeChat Channels Live History
        result = await client.wechat_channels_v2.fetch_live_history(username='v2_060000231003b20faec8cae1811ac4d5c702ea32b0771737aa785454f7f8177114cc4d248d66@finder', last_buffer='', flag=12, raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_live_detail
        # 获取视频号直播间详情/Get WeChat Channels Live Detail
        result = await client.wechat_channels_v2.fetch_live_detail(live_id='2078950291205875194', scene=5, finder_username='v2_060000231003b20faec8cae1811ac4d5c702ea32b0771737aa785454f7f8177114cc4d248d66@finder', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # POST /api/v1/wechat_channels/v2/fetch_search_channel_videos
        # 视频号号内搜索/Search Videos Within a WeChat Channel
        result = await client.wechat_channels_v2.fetch_search_channel_videos(username='v2_060000231003b20faec8c6e4811dc1d4c602ee30b0771bbcf220c67926bb76ab7702ac335a53@finder', keyword='新闻', raw=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
