"""Example: Weibo-Web-V2-API

SDK attribute: ``client.weibo_web_v2``
Endpoints: 33

Usage::

    python examples/weibo_web_v2.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/weibo/web_v2/check_allow_comment_with_pic
        # 检查微博是否允许带图评论/Check if Weibo allows image comments
        result = await client.weibo_web_v2.check_allow_comment_with_pic(id='5092682368025584')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_post_detail
        # 获取单个作品数据/Get single post data
        result = await client.weibo_web_v2.fetch_post_detail(id='5092682368025584', is_get_long_text='true')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_info
        # 获取用户信息/Get user information
        result = await client.weibo_web_v2.fetch_user_info(uid='1722594714', custom='shuqi')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_basic_info
        # 获取用户基本信息/Get user basic information
        result = await client.weibo_web_v2.fetch_user_basic_info(uid='7277477906')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_posts
        # 获取微博用户文章数据/Get Weibo user posts
        result = await client.weibo_web_v2.fetch_user_posts(uid='7277477906', page=1, feature=0, since_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_original_posts
        # 获取微博用户原创微博数据/Get Weibo user original posts
        result = await client.weibo_web_v2.fetch_user_original_posts(uid='7277477906', page=1, since_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_post_comments
        # 获取微博评论/Get Weibo comments
        result = await client.weibo_web_v2.fetch_post_comments(id='5283919831764022', count=10, max_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_post_sub_comments
        # 获取微博子评论/Get Weibo sub-comments
        result = await client.weibo_web_v2.fetch_post_sub_comments(id='5283574244704555', count=10, max_id='')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/search_user_posts
        # 搜索用户微博/Search user posts
        result = await client.weibo_web_v2.search_user_posts(uid='7277477906', q='', page=1, starttime=1772294400, endtime=1772294400, hasori=1, hasret=1, hastext=1, haspic=1, hasvideo=1, hasmusic=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_video_collection_list
        # 获取用户微博视频收藏夹列表/Get user video collection list
        result = await client.weibo_web_v2.fetch_user_video_collection_list(uid='7277477906')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_video_collection_detail
        # 获取用户微博视频收藏夹详情/Get user video collection detail
        result = await client.weibo_web_v2.fetch_user_video_collection_detail(cid='4883992307236954', cursor='', tab_code=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_video_list
        # 获取微博用户全部视频/Get user all videos
        result = await client.weibo_web_v2.fetch_user_video_list(uid='7277477906', cursor='0')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_following
        # 获取用户关注列表/Get user following list
        result = await client.weibo_web_v2.fetch_user_following(uid='1722594714', page=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_fans
        # 获取用户粉丝列表/Get user fans list
        result = await client.weibo_web_v2.fetch_user_fans(uid='1722594714', page=0)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_all_groups
        # 获取所有分组信息/Get all groups information
        result = await client.weibo_web_v2.fetch_all_groups()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_recommend_timeline
        # 获取微博主页推荐时间轴/Get user recommend timeline
        result = await client.weibo_web_v2.fetch_user_recommend_timeline(refresh=0, group_id='102803', containerid='102803', extparam='discover|new_feed', max_id='0', count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_hot_ranking_timeline
        # 获取微博热门榜单时间轴/Get hot ranking timeline
        result = await client.weibo_web_v2.fetch_hot_ranking_timeline(ranking_type='hour', since_id='0', max_id='0', count=10)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_hot_search_index
        # 获取微博热搜词条(10条)/Get Weibo hot search index (10 items)
        result = await client.weibo_web_v2.fetch_hot_search_index()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_hot_search_summary
        # 获取微博完整热搜榜单(50条)/Get Weibo complete hot search ranking (50 items)
        result = await client.weibo_web_v2.fetch_hot_search_summary()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_hot_search
        # 获取微博热搜榜单/Get Weibo hot search ranking
        result = await client.weibo_web_v2.fetch_hot_search()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_entertainment_ranking
        # 获取微博文娱榜单/Get Weibo entertainment ranking
        result = await client.weibo_web_v2.fetch_entertainment_ranking()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_life_ranking
        # 获取微博生活榜单/Get Weibo life ranking
        result = await client.weibo_web_v2.fetch_life_ranking()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_social_ranking
        # 获取微博社会榜单/Get Weibo social ranking
        result = await client.weibo_web_v2.fetch_social_ranking()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_similar_search
        # 获取微博相似搜索词推荐/Get Weibo similar search recommendations
        result = await client.weibo_web_v2.fetch_similar_search(keyword='#微博奇遇记#')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_ai_search
        # 微博智能搜索/Weibo AI Search
        result = await client.weibo_web_v2.fetch_ai_search(query='#法国#')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_ai_related_search
        # 微博AI搜索内容扩展/Weibo AI Search Content Extension
        result = await client.weibo_web_v2.fetch_ai_related_search(keyword='#微博奇遇记#')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_advanced_search
        # 微博高级搜索/Weibo Advanced Search
        result = await client.weibo_web_v2.fetch_advanced_search(q='yu7', search_type='hot', include_type='pic', timescope='custom:2025-09-01-0:2025-09-08-23', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_city_list
        # 地区省市映射/Region City List
        result = await client.weibo_web_v2.fetch_city_list(normalized=True)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_realtime_search
        # 实时搜索/Weibo Realtime Search
        result = await client.weibo_web_v2.fetch_realtime_search(query='yu7', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_user_search
        # 用户搜索/User search
        result = await client.weibo_web_v2.fetch_user_search(query='yu7', page=1, region='custom:11:1', auth='org_vip', gender='man', age='22y', nickname='张三', tag='摄影', school='清华大学', work='字节跳动')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_video_search
        # 视频搜索（热门/全部）/Weibo video search (hot/all)
        result = await client.weibo_web_v2.fetch_video_search(query='yu7', mode='hot', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_pic_search
        # 图片搜索/Weibo picture search
        result = await client.weibo_web_v2.fetch_pic_search(query='yu7', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/weibo/web_v2/fetch_topic_search
        # 话题搜索/Weibo topic search
        result = await client.weibo_web_v2.fetch_topic_search(query='yu7', page=1)
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
