"""Example: Xiaohongshu-Web-V3-API

SDK attribute: ``client.xiaohongshu_web_v3``
Endpoints: 5

Usage::

    python examples/xiaohongshu_web_v3.py

AUTO-GENERATED by scripts/generate_examples.py.
"""

import asyncio
import json

from tikhub import AsyncTikHub

API_KEY = "YOUR_API_KEY"


async def main():
    async with AsyncTikHub(api_key=API_KEY) as client:

        # GET /api/v1/xiaohongshu/web_v3/fetch_note_detail
        # 获取笔记详情/Fetch note detail
        result = await client.xiaohongshu_web_v3.fetch_note_detail(note_id='6a2f423d000000001003cb36', xsec_token='ABtexB6bX5HgLD42SFrK1scGUmSO8YV5_isaLrDy9sLxQ=')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_search_suggest
        # 获取搜索联想词/Fetch search suggestions
        result = await client.xiaohongshu_web_v3.fetch_search_suggest(keyword='口红')
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_homefeed
        # 获取首页推荐/Fetch homepage feed
        result = await client.xiaohongshu_web_v3.fetch_homefeed(num=20, cursor_score='', category='homefeed_recommend', need_filter_image=False)
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_homefeed_categories
        # 获取首页分类列表/Fetch homepage categories
        result = await client.xiaohongshu_web_v3.fetch_homefeed_categories()
        print(json.dumps(result, indent=2, ensure_ascii=False))

        # GET /api/v1/xiaohongshu/web_v3/fetch_user_info
        # 获取用户信息/Fetch user info
        result = await client.xiaohongshu_web_v3.fetch_user_info(user_id='5e3a8ee700000000010070c6')
        print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    asyncio.run(main())
